### ISSUE TITLE
iOS extensions warnings when building via carthage

### ISSUE THREAD

**Issue by JamieWhite** [ProcedureKit/ProcedureKit#112]
How do I build the iOS extensions framework so I can silence the extension warning?

**Comment by danthorpe** [comment]
Hi @JamieWhite, I there is a bug here I think, the module names are all just `Operations` and so the files made for the framework is just `Operations.framework` which means that while Carthage does correctly build all the frameworks, when it builds the `iOS` framework it overwrites the `iOS-Extension` framework.

If you have a fork, you could rename the Product Name in the iOS Extension target to `Operations-Extension` or something. This would be the first thing I would try, as I think it will change the files that carthage generates.

Also, I've removed the zip from the 2.4.0 release in Github. So, running `update` will now build.

```bash
$ carthage update
*** Fetching Operations
*** Checking out Operations at "2.4.0"
*** xcodebuild output can be found in /var/folders/6j/9k2drdbs1fv9fw5d6wng5yzh0000gn/T/carthage-xcodebuild.Y9xU8c.log
*** Building scheme "Operations-OSX" in Operations.xcodeproj
*** Building scheme "Operations-watchOS" in Operations.xcodeproj
*** Building scheme "Operations-tvOS" in Operations.xcodeproj
*** Building scheme "Operations-iOS-Extension" in Operations.xcodeproj
/Users/daniel/Desktop/Operations-examples/Carthage/Checkouts/Operations/Operations/Extras/AddressBook/iOS/AddressBook.swift:644:11: warning: 'AddressBook' was deprecated in iOS 9.0
/// Plus lots more AddressBook related warnings...

Ice:Operations-examples daniel$ 
```

**Comment by JamieWhite** [comment]
Seems someone has spoke to Carthage about this: https://github.com/Carthage/Carthage/issues/933

**Comment by JamieWhite** [comment]
Looks like we're still waiting on Carthage for this. I think Im gonna try and get my fork workable in extensions for the time being. I'm still using PSOperations and I'm keen to get off it.

**Comment by danthorpe** [comment]
Yeah, looks like it, although I'm not had a chance to catch up on where Carthage is. If anyone has any suggestions to get round this - PRs are more than welcome!

**Comment by JamieWhite** [comment]
Interesting update out by Carthage: https://github.com/Carthage/Carthage/releases/tag/0.12

I noticed you had a separate xcodeproj setup for the extension target so I changed it's product name like so https://github.com/JamieWhite/Operations/commit/24d356a87324f3e897a6946f6fa8472b99bdd94c and it didn't overwrite the main xcodeproj

**Comment by danthorpe** [comment]
Hi @JamieWhite - interesting, I'll have a look at what Carthage are doing tonight hopefully.

If you change the `PRODUCT_NAME` like this, are you keeping the "module name" the same? I tried many different variations (of the build settings) on this theme and could not get to a point where the actual files produced were named differently, yet the module name was the same. 

Part of my reasoning at the time was so that the unit tests would run in the extension compatible project. At the moment, these are not run in the CI unit tests, however, I didn't want to leave it where I couldn't run the tests in that project, as otherwise it would make it quite fragile to keep up-to-date and maintain.

Happy to receive feedback on this though, as *working* is obviously much better than having something which is easy to maintain yet doesn't work :)

**Comment by danthorpe** [comment]
Hi @JamieWhite - just wanted to keep you up to date with where I am on this issue.

Unfortunately, I'm not going to get round to fixing this for v2.6.0. Sorry about that. The reason being that it's already been almost 2 months of development, so bug fixes need to get merged and released.

I think for v2.7, I will start to look at making a workspace with nested projects / modules which will hopefully solve this issue.

**Comment by JamieWhite** [comment]
Hey, sorry I've been on holiday. I'm planning to have a play around and familiarise myself with the project this weekend to try and propose something.

**Comment by robfeldmann** [comment]
Hi @JamieWhite and @danthorpe, I was just wondering if there's been an update on this issue, or a solid workaround that you might be familiar with. I need to use Carthage for my project and have been running into this issue still. My workaround for now is to drag all the source files into my workspace, which is very undesirable. 

I still need to try changing the product name in a fork to see if I can get that working, but did want to follow up on this issue just in case there is a better solution. Thanks!

**Comment by danthorpe** [comment]
@robfeldmann @JamieWhite - take a look at the [recent release notes](https://github.com/danthorpe/Operations/releases/tag/2.9.1) for v2.9. There is a "solid" work around - although I haven't yet uploaded the binaries for v2.10.1.

To be honest, sorting this stuff out is almost certainly going to be the first thing I talk to  Engineers about at WWDC. My concern is that the "proper solution" won't actually be available until Swift 3.0 & Swift PM.

Have either of you come up with any other options / solutions?

**Comment by robfeldmann** [comment]
@danthorpe Yes, using the binaries as described in the 2.9 release notes does work for me as I actually don't need the extensions compatible API for this project (but I will for my next project). I should be able to do that for 2.10.1 (which contains location fixes that I need) once you post those binaries.

I can never seem to get building my own binaries to work, however (i.e., using `carthage update --no-use-binaries --platform iOS`). One of the operations I'm using is the `UserLocationOperation` and when not using binaries it's never available. It's like the header is never included for some reason. So, that's the true issue I'm trying to solve actually.

**Comment by danthorpe** [comment]
Oh. Well that is strange, I've not noticed this issue - will look into it.

One thing you could try, is to maintain a fork, where you delete the extension compatible Xcode project. Just keep rebasing this commit to stay up-to-date. Then Carthage only has one Xcode project to build - so, in theory is a lot less likely to have issues.

**Comment by JamieWhite** [comment]
So I think the best approach for getting this to work with Carthage is to split the framework into several frameworks like Core (App extension happy) and other

**Comment by danthorpe** [comment]
@JamieWhite yeah, I agree that breaking the framework up into modules is the best solution. I'm just a little hesitant to do this, as without using Swift PM I'm not entirely sure how I can get the nested modules to work.

For example, lets say you want to use `CloudKitOperation` and friends, how would the import look?

```swift
import Operations.CoreData
```

which is fine - it's a breaking change but, can't really get around that. But, I'm not entirely sure how to do this with the current development tools. I think maybe it would be some kind of custom module map file - but, not really found much in terms of documentation or examples on this. Maybe it's not possible, and instead we'd have this:

```swift
import Operations_CoreData
```

which is so much worse. This will require each module to have its own project, targets, tests, dependencies - it'll turn into a configuration & maintenance nightmare. I *think* with Swift PM that this sort of thing will be trivial, as there are no projects, and the Swift files will just live in a nice folder hierarchy (like they currently are). Hence - I'm going to see if I can speak with the SwiftPM engineers at WWDC.

**Comment by JamieWhite** [comment]
How about an app extension only target?

**Comment by danthorpe** [comment]
Well, this is what we used to have, but Carthage has know knowledge of extension API targets. So, it will build the iOS app target, and put it inside `Carthage/Build/iOS/Operations.framework` and then overwrite this with the extension compatible one. Or visa-versa.

**Comment by JamieWhite** [comment]
I think it's acceptable to name it OperationsAppExtension.framework

**Comment by danthorpe** [comment]
@JamieWhite - gonna finally close this! See: #493
