### ISSUE TITLE
More convenient operation dependency sequence creation

### ISSUE THREAD

**Issue by jshier** [ProcedureKit/ProcedureKit#176]
I've found myself rebuilding my `Operations` based networking layer recently and have gotten rather sick of the `declare operation -> add conditions/observer -> declare second operation -> add conditions/observers -> add first operation dependency to second operation -> etc.` code I write rather frequently. Plus, I'm rather a fan of some of the asynchronous sequence code I've see used by the various promise libraries or the [Async library](https://github.com/duemunk/Async). So I created the following extensions as a first take on such a feature:

``` swift
extension NSOperation {    
    func then(operationClosure: () -> NSOperation) -> [NSOperation] {
        let operation = operationClosure()
        operation.addDependency(self)

        return [self, operation]
    }
}

extension CollectionType where Generator.Element == NSOperation, Index: BidirectionalIndexType {
    func then(operationClosure: () -> Generator.Element) -> [Generator.Element] {
        let operation = operationClosure()
        var allOperations = Array(self)

        if let lastOperation = allOperations.last {
            operation.addDependency(lastOperation)
        }

        allOperations.append(operation)

        return allOperations
    }
}
```

Which can be used like:

``` swift
static func sequenceOfOperations(completionHandler: () -> ()) {
    sharedManager.addOperations(InterruptibleNetworkOperation<HTTPBinResponse>(request: APIRouter.GET)
        .then { InterruptibleNetworkOperation<HTTPBinResponse>(request: APIRouter.GET) }
        .then { InterruptibleNetworkOperation<HTTPBinResponse>(request: APIRouter.GET) }
        .then { BlockOperation(mainQueueBlock: completionHandler) }, waitUntilFinished: false)
}
```

I can see this extended with something like `thenIf(predicate:)` which would attach a condition to the operation, or perhaps a call to add an observer.

So my question is, would this be valuable for the library? What immediate improvements or ideas do you see?

**Comment by danthorpe** [comment]
This is really interesting, and quite serendipitous - see my [tweets from yesterday](https://twitter.com/danthorpe/status/694986693796085760). 

I've also been thinking about making chaining operations easier to write, as its such a common scenario, and in general I think it makes sense to promote `Operation` subclasses which are small and easily composed. To this end, I've done some stuff on [Result Injection](https://github.com/danthorpe/Operations/blob/development/Sources/Core/Shared/ResultInjection.swift) which is in v2.5, and [Functional Operations](https://github.com/danthorpe/Operations/blob/development/Sources/Core/Shared/FunctionalOperations.swift) which will be in v2.6. I also went quite a bit further in #150 defining a `OperationFlow` class, [which I eventually deleted](https://github.com/danthorpe/Operations/commit/a902cc64b476234a25f0ce128572d71f4f7d3132).

All of this is to say, despite my final tweet last night, that I think you're on to something here, and the framework should definitely make it easier to manage "chains" or sequences of Operations.

I think your initial approach here of just dealing with regular dependency using `then`, and not worries too much about injecting results into requirements, nor map, filter or reduce operations is a good start. This is partly why I backtracked in #150 and am not 100% convinced by the functional operations stuff. 

However, I also quite like the idea of a "flow" object (from that deleted code in #150) which owns the array of `Operation` instances and allows the consumer to terminate the sequence with a completion block (of sorts) which returns the final array of operations.

In your example - can you explain the usage or your proposal a bit clearer? i.e. what is this static function, and what is the `sharedManager`?

So... in conclusion, I think the framework will definitely get round to supporting something like this, so lets keep the conversation going and figure out the most suitable structure, with a view to having something in v2.7 or v2.8.

At the moment, I want to focus on getting 2.6 merged & released (this weekend, fingers crossed).

**Comment by danthorpe** [comment]
Hi @jshier - have you had any more thoughts on this?

**Comment by danthorpe** [comment]
@jshier - after our discussions about this at WWDC - still interested in looking into it, but haven't got capacity to do so now....

**Comment by danthorpe** [comment]
Done in #536.
