### ISSUE TITLE
Protocols for testability

### ISSUE THREAD

**Issue by sfaxon** [ProcedureKit/ProcedureKit#323]
I was inspired by Natasha the Robot's recent blog post titled [Protocol Oriented Networking in Swift](https://www.natashatherobot.com/protocol-oriented-networking-in-swift/) to start testing my ViewControllers using protocols as a means of dependency injection. 

I wrote a class that wraps the current OperationQueue so that I can create my own delegate methods that use a protocol (OperationType) rather than NSOperations: 

```swift
protocol OperationType {
    func execute()
}

extension Operation: OperationType { }

// Extending Operations to support structs for testing
protocol FNSOperationQueueDelegate: class {
    
    // --> Use the OperationType protocol here rather than NSOperation
    func operationQueue(queue: FNSOperationQueue, willAddOperation operation: OperationType)
    
    func operationQueue(queue: FNSOperationQueue, operationDidFinish operation: OperationType, withErrors errors: [ErrorType])
}

class FNSOperationQueue {
    private let queue = OperationQueue()
    private var operationQueueDelegeate: OperationQueueDelegate? = .None
    
    var delegate: FNSOperationQueueDelegate? = .None {
        didSet {
            self.queue.delegate = self
        }
    }
    
    func addOperation(op: OperationType) {
        // it might be better to check if the operation conforms to some kind of MockOperation protocol here
        if let operation = op as? Operation {
            queue.addOperation(operation)
        } else {
            // structs that conform to OperationType for testing
            // immediately call delegate methods
            if let d = self.delegate {
                d.operationQueue(self, willAddOperation: op)
                d.operationQueue(self, operationDidFinish: op, withErrors: [])
            }
            op.execute()
        }
    }
    
    func addOperations(ops: [OperationType], waitUntilFinished wait: Bool) {
        if let operations = ops as? [Operation] {
            queue.addOperations(operations, waitUntilFinished: wait)
        } else {
            ops.forEach(addOperation)
        }
    }
}

// just forwarding the delegate calls along to FNSOperationQueue
extension FNSOperationQueue: OperationQueueDelegate {
    func operationQueue(queue: OperationQueue, willAddOperation operation: NSOperation) {
        guard let d = self.delegate else { return }
        
        if let op = operation as? OperationType {
            d.operationQueue(self, willAddOperation: op)
        }
    }
    
    func operationQueue(queue: OperationQueue, operationDidFinish operation: NSOperation, withErrors errors: [ErrorType]) {
        guard let d = self.delegate else { return }
        
        if let op = operation as? OperationType {
            d.operationQueue(self, operationDidFinish: op, withErrors: errors)
        }
    }
}
```

I'm using Operations to wrap most of my network calls, for example, the truncated Login operation looks like this:

```swift
protocol LoginOperationType: OperationType {
    var loginResponse: LoginResource? { get }
    var email: String { get }
}

class LoginOperation: Operation, LoginOperationType {

    var loginResponse: LoginResource?
    var email: String = ""
    private var password: String = ""
    
    init(email: String, password: String) {
        self.email = email
        self.password = password
        super.init()
        self.addObserver(NetworkObserver())
    }
    
    override func execute() {
        guard !cancelled else { return }
        let loginRequest = LoginRequest(email: self.email, password: self.password)
        
        Alamofire.request() // networking bits with calls to finish() and finish(error:)
}
```

My LoginViewController uses the wrapped queue and provides a method for tests to add operations to the queue, where they can be proper Operations, or an object conforming to the LoginOperationType protocol: 

```swift
    private lazy var queue: FNSOperationQueue = {
        var q = FNSOperationQueue()
        q.delegate = self
        return q
    }()

    // method callable in tests, that also allows a mocked object that conforms to the LoginOperationType protocol
    func addLoginToQueue(operation: LoginOperationType) {
        queue.addOperation(operation)
    }
```

And finally, my test can use a struct to mock the operation, allowing me to test views without making network calls:

```swift 
class LoginViewControllerTest: XCTestCase {
    
    let loginViewController: LoginViewController = {
        let storyboard = UIStoryboard(name: "Main", bundle: NSBundle.mainBundle())
        return storyboard.instantiateViewControllerWithIdentifier("LoginViewController") as! LoginViewController
    }()
    
    override func setUp() {
        super.setUp()

        UIApplication.sharedApplication().keyWindow!.rootViewController = loginViewController
        let _ = loginViewController.view
    }

    func testLoginTransition() {

        struct MockLoginOperation: LoginOperationType {
            let loginResponse: LoginResource? = LoginResource() // Struct representing parsed network response
            let email: String = "foo@bar.com"
            
            func execute() {
            }
        }
        
        loginViewController.addLoginToQueue(MockLoginOperation())
        // XCTestAssert's
        
    }
}
```

I've just recently started using this and would really appreciate feedback. Is there a better way to test controllers that depend on operations that I should be using instead?

If there is not a better way, would supporting passing a protocol in place of NSOperation's be considered for Operations 3.0? Protocol Oriented Programming seems to be a pretty popular topic to blog about this week 😄 . In the couple of hours I've played with this I like the flexibility it seems to give, but I'm concerned that it may not work great with the NSOperation & NSOperationQueue classes long term. I would appreciate to hear feedback from people with more experience working with these libraries. 

Thanks!

**Comment by danthorpe** [comment]
Hi @sfaxon - this is great! Thanks for the feedback.

I've not read through all your code samples yet. And, yes, as you can probably guess from [looking through this codebase](https://github.com/danthorpe/Operations/blob/development/Sources/Features/Shared/CloudKit/CloudKitInterface.swift), I'm a huge fan of abstracting class APIs into protocols for testing.

So, I think you are almost certainly doing the correct thing. 👍 

Regarding `OperationType` in *Operations* v3 - this was actually my initial main goal with v3 as a way to eventually move away from a predominately inheritance based architecture. I have even done some work to this end - but it is currently shelved. Then the refactor of `OperationCondition` to be an `Operation` subclass sort of required a major version increment a bit earlier than I intended. So, at the moment, `NSOperationType`, `OperationType` and their equivalent queue variants are not in the scope for v3.

My top goals for 3.0 are:

- [x] Refactor `Operation` state, conditions & work around KVO bug
- [ ] API consistency & complete documentation/wiki (In Progress)
- [ ] Improve error handling model for `CloudKitOperation` (In Progress)
- [ ] Improve timeout behaviour & bugs for Location Operations
- [ ] Module map, naming, extension API compatible issues. (In Discussion)

In the back of my mind, I'm thinking that protocol based APIs & Swift 3.0 support would be the major changes for *Operations v4* - but if you want to help and contribute a pull request, then I don't see why it couldn't make it for v3. Or, v3.* as it shouldn't be a breaking change. 😃

Also, something which I am going to do in the next few days is put this Roadmap into the Wiki, although of course, nothing is set in stone.

**Comment by sfaxon** [comment]
I'll try to make some time to explore making this change. Should I work off of the development branch?

**Comment by danthorpe** [comment]
Yes please! 😃

**Comment by danthorpe** [comment]
Hi, @sfaxon I'm going to close this ticket now.

Protocols for testability are part of the work currently being done for _ProcedureKit_ and v4, as you can see in the `development` branch and `ProcedureProtocol`. It's a work in progress - but will continue to develop and evolve the protocols.
