### ISSUE TITLE
Operation which depends on the network operation

### ISSUE THREAD

**Issue by razalur** [ProcedureKit/ProcedureKit#340]
Hello!

I have one more error with operations usage
So I have an operation which download data and then another operation parse this data.
But sometimes I have a crash on parsing data cause the data to parse is nil. It seems that sometimes parsing operation starts earlier than the downloading operation finishes. Is it a possibility to find out the reason of such crash? Or may be you can tell me why so by looking at my code?

```
class GetAndSaveAuthorOperation: GroupOperation {
    init(guid: String, context: NSManagedObjectContext) {
        let url = NSURL(string: GET_AUTHOR_SERVLET_URL)!
        let authorRequest = NSMutableURLRequest(URL: url)
        authorRequest.HTTPMethod = "POST"
        authorRequest.HTTPBody = String("\(POST_PARAM_GUID)=\(guid)").dataUsingEncoding(NSUTF8StringEncoding)
        
        let downloadAuthor = DownloadDataOperation(request: authorRequest)
        
        let parseAuthor = ParseAuthorOperation(mainContext: context)
        parseAuthor.injectResultFromDependency(downloadAuthor)
        
        super.init(operations: [parseAuthor, downloadAuthor])
    }
}

class DownloadDataOperation: GroupOperation, ResultOperationType {
    let request: NSMutableURLRequest
    private(set) var result: NSData?

    init(request: NSMutableURLRequest) {
        self.request = request
  
        super.init(operations: [])
        
        let task = NSURLSession.sharedSession().dataTaskWithRequest(request) { data, response, error in
            if let error = error {
                print("Can't download! Cause ...")
            }
            else {
                self.result = data
            }
        }

        let taskOperation = URLSessionTaskOperation(task: task)
        self.addOperation(taskOperation)
    }
}

class ParseAuthorOperation: Operation, AutomaticInjectionOperationType {
    var requirement: NSData?

    let mainContext: NSManagedObjectContext
    var privateContext: NSManagedObjectContext!
   
    init(mainContext: NSManagedObjectContext) {
        self.mainContext = mainContext
        
        super.init()
    }
    
    override func execute() {
        guard !cancelled else { return }
        
        self.privateContext = NSManagedObjectContext(concurrencyType: .PrivateQueueConcurrencyType)
        self.privateContext.parentContext = self.mainContext
        
        do {
            /// Here I have a crash sometimes, cause requirement is nil
            let wrappedJson = try NSJSONSerialization.JSONObjectWithData(requirement!, options: .MutableLeaves) as? Dictionary<String, AnyObject>

            if let author = wrappedJson?[JSON_PARAM_DATA] as? [String: AnyObject] {
                parse(author)
            } else {
                print("cant unwrap author json")
            }
            finish()
        } catch let jsonError as NSError {
            print("ParseAuthorOperation error")
            finish()
        }
    }
```

**Comment by danthorpe** [comment]
Hi @razalur - just getting back from WWDC - will have a look into this.

At first glance, it looks like the issue is with `DownloadDataOperation`. In the un-happy path version, the `result` property is not set, which I think might be why when it's enclosing operation finishes, and the next one starts, that fails as the result is nil.

**Comment by razalur** [comment]
Yes, I thought such as you. But in un-happy path version of my DownloadDataOperation I have to get "Can't download! Cause ...". But I do not get it.
To make sure that the problem is not in downloading part I decide to print all the data I receive. And now I can see that the data receives correctly. But sometimes parse operation (that depends on downloading operation) begins earlier then downloading operation finishes. That why I have a nil in result of downloading. But why so... That's a secret for me(

**Comment by danthorpe** [comment]
Well, this is because the `NSURLSessionTask` operation has an async callback - but there is no inherent dependency here between this and the containing group. When that block is invoked is undefined with respect to the state of the operation. You might want to look at `NetworkOperation` or writing your own wrapper.
