### ISSUE TITLE
Operations Roadmap, Swift 3.0 & naming changes

### ISSUE THREAD

**Issue by danthorpe** [ProcedureKit/ProcedureKit#343]
This ticket is to track and document the transition path of this project and the migration path for consumers of this project to Swift 3.0. There are a number of things which will happen.

## Overall Migration Plan

1. Adopting a new name. As `Operation` has effectively been sherlocked by Swift 3.0, we need to pick a new name. The new name cannot have any other Swift 3.0 naming issues, such as `Task`, or maybe `Job`. So, currently settled on `Procedure`.

2. Refactor `Operation` to `Procedure` and `OperationQueue` to `ProcedureQueue`

3. Rename the project / module name. Rather than *Operations*, I am thinking *ProcedureKit*.

4. Move to an organisation account - again, [**ProcedureKit**](https://github.com/ProcedureKit).

In order for framework consumers to migrate with relative ease, this will need to be done in stages.

1. A future version of *Operations* in Swift 2.2/2.3 will deprecate `Operation` and `OperationQueue` and related types will need to be changed too, with Fix-It `@available()` helpers. Potentially this will be v3.0 of *Operations*.

2. Move code (and history) to **ProcedureKit** with a Swift 3.0 version. This would probably also require a rename in CocoaPods too.

## Support branches for framework consumers

- [x] Swift 2.3
  ✅ Integrate branch `swift/2.3` into your project.

- [ ] Swift 3.0
  ⚠️ Integrate branch `swift/3.0` into your project.

**Comment by maxydon** [comment]
I wander if  `public enum Queue` is still needed since in swift 3 they changed the GCD to be like this `DispatchQueue.main.async{}`

**Comment by blg-andreasbraun** [comment]
Thought the same thing yesterday while I was playing around in Xcode 8 with the framework.

**Comment by danthorpe** [comment]
Hey, yep, this is happening - did most of the refactor today in the Swift Open Hours lab. Just haven't pushed it yet. Keep an eye on #343 and swift/3.0 branch.

Annoyingly, the GCD talk isn't until Friday. So, everything is subject to change...

Cheers,
Dan

**Comment by danthorpe** [comment]
Hey. Just to clarify - will include here breaking changes, such as deprecation of Queue as necessary for each version. Will also include fix-its where possible.

**Comment by maxydon** [comment]
You at wwdc too? Let's meet!! I know it's abuse of this comment but let me know!

**Comment by danthorpe** [comment]
@maxydon yeah, I'm mostly in the labs. My DMs are open on Twitter ([@danthorpe](https://twitter.com/danthorpe)) if you want to contact me while you're here. Really happy to meet and chat to you all - whether you use Operations or not, it's what WWDC is all about! 😀

**Comment by maxydon** [comment]
Funny, Amazon People called it AWSTask https://github.com/aws/aws-sdk-ios

**Comment by thisismcgregor** [comment]
@danthorpe is the `swift/2.3` branch going to be merged into develop and pushed as a release or should we just build from that branch in the interim (until 3.0 is wrapped up)? It was only a matter of time until Operation was sherlocked. 😆

**Comment by danthorpe** [comment]
Hi @thisismcgregor - well, yeah, at the moment use `master` - most stable, `develop` - essentially this is preview of Operations v3 just got a few bits and bobs to do. And use `swift/2.3` if you want to use Xcode 8, will sort out `swift/3.0` shortly too.

Probably won't merge `swift/2.3` into `develop` until the release timeline of Xcode 8 is clearer, however, it will track `develop` as closely as possible.

After v3 - priorities for this project is to transition towards new names tied into the Swift 3.0 releases, which will likely result in a v4 (for name changes) and then v5 (for Swift 3.0).

**Comment by cezarywojcik** [comment]
I prefer `Operation` -> `AdvancedOperation` and `OperationQueue` -> `AdvancedOperationQueue`. It's a more accurate representation of _what_ the class actually represents + is a good nod back to the original talk that introduced many of these concepts. Calling it `Procedure` could be confusing because it isn't immediately obvious that a `Procedure` is a subclass of `NSOperation`.

**Comment by danthorpe** [comment]
@cezarywojcik - appreciate the input, however...

I don't think that `AdvancedOperation` is a good name for this - "Advanced" is a fairly meaningless and vague adjective in this context: _advanced_ how? It just makes the class name longer. I might as well just name it `DTOperation`. This "prefix" approach has been used by the GCD team for their Swift 3.0 improvements, but in their case, prefixing their types with `Dispatch`, a noun, works well. A `DispatchSource` and `DispatchQueue` are much better names than `Source` and `Queue`.

Additionally, `Procedure` will almost certainly be a protocol. The superclass of its concrete class is purely an implementation detail, and may not always be `Foundation.Operation`, so I don't think that it will be confusing.

**Comment by morisk** [comment]
Procedure is a bad name for searches.

 I found this amazing framework by searching `Operation` and I would never find it with new name. I think keeping Operation in name is essential. To overcome overlapping maybe some crazy naming would be in place like: 
`Operate`
`Operation1`
`DOperation`
`Op`

and still call this framework Operation / Operation Kit 
I like the `Op` -> `OpQueue` -> `OpBlock`

**Comment by danthorpe** [comment]
@morisk it's a fair comment of course. When I transfer the repository to an org, GitHub re-directs traffic automatically, so visitors landing on `danthorpe/Operations` will get transferred automatically with the appropriate re-direct headers.

In terms of search terms, clearly the phrase "operation" and "advanced operation" is not going anywhere, so I'm confident that discoverability will not be diminished in the long run.

**Comment by danthorpe** [comment]
While this issue is not exactly done - the discussion has moved onto #398 which lays out the roadmap for Swift 3.0 support and _ProcedureKit_.
