### ISSUE TITLE
Timer in NetworkObserver doesn't work as expected

### ISSUE THREAD

**Issue by ryanjm** [ProcedureKit/ProcedureKit#344]
I need to write some tests to verify this, but I believe the [Timer](https://github.com/danthorpe/Operations/blob/d2c3dce9227d926a4112f60a9a997b5ef2f48371/Sources/Core/iOS/NetworkObserver.swift#L97-L113) doesn't work as expected. I believe that `self.isCancelled` is captured at the time the block is created and never gets updated.

I ended up copying the `Timer` into my project and noticed that it kept running even after I cancelled it. I couldn't figure out how to get `dispatch_after` to work in a Playground but I restructured it a little and this playground gets the point across:

```swift
struct Timer {

    var isCancelled = false
    var block: dispatch_block_t = {}
    var msg: String = ""

    init(_ handler: dispatch_block_t) {
        msg = "abc"
        block = {
            print("  inside block: \(self.isCancelled)")
            print("  msg: \(self.msg)")
            if self.isCancelled != true {
                handler()
            }
        }
    }

    mutating func cancel() {
        print("cancel = true")
        self.isCancelled = true
        self.msg += "123"
    }

    func runBlock() {
        print("running block (self.msg = \(self.msg))")
        block()
    }
}

var t = Timer {
    print("---")
}

t.runBlock()
t.cancel()
t.runBlock()
```

The output is:

```
running block (self.msg = abc)
  inside block: false
  msg: abc
---
cancel = true
running block (self.msg = abc123)
  inside block: false
  msg: abc
---
```

So you can see the values inside the block are captured at the time it is created and never updated. If anyone knows how to make the values in the block update properly, please let me know. Otherwise I'll keep looking for the solution...

**Comment by ryanjm** [comment]
I haven't been able to figure it out. It looks like it has to do with it being a `struct` vs `class`. Everything says "you can capture values" as if the default is that it shouldn't be. But with a `struct` it appears to capture the values. Changing it to a `class` makes it work.

**Comment by danthorpe** [comment]
Hi @ryanjm - yes, this is almost certainly a value vs reference issue. Must be some poor testing around this I think.
