### ISSUE TITLE
CloudKitOperation not handling moreComing flag

### ISSUE THREAD

**Issue by leotumwattana** [ProcedureKit/ProcedureKit#366]
## Issue
As per our initial conversation on Slack. It seems CloudKitOperation is not handling the `moreComing` flag. At least for `Operation v3.0`. I haven't checked earlier versions of the library.

## Investigation
After some initial digging under the hood, I'm guessing `moreComing` is suppose to be handled by `BatchedCloudKitOperation<...>`? Please correct me if I'm wrong. So the magic is coming from `willFinishOperation`? 

```
public override func willFinishOperation(operation: NSOperation) {
        if let cloudKitOperation = operation as? CloudKitOperation<T> {
            generator.more = enableBatchProcessing && cloudKitOperation.current.moreComing
        }
        super.willFinishOperation(operation)
}
```

I placed a `break point` and found the willFinishOperation was not called. Further digging shows that BatchedCloudKitOperation is defined in the library, but doesn't seem to be part of any **subclassing** nor does it seem to be **used** anywhere. So I'm guessing this may be the issue?

**Comment by leotumwattana** [comment]
Just wanted to give a quick update. 

I'm currently handling the more is coming flag manually by wrapping the CloudKitOperation<CKFetchRecordChangesOperation> in a group operation and using the group operation to generate additional CloudKitOperation<CKFetchRecordChangesOperation> based on the moreComing flag. 

For those running into this issue, this serves as an easy workaround until the issue is fixed.

**Comment by danthorpe** [comment]
@leotumwattana - sorry, not had a chance to look into this yet - but that is essentially what `BatchedCloudKitOperation` does (except that it subclasses `RepeatedOperation` instead of `GroupOperation`).

**Comment by leotumwattana** [comment]
@danthorpe - Sorry for late reply as well. Been a bit crazy at work these past few days. Yup. This is not a high priority issue as there are easy workarounds. As mentioned before, I think somewhere along the updates, `CloudKitOperations` are now no longer subclassed from `BatchedCloudKitOperation`. I'll try to look at it, but it will likely have to be during the next weekend.

**Comment by danthorpe** [comment]
@leotumwattana - can you share your code where you are using `BatchedCloudKitOperation`. I'm just trying to figure out what the issue is really.

The unit tests which test it begins [here](https://github.com/danthorpe/Operations/blob/development/Tests/Features/CloudKitOperationTests.swift#L2258).

So, lets say you want to execute a `CKFetchNotificationChangesOperation`, you would do it like this:

```swift
let operation = BatchedCloudKitOperation { CKFetchNotificationChangesOperation() }
```
and then `BatchedCloudKitOperation` will:
1. wrap up the CKFetchNotificationChangesOperation in a `CloudKitOperation`
2. automatically repeat `CloudKitOperation<CKFetchNotificationChangesOperation>` in the event of `moreComing` being true. 

So, at the moment, not really clear on what your expectations are/were?

**Comment by leotumwattana** [comment]
@danthorpe - Sure thing. Actually my code is basically what you have above.
```
let operation = BatchCloudKitOperation { CKFetchCKFetchRecordChangesOperation() }
```
However, when I run the operation, I found that it **did not** continue to download more records automatically. So what I ended up doing is to detect the `moreComing` flag manually and regenerating a new `BatchCloudKitOperation` to handle it manually.

### What I don't understand

It seems `CloudKitOperation` subclasses from `RetryOperation` as oppose to `BatchedCloudKitOperation`? Is this by design? If so, where does `BatchedCloudKitOperation` come into play?
```
public final class CloudKitOperation<T where T: NSOperation, T: CKOperationType, T: AssociatedErrorType, T.Error: CloudKitErrorType>: RetryOperation<OPRCKOperation<T>> {
```

**Comment by danthorpe** [comment]
Hmm, I'm assuming you mean `CKFetchRecordChangesOperation`?  Can you turn on verbose logging to shed some light on what is happening:

You can put this in your AppDelegate's startup, and it will print out the life-cycle of all `Operation` instances.
```swift
LogManager.severity = .Verbose
```

As for how `BatchCloudKitOperation` comes into play - it subclasses `RepeatedOperation` and composes `CloudKitOperation` (which subclasses `RetryOperation`). So, essentially its job is to repeat instances of `CloudKitOperation`.

**Comment by leotumwattana** [comment]
Sure thing. This is the verbose log from my sample application. What I did is create **500** records and push them up to CloudKit. Then try to fetch them. As you can see towards the end of the log. The fetch operation only manages to get one batch and then `finishes with no errors`, but the `moreComing` flag is `true`.

### Verbose log
```
ZoneSetupOperation: Initialized -> Pending
ZoneSetupOperation: Pending -> Executing
CreateRecordOperation: Initialized -> Pending
ZoneSetupOperation: Will Execute
CKFetchRecordChangesOperation: Initialized -> Pending
CreateZoneOperation: Initialized -> Pending
CreateZoneOperation: Pending -> Executing
CreateZoneOperation: Will Execute
OPRCKOperation<CKModifyRecordZonesOperation>: Initialized -> Pending
OPRCKOperation<CKModifyRecordZonesOperation>: Pending -> Executing
OPRCKOperation<CKModifyRecordZonesOperation>: Will Execute
Zone Setup Operation: Optional([<CKRecordZone: 0x7fa63bd2c5f0; zoneID=CustomPrivateZone:__defaultOwner__, capabilities=(Atomic,Sync)>]) Optional([])
OPRCKOperation<CKModifyRecordZonesOperation>: Executing -> Finishing
OPRCKOperation<CKModifyRecordZonesOperation>: Will finish with no errors.
OPRCKOperation<CKModifyRecordZonesOperation>: Finishing -> Finished
OPRCKOperation<CKModifyRecordZonesOperation>: Did finish with errors: []
CreateZoneOperation: Executing -> Finishing
CreateZoneOperation: Will finish with no errors.
CreateZoneOperation: Finishing -> Finished
CreateZoneOperation: Did finish with errors: []
ZoneSetupOperation: Executing -> Finishing
ZoneSetupOperation: Will finish with no errors.
ZoneSetupOperation: Finishing -> Finished
ZoneSetupOperation: Did finish with errors: []
CreateRecordOperation: Pending -> Executing
CreateRecordOperation: Will Execute
CreateRecordCloudKitOperation: Initialized -> Pending
CreateRecordCloudKitOperation: Pending -> Executing
CreateRecordCloudKitOperation: Will Execute
OPRCKOperation<CKModifyRecordsOperation>: Initialized -> Pending
OPRCKOperation<CKModifyRecordsOperation>: Pending -> Executing
OPRCKOperation<CKModifyRecordsOperation>: Will Execute
OPRCKOperation<CKModifyRecordsOperation>: Executing -> Finishing
OPRCKOperation<CKModifyRecordsOperation>: Will finish with 1 errors.
CreateRecordCloudKitOperation: Received CloudKit Limit Exceeded error: ModifyRecordsError<CKRecord, CKRecordID>(underlyingError: <CKError 0x7fa63bdbb5a0: "Limit Exceeded" (27/1020); "Your request contains 500 items which is more than the maximum number of items in a single request (400)">, saved: Optional([]), deleted: Optional([]))
CloudKitOperation<CKModifyRecordsOperation>: Initialized -> Pending
CloudKitOperation<CKModifyRecordsOperation>: Pending -> Executing
CreateRecordCloudKitOperation: will add next operation: <_TtGC10Operations14OPRCKOperationCSo24CKModifyRecordsOperation_: 0x7fa63be00130>{name = 'OPRCKOperation<CKModifyRecordsOperation>'}
CloudKitOperation<CKModifyRecordsOperation>: Will Execute
CreateRecordCloudKitOperation: did replace configure block.
OPRCKOperation<CKModifyRecordsOperation>: Initialized -> Pending
OPRCKOperation<CKModifyRecordsOperation>: Pending -> Executing
OPRCKOperation<CKModifyRecordsOperation>: Will Execute
Delay for 0.273893074988946 seconds: Initialized -> Pending
OPRCKOperation<CKModifyRecordsOperation>: Initialized -> Pending
Delay for 0.273893074988946 seconds: Pending -> Executing
Delay for 0.273893074988946 seconds: Will Execute
CreateRecordCloudKitOperation: will attempt 2 recovery from errors: [Operations.ModifyRecordsError<CKRecord, CKRecordID>(underlyingError: <CKError 0x7fa63bdbb5a0: "Limit Exceeded" (27/1020); "Your request contains 500 items which is more than the maximum number of items in a single request (400)">, saved: Optional([]), deleted: Optional([]))] in operation: <_TtGC10Operations14OPRCKOperationCSo24CKModifyRecordsOperation_: 0x7fa63bdaef10>{name = 'OPRCKOperation<CKModifyRecordsOperation>'}
OPRCKOperation<CKModifyRecordsOperation>: Finishing -> Finished
OPRCKOperation<CKModifyRecordsOperation>: Did finish with no errors
Delay for 0.273893074988946 seconds: Executing -> Finishing
Delay for 0.273893074988946 seconds: Will finish with no errors.
Delay for 0.273893074988946 seconds: Finishing -> Finished
Delay for 0.273893074988946 seconds: Did finish with errors: []
OPRCKOperation<CKModifyRecordsOperation>: Executing -> Finishing
OPRCKOperation<CKModifyRecordsOperation>: Will finish with no errors.
OPRCKOperation<CKModifyRecordsOperation>: Finishing -> Finished
OPRCKOperation<CKModifyRecordsOperation>: Did finish with errors: []
CloudKitOperation<CKModifyRecordsOperation>: Executing -> Finishing
CloudKitOperation<CKModifyRecordsOperation>: Will finish with no errors.
CloudKitOperation<CKModifyRecordsOperation>: Finishing -> Finished
CloudKitOperation<CKModifyRecordsOperation>: Did finish with errors: []
OPRCKOperation<CKModifyRecordsOperation>: Pending -> Executing
OPRCKOperation<CKModifyRecordsOperation>: Will Execute
OPRCKOperation<CKModifyRecordsOperation>: Executing -> Finishing
OPRCKOperation<CKModifyRecordsOperation>: Will finish with no errors.
CreateRecordCloudKitOperation: successfully recovered from errors in <_TtGC10Operations14OPRCKOperationCSo24CKModifyRecordsOperation_: 0x7fa63bdaef10>{name = 'OPRCKOperation<CKModifyRecordsOperation>'}
OPRCKOperation<CKModifyRecordsOperation>: Finishing -> Finished
OPRCKOperation<CKModifyRecordsOperation>: Did finish with errors: []
CreateRecordCloudKitOperation: Executing -> Finishing
CreateRecordCloudKitOperation: Will finish with no errors.
CreateRecordCloudKitOperation: Finishing -> Finished
CreateRecordCloudKitOperation: Did finish with errors: []
CreateRecordOperation: Executing -> Finishing
CreateRecordOperation: Will finish with no errors.
CreateRecordOperation: Finishing -> Finished
CreateRecordOperation: Did finish with errors: []
CKFetchRecordChangesOperation: Pending -> Executing
CKFetchRecordChangesOperation: Will Execute
CloudKitOperation<CKFetchRecordChangesOperation>: Initialized -> Pending
CloudKitOperation<CKFetchRecordChangesOperation>: Pending -> Executing
CloudKitOperation<CKFetchRecordChangesOperation>: Will Execute
OPRCKOperation<CKFetchRecordChangesOperation>: Initialized -> Pending
OPRCKOperation<CKFetchRecordChangesOperation>: Pending -> Executing
OPRCKOperation<CKFetchRecordChangesOperation>: Will Execute
ServerCT: Optional(<CKServerChangeToken: 0x7fa63bc35aa0; data=AQAAAAAAAADKf/////////+xdqQhv+FCa7uejyX4/tSP>) ClientCT: nil
More records coming: true
OPRCKOperation<CKFetchRecordChangesOperation>: Executing -> Finishing
OPRCKOperation<CKFetchRecordChangesOperation>: Will finish with no errors.
OPRCKOperation<CKFetchRecordChangesOperation>: Finishing -> Finished
OPRCKOperation<CKFetchRecordChangesOperation>: Did finish with errors: []
CloudKitOperation<CKFetchRecordChangesOperation>: Executing -> Finishing
CloudKitOperation<CKFetchRecordChangesOperation>: Will finish with no errors.
CloudKitOperation<CKFetchRecordChangesOperation>: Finishing -> Finished
CloudKitOperation<CKFetchRecordChangesOperation>: Did finish with errors: []
CKFetchRecordChangesOperation: Executing -> Finishing
CKFetchRecordChangesOperation: Will finish with no errors.
CKFetchRecordChangesOperation: Finishing -> Finished
CKFetchRecordChangesOperation: Did finish with errors: []
```

**Comment by danthorpe** [comment]
Hmm, interesting... This is your [sample project](https://github.com/leotumwattana/OperationCloudKit) yes?

**Comment by leotumwattana** [comment]
Yup. That's correct. I just pushed the changes that will reproduce the issue above. 😉

**Comment by swiftlyfalling** [comment]
@leotumwattana:

Your `FetchChangesOperation` uses:
```swift
let op = CloudKitOperation { CKFetchRecordChangesOperation() }
```

This will create a `CloudKitOperation`, which does **not** automatically handle the moreComing flag.

`BatchedCloudKitOperation` must be deliberately specified in lieu of `CloudKitOperation` to opt-in to the automatic "moreComing" batching support. Specifically:

```diff
-let op = CloudKitOperation { CKFetchRecordChangesOperation() }
+let op = BatchedCloudKitOperation { CKFetchRecordChangesOperation() }
```

Some general notes on BatchedCloudKitOperation:

Currently, BatchedCloudKitOperation calls the completion block for every underlying CloudKitOperation it executes. i.e. the FetchRecordChangesCompletionBlock may be called more than once. 

For now, if you want to know when the BatchedCloudKitOperation itself is complete, you will probably need to add a Will/DidFinishObserver.

**Comment by leotumwattana** [comment]
Ah ic. So my bad. Didn't know about that distinction. But why separate the
two?

**Comment by danthorpe** [comment]
@swiftlyfalling - thanks for the clarification.

@leotumwattana - the two are separated because the API requirements for "batch processing" has been isolated into a protocol which is a constraint on the `CKOperation` returned by the generator. In other words, it is compile time safe vs run-time check to see if the operation `respondsToSelector: #selector(moreComing)`. Additionally, the "repeated" nature of `CloudKitOperation` is all about retrying in the event of failure, contracts to that of `BatchCloudKitOperation` which is all about performing another batch.

I agree that they're functionally very similar, and from a framework consumer's point of view, would be much easier to not have to make the distinction. However - the retry logic for `CloudKitOperation` is (unfortunately) already quite complex and I didn't want to throw batching in there too. Additionally, I don't think it is necessarily bad that the framework consumer has to explicitly opt-in to batching, rather than it being magic.

Will consider the trade-offs here again though.

**Comment by leotumwattana** [comment]
@danthorpe Understood. Thanks for the explanation. Guess I just didn't read
the doc / code comments clearly enough. So my bad. 😉

**Comment by danthorpe** [comment]
@leotumwattana - no worries! There is obviously a documentation issue 😔.

**Comment by leotumwattana** [comment]
Just noticed I've left this open when it should be closed. So closing this as a clean up. 😉
