### ISSUE TITLE
Update the documentation on https://operations.readme.io

### ISSUE THREAD

**Issue by blg-andreasbraun** [ProcedureKit/ProcedureKit#371]
The current version there ist 2.5.0. I think we need to update it to 3.0.0 :)

**Comment by danthorpe** [comment]
Hi @blg-andreasbraun - thanks! It's on my list. I'm slowly moving all the guides over to the Wiki on GitHub.

**Comment by nickmshelley** [comment]
I'd suggest just taking the link to the guide out of the Readme now that the overhaul is officially released and that guide is really out of date.

**Comment by danthorpe** [comment]
Thanks @nickmshelley - will do.
