### ISSUE TITLE
LoggingObserverTests rare crash

### ISSUE THREAD

**Issue by swiftlyfalling** [ProcedureKit/ProcedureKit#393]
Reproduced a crash in test__logger_outputs_cancellation(). Specifically, the line:

``` swift
self.receivedMessages.append(message)
```

in `LoggingObserverTests.configureOperation.LoggingObserver`.

Only happened once. Did not have a chance to dig into it, but it had a similar appearance to prior thread-safety issues that have been resolved.

My guess is that it's because access to `LoggingObserverTests.receivedMessages` is not thread-safe.

LoggingObserver seems to be deprecated, but I figured it was worth noting.

**Comment by danthorpe** [comment]
Thanks @swiftlyfalling - this is a bit annoying.

I think that some early adopters (@jshier ?) are still using `LoggingObserver` in their production code - so, it's deprecated, but still hanging around for the time being. It wont make the transition to v4.0 though.

**Comment by swiftlyfalling** [comment]
Hit a spurious test failure caused by another LoggingObserverTest while checking PR #454.

**Comment by danthorpe** [comment]
Gonna close this - as it's increasingly less relevant.
