### ISSUE TITLE
OperationQueue addOperation() hangs

### ISSUE THREAD

**Issue by fgulan** [ProcedureKit/ProcedureKit#407]
I've subclassed Operation class for my own simple operation (API request) and sometimes when adding that operation to OperationQueue it hangs on addOperation() for few seconds. I'm currently iterating thorough objects, for each object create operation and add it to operation queue via addOperation() method.

**Comment by danthorpe** [comment]
Hi @fgulan - can you share a bit more information, such as code, or explanation of the dependency graph or any conditions?

The `addOperation` method in the queue is a little bit involved, but most of it is just about adding some dependencies for conditions and dealing with mutual exclusive conditions. So, would be good to try to vary the scenario to remove any conditions and see if you still have issues. That will help narrow down what is going on.

You could also fire up the Time Profiler to see what is happening?

**Comment by swiftlyfalling** [comment]
If you have a lot (and I mean a **lot**) of conditions, this could cause a slightly delay in adding operations to an OperationQueue. But, at least in all of my tests, this requires an absurdly large number of conditions.

**Comment by danthorpe** [comment]
Gonna close this, @fgulan if you are still having issues, please re-open. :)
