### ISSUE TITLE
difference between addOperation and produceOperation

### ISSUE THREAD

**Issue by vamsiac** [ProcedureKit/ProcedureKit#408]
Hi Dan,

Was working on issue where i gather set of operations asynchronously and add them to the current group operation. adding them making the group operation to stick there in executing state. where as producing an operation is running the child operations.

1. Are there any catches that we should not add child operations once parent's execution starts.
2. when an operation is produced from the group operation will they add as child ops to the group op?

Sorry tried to look at GroupOperation class and get my head around the problem but cannot get answers to these two questions.
```
class UploadOperation: GroupOperation {
    override func execute() {
        guard !cancelled else { return }
        
        let uploadOperations = self.allUploadOperations() { allUploadOps in

//this won't work and current operation is executing forever
        addOperations(uploadMachineOperations)

//this works
           uploadMachineOperations.map {produceOperation($0)}

 }
}

```

**Comment by vamsiac** [comment]
ignore ignore. my fault. wasn't calling super.execute.

**Comment by danthorpe** [comment]
@vamsiac - no worries.

In general though - the behaviour of `produceOperation` is to add a operation to the queue on which the receiver is running. So, in terms of `GroupOperation` if you call `self.produceOperation(newOperation)` it will add the operation to the queue that the _group_ is on. 

Whereas `self.addChildOperation(newOperation)` adds it to the group's internal private queue.
