### ISSUE TITLE
[Question] RetryOperation paramters

### ISSUE THREAD

**Issue by woodydaniel** [ProcedureKit/ProcedureKit#414]
I'm really confused about the retryOperation retry block parameter. Is there an example someone could give me or point me to. My current usage of the retryOperation doesn't require the retry block handler - what would I pass through in this case. Would also be great to know what to pass through if I did want to utilise the retry handler.

Thanks

**Comment by danthorpe** [comment]
Hi @woodydaniel - sure, I can help.

The retry block is not technically optional, however it can be given a default value of "pass through" like this: `= { $1 }` - not terribly obvious I know.

There are not yet any example of `RetryOperation` in usage beyond `CloudKitOperation`. But, if you read the [docs in the source](https://github.com/ProcedureKit/ProcedureKit/blob/development/Sources/Core/Shared/RetryOperation.swift#L140) you can see how it can be initialised. Note that there are a number of different ways to initialise `RetryOperation` and `RepeatedOperation` all of which are subclass-able.

So, I suggest you subclass it to provide your own initialisation API.

The retry block can be used to do a few things

1. Custom logging or reporting of failures
2. Adjusting how the "suggested" retry operation is configured
3. Return nil to stop attempting retry and instead finish with an error

If you do not want to do either 1, or 2, then you can pass through the "suggested" retry payload (includes the `next()` instance from the operation generator, and an optional `Delay`). So, the retry block function has this signature:

```swift
public typealias Handler = (RetryFailureInfo<T>, Payload) -> Payload?
``` 

which means, just return the 2nd argument to "pass through": `= { $1 }`.

But what is this `Delay` all about - well, the generators which are used to construct `RetryOperation` are a delay generator and the operation generator. The delay generator can be used to optionally add delays between retries. This is handy for exponential back-off, random delays etc. There is built in support for creating these. See `WaitStrategy`.

Lastly, there is the concept of _does this retry forever?_ - which can be solved in a number of ways.

1. The operation generator (i.e. the generator which creates new `NSOperation` instances) can return nil - this means no more retries.
2. The retry block can return nil
3. The `maxCount` argument can be provided - this is the maximum number of retry attempts to make before finishing with errors.

**Comment by woodydaniel** [comment]
@danthorpe thanks for the quick response and detailed explanation. 
Unfortunately I'm still fairly new at Swift dev and am struggling a bit with one or two things mentioned, specifically - still getting the retry parameter correct. If you wouldn;t mind seeing below and commenting, hopefully I'll get it right after this:

Currently I have a class `PostAttachmentOperation` of type `Operation` which uploads an attachment. 
For my RetryOperation I have this:
`RetryOperation(maxCount: 3, strategy: WaitStrategy.Fixed(3), postAttachmentOperation, retry: { (RetryFailureInfo<NSOperation>, RepeatedPayload<NSOperation>) -> RepeatedPayload<NSOperation>? in
                            //retrun something here
                        })`

I understand what you said about passing the second argument - the retry payload - through, I'm just stuck putting that into code.

I saw in the `RetyOoperation` class you gave this example:
`  let operation = RetryOperation(
         maxCount: 3,
         strategy: .Random((0.1, 1.0)),
         generator: MyOperationGenerator()
     ) { info, delay, op in
         // inspect failure info
         return (delay, op)
     }
`
I tried to reconcile that example with mine but with no success.
Apologies again if I'm not seeing something really obvious, your exaplnaiton above was really succinct and well explained.

**Comment by danthorpe** [comment]
Yep, okay, so in the header docs - there is a mistake, the `delay, op` is not a single argument (a tuple). So you need to do this:

```swift
RetryOperation(maxCount: 3, strategy: .Fixed(3), postAttachmentOperation, retry: { $1 })
```

Except... that your `postAttachmentOperation` looks as though it *is* an operation, not a _generator of operations_. `NSOperation` is a "one shot" class, you cannot retry it as it. Instead we use a `GeneratorType` to create a new instance when we want to do a retry.

Therefore you need to do something like this:

```swift
let retry = RetryOperation(maxCount: 3, strategy: .Fixed(3), AnyGenerator { PostAttachmentOperation() }, retry: { $1 })
```

But obviously you might want to configure the `PostAttachmentOperation` - so you could either have a function of this type: `() -> PostAttachmentOperation?` which you can pass directly into `AnyGenerator`. Or you do the configuration afterwards using the mechanics of `RetryOperation` and `RepeatedOperation`

```swift
retry.addConfigureBlock { postAttachmentOperation in
    postAttachmentOperation.post = thePost
   // etc
}
```

This block gets run on every new operation which is retried.

**Comment by woodydaniel** [comment]
Thanks @danthorpe, this makes a huge amount of sense. I'm going to look in to the `AnyGenreator` struct as i'm not familiar with it but overall your last explanation was awesome! 
Thank you

**Comment by danthorpe** [comment]
Hi, @woodydaniel I'm going to close this ticket now - feel free to to re-open it or a create a new issue if you have any follow up question. 😀

**Comment by woodydaniel** [comment]
Sure @danthorpe thanks for all the help!
