### ISSUE TITLE
ConditionOperation executed before operation set

### ISSUE THREAD

**Issue by pomozoff** [ProcedureKit/ProcedureKit#415]
I have large project using this framework.
Last day I've found a crash that leads to assertion in the Operations framework.
Here is the verbose operations log:

> Fetch own Id: Adding to queue
> Fetch own Id: Initialized -> Pending
> No Failed Dependencies: Will finish with 1 errors.
> Fetch contact info for the own Id: Adding to queue
> Fetch contact info for the own Id: Initialized -> Pending
> Fetch own Id Evaluate Conditions: Will finish with 1 errors.
> Fetch own Id: Did cancel with errors: [Operations.NoFailedDependenciesCondition.Error.FailedDependencies].
> Fetch contact info for the own Id: Did cancel.
> Fetch contact info for the own Id: Pending -> Finishing
> Fetch own Id: Did cancel.
> Fetch contact info for the own Id: Will finish with no errors.
> Fetch own Id: Pending -> Finishing
> Fetch own Id: Will finish with 1 errors.
> Fetch contact info for the own Id: Finishing -> Finished
> Fetch contact info for the own Id: Did finish with no errors
> Fetch contact info for the own Id: Did cancel with errors: [Operations.AutomaticInjectionError.DependencyFinishedWithErrors([Operations.NoFailedDependenciesCondition.Error.FailedDependencies])].
> Fetch own Id: Finishing -> Finished
> Fetch own Id: Did finish with errors: [Operations.NoFailedDependenciesCondition.Error.FailedDependencies]
> fatal error: ConditionOperation executed before operation set.: file /Users/user/Documents/Develop/project/Carthage/Checkouts/Operations/Sources/Core/Shared/Condition.swift, line 106

In short - there are three operations.
First one opens a data source and it should fail.
The next two are both depend on it and they should not to be executed in this scenario.
I use `addCondition( NoFailedDependenciesCondition() )` to reach this behavior.

I can't understand why this assertion is fired.
There is a `nil` in the `operation` field of the condition, but why it is there?

Any suggestions are appreciated.

P.S. Unfortunately I can't reproduce this issue as a test case.

**Comment by danthorpe** [comment]
Hi @pomozoff - will have a look into this, looks like your operation has a dependency which has failed though right?

**Comment by pomozoff** [comment]
First operation is failed as expected.
Second one is depend on first and it was cancelled well.
But the third operation which is depend on both - first and second operations (I can't leave only one dependency on the second operation right now to check this scenario) tries to execute condition before start - `NoFailedDependenciesCondition()` and this condition has no operation set and crashes on the assertion.

**Comment by danthorpe** [comment]
@pomozoff arr, okay - will look into it in a bit more detail.

**Comment by swiftlyfalling** [comment]
@pomozoff: I reproduced this issue with a small test case, and a fix is pending in PR #420.
