### ISSUE TITLE
Access to deinited object

### ISSUE THREAD

**Issue by pomozoff** [ProcedureKit/ProcedureKit#416]
Here is a [screenshot](https://yadi.sk/i/inf9gH9fuSZ9B) of the crash.
**Self** is already destroyed but it marked as **unowned** in the block and code crashes trying to access **self** in the line #545.

Should the **self** will be marked as **weak**?

**Comment by danthorpe** [comment]
Yeah, it can be weak - the evaluator is owned by the operation, so, `unowned` should be okay - but there may be some odd async edge cases on de-init I suppose. You are probably correct that `weak` and then unwrapping is safer.

I will fix this in the `swift/2.2` branch.

**Comment by pomozoff** [comment]
Thanks.
