### ISSUE TITLE
URLSessionOperation completion handler executes before Task is finished.

### ISSUE THREAD

**Issue by S0MMS** [ProcedureKit/ProcedureKit#418]
There seems to be an issue with URLSessionOperation.  If the NSURLSessionTask that the URLSessionOperation is initialized with has a completion handler **AND** the URLSessionOperation itself has a completion handler, the completion handler for the URLSessionOperation can execute **BEFORE** the task completion handler.  The following code produces the issue...

    func testURLSessionTaskOperation() {
        let url = NSURL(string: "https://www.google.com")
        let request = NSURLRequest(URL: url!)
        
        let task : NSURLSessionTask = NSURLSession.sharedSession().dataTaskWithRequest(request, completionHandler: {(data: NSData?, response: NSURLResponse?, error: NSError?) in
            for i in 0..<100000 {
                var foo:String = "foo \(i)"
                foo = foo.stringByAppendingString(foo)
            }
            print("Task done")
        })
        
        let sessionTaskOperation = URLSessionTaskOperation.init(task: task);
        sessionTaskOperation.completionBlock = {
            print("Operation done")
        }
        
        let queue = OperationQueue()
        queue.addOperations(sessionTaskOperation);
        
        sleep(10)
    }

Running this test will yield output of... 
'Operation done' 
'Task done'

The expected result should be (in my opinion)...
'Task done'
'Operation done'

**Comment by danthorpe** [comment]
Thanks @S0MMS - will look into this.

Unfortunately, the `completionBlock` is `NSOperation` is very unreliable - especially when it comes to deterministic behaviour.

Can you retry your test using a `DidFinishObserver` instead:

```swift
let sessionTaskOperation = URLSessionTaskOperation.init(task: task);
sessionTaskOperation.addObserver(DidFinishObserver { op, errors in
    print("Operation done")
})
```

Thanks!

**Comment by S0MMS** [comment]
Dan,

Thanks for getting back - I hear you on the completionBlock being unreliable.  I changed my test to the following...

    func testURLSessionTaskOperation() {
        let url = NSURL(string: "https://www.google.com")
        let request = NSURLRequest(URL: url!)
        
        let task : NSURLSessionTask = NSURLSession.sharedSession().dataTaskWithRequest(request, completionHandler: {(data: NSData?, response: NSURLResponse?, error: NSError?) in
            // do some stuff
            for i in 0..<100000 {
                var foo:String = "foo \(i)"
                foo = foo.stringByAppendingString(foo)
            }
            print("Task done")
        })
        
        let sessionTaskOperation = URLSessionTaskOperation.init(task: task);
        sessionTaskOperation.addObserver(DidFinishObserver { op, errors in
            print("Operation done")
        })
        
        let queue = OperationQueue()
        queue.addOperations(sessionTaskOperation);
        
        sleep(10)
    }

And it still results in 'Operation done' executing before 'Task done'.

**Comment by danthorpe** [comment]
Great - thanks @S0MMS.

**Comment by pritesh-eb** [comment]
This looks like a bug in `NSURLSessionDataTask`. Switching to `NSURLDownloadTask` will work as expected. Check this for more details: http://www.oliverfoggin.com/advanced-nsoperations-nsurlsessiondatatask-vs-nsurlsessiondownloadtask/

**Comment by S0MMS** [comment]
Pritesh,

Thanks for the heads up.  That's exactly the behavior we are seeing.  Unfortunately, NSURLSessionDownloadTask may not be an option for us for a couple of reasons: 1-we are POSTing data to our server, 2-we then need access to the response data (JSON), the response and any errors that occurred (like the DataTask callback). 3-we then need to run some code after all this stuff happens.  I suppose a class could be constructed that utilizes the download task delegate methods and provides a mimicry of all this, but man - it would be great if NSURLSessionDataTask just worked the way it was supposed to!

**Comment by pritesh-eb** [comment]
> but man - it would be great if NSURLSessionDataTask just worked the way it was supposed to!
👍 

I haven't used `ProcedureKit` myself, but a few general comments:

1. `NSURLSessionDownloadTask` can be used for `POST` requests
2. You can get the JSON pretty easily using https://developer.apple.com/library/mac/documentation/Foundation/Reference/NSURLSession_class/#//apple_ref/occ/instm/NSURLSession/downloadTaskWithRequest:completionHandler:
```
func downloadTaskWithRequest(_ request: NSURLRequest,
           completionHandler completionHandler: (NSURL?,
                                      NSURLResponse?,
                                      NSError?) -> Void) -> NSURLSessionDownloadTask
```

You may need a `delegate` for other reasons (handling redirection etc), but at least `NSURLSessionDownloadTask` can do whatever you described in your comment.

**Comment by danthorpe** [comment]
@pritesh-eb @S0MMS not had a chance to look into this yet - will look at the links. In theory, it would be pretty simple to extract the API that `URLSessionTaskOperation` uses into a protocol, and then framework consumers can specify either `NSURLSessionDownloadTask` or `NSURLSessionDataTask`...

**Comment by pritesh-eb** [comment]
@danthorpe A brief look suggests that `URLSessionTaskOperation` _should_ already work with `NSURLSessionDownloadTask`: https://github.com/ProcedureKit/ProcedureKit/blob/ecf45018e8e10cbd20b14493b929189cd8b3dd83/Sources/Features/Shared/URLSessionTaskOperation.swift#L31

```
public init(task: NSURLSessionTask) {
    //
}
```

I hope that helps!

**Comment by automactic** [comment]
@S0MMS Could it because `DidFinishObserver` and dataTask's `completionHandler` was called in different threads? As I remember, `DidFinishObserver` is called in the operation queue's thread, `completionHandler` should be called in a thread related to `NSURLSession`. So the order they are called couldn't be guaranteed.

**Comment by danthorpe** [comment]
@pritesh-eb oh right - yes, we compose it, and just observe the state changes.

**Comment by danthorpe** [comment]
@swiftlyfalling - what do you think to this?

**Comment by S0MMS** [comment]
@automactic - I haven't yet tried to solve the issue by insuring both the Task and Operation completion handler are using the same thread.  I may look into this later today.  Thanks.

**Comment by S0MMS** [comment]
Just wanted to let everyone know that Pritesh's suggestion works great (thanks Pritesh!) The NSURLSessionDownloadTask certainly completes before the URLSessionTaskOperation does.

Although I'd prefer that NSURLSessionDataTask just work and while there is some philosophical dissonance concerning the retrieval of the data through a temporary file, at the end of the day I get paid to make stuff work - not philosophize.  

Thanks again.

**Comment by danthorpe** [comment]
I think, given that `URLSessionTaskOperation` is probably the mostly often questioned and contentious class in this project, we will look at improving it regardless as @swiftlyfalling is proposing in #426.

**Comment by S0MMS** [comment]
danthorpe - I saw swiftlyfalling's proprosal - looks good and is similar in vein to a workaround we came up with...invoking operation.finish() only after invoking the tasks completion handler..

Keep up the good work.
