### ISSUE TITLE
The file reference for "OpenInSafariOperationTests.swift" is a member of multiple groups

### ISSUE THREAD

**Issue by pomozoff** [ProcedureKit/ProcedureKit#432]
Compiling a branch "swift/2.2" with Carthage I received following warnings:

> *** Building scheme "iOS Operations" in Operations.xcodeproj
> 2016-08-29 06:44:56.802 xcodebuild[4079:113369] warning:  The file reference for "OpenInSafariOperationTests.swift" is a member of multiple groups ("Features" and "Features"); this indicates a malformed project.  Only the membership in one of the groups will be preserved (but membership in targets will be unaffected).  If you want a reference to the same file in more than one group, please add another reference to the same path.
> 2016-08-29 06:46:18.184 xcodebuild[4287:121264] warning:  The file reference for "OpenInSafariOperationTests.swift" is a member of multiple groups ("Features" and "Features"); this indicates a malformed project.  Only the membership in one of the groups will be preserved (but membership in targets will be unaffected).  If you want a reference to the same file in more than one group, please add another reference to the same path.

**Comment by danthorpe** [comment]
Yeah, I've seen this too - I don't think it's a huge issue, but will have a look into it.
