### ISSUE TITLE
Release configuration leaks "swift/2.2"

### ISSUE THREAD

**Issue by pomozoff** [ProcedureKit/ProcedureKit#433]
Branch is "swift/2.2" 32868f0
I've tried to find a reason and have built a Debug configuration, but there are no leaks.
It's very similar to [this](https://github.com/DaveWoodCom/XCGLogger/issues/137) leak.

![2016-08-29_10-57-04](https://cloud.githubusercontent.com/assets/839094/18044634/e0b4fed6-6ddf-11e6-8662-91440925c27e.png)
![2016-08-29_10-57-10](https://cloud.githubusercontent.com/assets/839094/18044633/e0b32c5a-6ddf-11e6-9e7e-ccbfc8807b3f.png)
![2016-08-29_10-57-16](https://cloud.githubusercontent.com/assets/839094/18044635/e0c00db2-6ddf-11e6-9541-c07e65e7ed46.png)
![2016-08-29_10-57-21](https://cloud.githubusercontent.com/assets/839094/18044638/e0e257fa-6ddf-11e6-9903-ffb003e8fa92.png)
![2016-08-29_10-57-27](https://cloud.githubusercontent.com/assets/839094/18044639/e0ee687e-6ddf-11e6-95a0-8491d942d4f1.png)
![2016-08-29_10-57-32](https://cloud.githubusercontent.com/assets/839094/18044640/e0f22f04-6ddf-11e6-8c01-f354cd45ad2f.png)
![2016-08-29_10-57-38](https://cloud.githubusercontent.com/assets/839094/18044641/e0ff0c9c-6ddf-11e6-932b-5052b142bbe4.png)
![2016-08-29_10-59-41](https://cloud.githubusercontent.com/assets/839094/18044694/2347ed26-6de0-11e6-8d2f-9f746a0471ff.png)
![2016-08-29_11-00-20](https://cloud.githubusercontent.com/assets/839094/18044707/383cb82e-6de0-11e6-87f6-b7809f276f11.png)

**Comment by danthorpe** [comment]
Hmm, will investigate! Thanks @pomozoff for raising this!

**Comment by danthorpe** [comment]
@pomozoff - can you describe the structure of your operations where you're seeing this? I'm guessing you have some mutually exclusive conditions? Any other details you can share will help me replicate the bug. 😀

**Comment by swiftlyfalling** [comment]
@pomozoff: According to the issue for that other leak, it sounds like the Swift 2.2 release library has some edge case leaks that are triggered by String interpolation (and fixed in Swift 3).

> So I spent a tonne of time digging into the memory leaks. The leaks are actually in the Swift core library and our code just happened to trigger them. As you probably noticed, judging by the PR, the leak is triggered in some cases using string interpolation, so changing affected code from: "[\(owner.identifier)] " to "[" + owner.identifier + "] " avoids the leak.

> Worth noting the leaks appear to be fixed in Swift 3.

Source: [comment](https://github.com/DaveWoodCom/XCGLogger/issues/137#issuecomment-241268975)

Please try branch `swift/2_2/OPR-433_string_leaks_workaround`, which has some fixes for this. It should reduce the leaking that you are seeing.

**Comment by pomozoff** [comment]
Sorry, I'm very short of time, I'll test it tomorrow.

**Comment by danthorpe** [comment]
@pomozoff this got merged into 3.2.0, so if you update, you will hopefully see that your crashes have ceased, however, there may be other string interpolation going on causing some leaks...

**Comment by pomozoff** [comment]
Thanks.
