### ISSUE TITLE
Replace some test-case uses of addCompletionBlock with DidFinishObserver

### ISSUE THREAD

**Issue by swiftlyfalling** [ProcedureKit/ProcedureKit#436]
Unless explicitly testing completion blocks, we really ought to be using DidFinishObservers instead of completion blocks in tests.

> NOTE: `addCompletionBlockToTestOperation` internally uses a DidFinishObserver, so there is no need to replace use of that function.

In BasicTests.swift:
- [ ] `test__delay_operation_completes_after_interval`
- [ ] `test__operation_with_long_running_dependency_cancels_and_finishes_without_...`

In GroupOperationTests.swift:
- [ ] `test__group_operations_are_performed_in_order`
- [ ] `test__adding_operation_to_running_group`
- [ ] `test__group_operation__does_not_finish_before_child_operations_have_finished`
- [ ] `test__group_operation__does_not_finish_before_child_groupoperations_are_finished`
- [ ] `test__group_operation_does_not_finish_before_child_produced_operations_are_finished`
- [ ] `test__group_operation_cancellation__queue_is_empty_when_finished`
- [ ] `test__group_operation_operations_array_receives_operations_produced_by_children`
- [ ] `test__group_operation_ignores_queue_delegate_calls_from_other_queues`

In NetworkObserverTests.swift:
- [ ] `test__network_indicator_hides_after_short_delay_when_operation_ends`

In StressTests.swift:

- [ ] `test__group_operation_cancel_and_add_operation`
- [ ] `test__repeated_operation_cancel`
- [ ] `test__group_operation__does_not_finish_before_child_operations_are_finished`

**Comment by danthorpe** [comment]
I think we can probable close this now as it's gonna be redundant. :)
