### ISSUE TITLE
Make operation observer protocols accessible via Objective-C

### ISSUE THREAD

**Issue by danthorpe** [ProcedureKit/ProcedureKit#441]

**Comment by danthorpe** [comment]
Actually - not going to do this - Making the protocols `@objc` will then mean that the structs cannot be used as observers - they must be classes.

So, for this to work, the block based observers would need to be classes, or some kind of type-erased class which composes the structs. Which at the moment, is not realistic given work currently underway for _ProcedureKit_ and Swift 3.0.

**Comment by ryanjm** [comment]
Alright. Full steam ahead with Swift. 👍

**Comment by danthorpe** [comment]
Yeah, sorry about that @ryanjm - should have done an experiment first.

**Comment by ryanjm** [comment]
No problem. That's the way it goes.
