### ISSUE TITLE
Crash: ProcedureKit Swift/2.3 - Xcode 8 GM - iOS 9 - EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by leotumwattana** [ProcedureKit/ProcedureKit#461]
Has anyone noticed an issue with **ProcedureKit (Branch: Swift/2.3)** crashing with the following when built with **Xcode 8 GM onto iOS 9** devices and simulator? 🙅 

![fullsizerender 3](https://cloud.githubusercontent.com/assets/544211/18407777/2816f452-774d-11e6-9823-9194e2c6b440.jpg)

Everything seems to work out fine when building to **iOS 10** devices and simulator. 👌 

Any help will be greatly appreciated. Thanks!

**Comment by danthorpe** [comment]
@ProcedureKit/core - anyone got any ideas? I'm currently disconnected in Berlin..

**Comment by harryworld** [comment]
A sample project running Xcode 8 GM can be found [here](https://github.com/harryworld/TestOperations)

**Comment by swiftlyfalling** [comment]
Am looking into this now. (iOS 9.3 Simulator download keeps timing out, though.)

**Comment by swiftlyfalling** [comment]
@leotumwattana, @harryworld, @danthorpe: PR #462 should fix this issue.

**Comment by leotumwattana** [comment]
@swiftlyfalling

Perfect. Your PR resolved the issue. :thumbsup:

Closing.
