### ISSUE TITLE
4.0 beta-1 Assertion while adding an operatin to the queue 

### ISSUE THREAD

**Issue by DanielMandea** [ProcedureKit/ProcedureKit#481]
I the previous releases 3.x this worked:

```
import ProcedureKit

class DownloadFeedProcedure: Procedure {

    override init() {
        super.init()
    }

    // MARK: - Override 

    override func execute() {
        print("Hello world")
        finish()
    }
}

class UpdateFeedGroupPorcedure: GroupProcedure {

    // MARK: - Private

    private let downloadProcedure:DownloadFeedProcedure

    // MARK: - Init 

    init(underlyingQueue: DispatchQueue? = nil) {
        downloadProcedure = DownloadFeedProcedure()
        super.init(underlyingQueue: underlyingQueue, operations: [downloadProcedure])
    }

}

let queue = OperationQueue()
let groupOp = UpdateFeedGroupPorcedure()
queue.addOperation(groupOp)

```

Now i receive the following assert while adding the procedure to the queue 
"assertion failed: Attempting to perform illegal cyclic state transition"
screen shot 2016-09-20 at 5 38 15 pm

Is this a known issue or, I'm doing something ##wrong?
I also tested this with a simple operation and I have the same result.

**Comment by danthorpe** [comment]
Hi @DanielMandea,

To confirm - are you using an OperationQueue or a ProcedureQueue?

**Comment by swiftlyfalling** [comment]
@DanielMandea: Also, it looks like your screen shot did not attach/link properly. There should have been additional details in the assertion - could you please post them?

**Comment by DanielMandea** [comment]
@danthorpe the problem was that i used OperationQueue instead of ProcedureQueue. Thanks for your reply. 
Will close this issue
