### ISSUE TITLE
Attempting to perform illegal cyclic state transition, initialized -> executing

### ISSUE THREAD

**Issue by XBeg9** [ProcedureKit/ProcedureKit#490]
I am trying to use ProcedureKit 4.0.0-beta-1 and getting such assert. Any way to fix?

**Comment by danthorpe** [comment]
Are you adding the procedure to an `OperationQueue` or a `ProcedureQueue`?

**Comment by XBeg9** [comment]
@danthorpe oh! didn't know that :) thanks!

**Comment by danthorpe** [comment]
@XBeg9 - yep, stuff still in beta at the moment, docs & guides are coming.
