### ISSUE TITLE
Argument list too long: recursive header expansion failed

### ISSUE THREAD

**Issue by brandonskane** [ProcedureKit/ProcedureKit#494]
Getting a "Check dependencies" error in Xcode 8 for release/4.0.0-beta-2.

`Argument list too long: recursive header expansion failed at .../Carthage/Checkouts/ProcedureKit/Carthage/Build/iOS/ProcedureKitMobile.framework.dSYM/Contents.`

<img width="875" alt="genesisapp_xcodeproj" src="https://cloud.githubusercontent.com/assets/375155/19017948/359cc1d8-881e-11e6-807c-ad77c170b236.png">

**Comment by danthorpe** [comment]
Hi @brandonskane - sorry - should have been clearer, there are schemes for Mobile, Mac etc - but nothing in them.

Only ProcedureKit works at the moment. See #398 for details.

**Comment by danthorpe** [comment]
Hi @brandonskane - `ProcedureKitMobile` is now available in beta 3. Gonna close this for now - please comment if you have any other issues 😀
