### ISSUE TITLE
[Question]: Different deployment targets for CocoaPods and Carthage in v4.0.0

### ISSUE THREAD

**Issue by fromcelticpark** [ProcedureKit/ProcedureKit#501]
First, I'd like to say thank you for maintaining and actively contributing to ProcedureKit. It's really cool how you adopted and developed the idea that was proposed back in that wwdc session on operations :)

Ok, now to the question. Our team is in the process of migrating our application and its dependencies to swift 3. And we came across the issue that with ProcedureKit v4.0.0 its iOS deployment target was upped from iOS 8 to iOS 9 and now its higher than deployment target of our application. 
Digging into the recent changes of ProcedureKit showed that deployment targets for all platforms stated in [xcconfig file](https://github.com/ProcedureKit/ProcedureKit/blob/4.0.0-beta-2/Supporting%20Files/ProcedureKit.xcconfig#L38) (which is used for Carthage) are different from  that from the [podspec file](https://github.com/ProcedureKit/ProcedureKit/blob/4.0.0-beta-2/ProcedureKit.podspec#L18).

<img width="326" alt="screenshot 2016-10-10 14 04 51" src="https://cloud.githubusercontent.com/assets/2337202/19234252/0b85870a-8ef3-11e6-8dc5-a3ce80300bbb.png"> <img width="300" alt="screenshot 2016-10-10 14 04 58" src="https://cloud.githubusercontent.com/assets/2337202/19234253/0b86877c-8ef3-11e6-97df-a7dbd3e7d409.png">

So I wanted to know whether the bumping of deployment targets in xcconfig file was an intentional change or not. And if it wasn't, I would be happy to open a pull request to change the values back to the settings that are specified in podspec file.

**Comment by danthorpe** [comment]
Hi @fromcelticpark - thanks so much!

Oh, this is a mistake/oversight in the xcconfig file. I am not planning on bumping to iOS 9, although tvOS will be 9.

I'm guess from this that you want to use Carthage? I will fix this for Beta 3 - but I'm not sure exactly when that will get created - hopefully this week sometime. In the meantime, if you are working on a feature branch to refactor, you could just change your deployment target, or create a fork and make the changes yourself?

For Beta 3, I will have cross platform binaries for `ProcedureKit`, `TestingProcedureKit` and `ProcedureKitMobile` and `ProcedureKitLocation`.

**Comment by fromcelticpark** [comment]
@danthorpe great! Thanks for a fast reply.

Yeah, custom fork is my way to go setup for now. Will switch to "Beta 3" when it comes out :thumbsup:. Thanks!
