### ISSUE TITLE
Contribution needed? 

### ISSUE THREAD

**Issue by martnst** [ProcedureKit/ProcedureKit#505]
Hi @danthorpe, 

your ProcedureKit seems to be a more active project than [PSOperations](https://github.com/pluralsight/PSOperations). However, I noticed it's kinda in the middle morphing from `Operations` to `ProcedureKit`. At least from the documentations point of view. 
I also noticed it does not quite follow the new naming approach of Swift 3 yet. 

As I am using `ProcedureKit` in an tvOS app but also `PSOperations` in another App on iOS and macOS. I like to move the other apps to Procedure as it's the more active project. Starting to migrate my operations I noticed issues here and there which made me wonder if you could need any help moving forward rather than just complaining :).

**Comment by danthorpe** [comment]
Hi @martnst - yeah, certainly in a bit of a transition phase, and thankfully there has been loads of contributions so far.

Biggest contribution you can make to start with would be to create a [New Issue](https://github.com/ProcedureKit/ProcedureKit/issues/new) for each thing you see which seems not quite right. Especially Swift 3 naming style errors and the like. 😀

**Comment by martnst** [comment]
Okay, will do my best. May I also ask critical question on design of the code?

**Comment by danthorpe** [comment]
Yeah, sure, I'll try not to be too offended!
