### ISSUE TITLE
Understanding Condition

### ISSUE THREAD

**Issue by martnst** [ProcedureKit/ProcedureKit#506]
Here is my feedback on Conditions: 

- `func attach(condition: Condition)`: 
  - It took me some time to find this method. Expected it to be named `add` as well. I don't see any advantage in naming it `attach`. 
  - The parameter should be unnamed, as `operation.attach(condition: MyCondition())` seems no nice Swift 3 naming to me. 
- Requiring Conditions to be Procures seems a bit over-engineered to me. Looking at the implementation of evaluating the conditions I see an advantage, however implementing a condition suffers from this design. 
- even-though it's just an internal method i think `evaluateConditions` is not a good name as it does not actually evaluate a Procudures condition, but creates an operation for doing this, which then needs to be executed to perform the actual evaluation. 
- `internal enum ConditionEvaluation` is actually duplicating `public enum ConditionResult` with the exception of the `failed` case
  - How about a custom error that holds an array of underlying errors instead? 
- What is the purpose of `TrueCondition` and `FalseCondition`?
- `WrappingConditon` might be better name of `ComposedCondition`
- `IgnoredCondition` is also named slightly misleading as it only ignores failures but not the entire condition, which leads to canceling operations without the error included in condition`s the `.failed` state. I don't have any better name other than `WeakCondition` in mind though.

**Comment by danthorpe** [comment]
Hi @martnst - thanks for the feedback.

* Yeah, I'm not sure about `attach(condition:)` either. 
    * Originally, I wrote this as `add(condition:)` along with `add(observer:)` and `add(dependency:)`. I would say this is the most likely API to change, actually just waiting for some Yay/Nay feedback on it.
    * Actually, not convinced that it should be unnamed, especially if it is named back to `add` - I think having lines code which adds dependencies, observers and conditions would be less readable. For example, it all depends on the framework consumer, consider:

        ```swift
        procedure.add(foo)
        procedure.add(bar)
        procedure.add(baz)
        ```
        vs
        ```swift
        procedure.add(condition: foo)
        procedure.add(observer: bar)
        procedure.add(dependency: baz)
        ```

* On Conditions being Procedures - see the back story: https://github.com/procedurekit/procedurekit/issues/175 - Looking at PSOperations, I would say that this bug still exists in their framework due to the way the operation's state is managed. We've totally overhauled it in a fantastic contribution from the community around this project as part of _Operations_ v3. 

    Having said that, I can see how it might look a little over-engineered, with the `EvaluatingConditions` group procedure. Can certainly discuss any proposals you have here. What are the issues with implementing conditions? I kinda see that it's actually easier to implement conditions, as they're just `Procedure`s. I was even thinking of making it so that it was just a Procedure with a readable `ConditionResult` property.

* Yeah, can look into this - the naming here is pretty much just taken from the v2 work, where there was the concept (actually it was a state of the `Operation`) called "evaluating conditions".

* Yeah, again - fair point, when I initially wrote the evaluator, conditions only had a `.satisfied` and `.failed` state. Then I added `.ignored` (for `IgnoredCondition`) and later `.pending`. So, it probably could do with some refactoring.

**Comment by martnst** [comment]
As of #507 I think `func add(_ condition: ConditionProtocol)` would be the best way.

**Comment by danthorpe** [comment]
Are you suggesting that `Condition` be refactored back to being a protocol, which is composed inside a specific `Foundation.Operation` subclass for evaluation purposes inside `Procedure`?

**Comment by martnst** [comment]
I am not sure about that. I had the idea of defining a minimal protocol and internally wrapping into a `Procedure`. Then it kinda would be best of both, the power of Procedures on evaluation and an easy protocol that can be implanted by a struct as PSOperations does.

**Comment by danthorpe** [comment]
Yeah, I [had this API](https://github.com/ProcedureKit/ProcedureKit/blob/release/3.4.0/Sources/Core/Shared/Operation.swift#L256) as an intermediate for _Operations_ v3. 

But for all the conditions defined in the framework, I refactored them into `Condition` classes. And this always just seemed like a temporary thing. So, I can certainly appreciate if you are thinking about porting some code from _PSOperations_ over to _ProcedureKit_ - having this API would make it easier.

From my point of view - it's less code to test and maintain, and I didn't really think that there was much of a problem with subclassing `Condition` for custom ones.

Can you provide an example where a type which conforms to a protocol is easier/better vs a `Condition` subclass? Or is it mostly about a migratory aid?

**Comment by martnst** [comment]
I just started implementing some missing conditions of PSOperations. E.g. 

```swift
class ReachablityCondition : Condition {
    public let host: URL
    
    init(host: URL) {
        self.mutuallyExclusive = false
        self.host = host
    }
    
    override func evaluate(procedure: Procedure, completion: @escaping (ConditionResult) -> Void) {
        ReachabilityController.requestReachability(host) { (reachable) in
            if reachable {
                completion(.satisfied)
            }
            else {
                let error = ProcedureKitError.conditionFailed()
                completion(.failed(error))
            }
        }
    }
}
```

**Comment by martnst** [comment]
I'll think about it.

**Comment by danthorpe** [comment]
Yeah, something like that.

However - just FYI, before you go all out on reachability stuff - I think we should discuss it a little bit. Because, this is actually an anti-pattern which Apple have talked about a lot in network sessions. Fundamentally you should not "check" that the client is connected before making a request - instead in the event of a timeout/network error, the client should then observe reachability to retry the request when it goes backonline.

_ProcedureKit_ has a very capable `RetryProcedure`....

**Comment by martnst** [comment]
okay, I'll revise flow. There might be better ways.

**Comment by danthorpe** [comment]
Yeah, I mean, we have these classes already:

- [ReachabilityCondition](https://github.com/ProcedureKit/ProcedureKit/blob/release/3.4.0/Sources/Features/Shared/ReachabilityCondition.swift) 
- [ReachableOperation](https://github.com/ProcedureKit/ProcedureKit/blob/release/3.4.0/Sources/Features/Shared/ReachableOperation.swift)

but neither are really what I would call best practice. Suggest you create a new issue to discuss Reachability.

**Comment by martnst** [comment]
Okay, did not see those as I only checked the development branch. Will create new issues as needed.

**Comment by danthorpe** [comment]
Yeah, you might find it informative to checkout the `release/3.4.0` branch which is the last Swift 2.3 _Operations_ v3 branch - i.e. "feature complete".

**Comment by danthorpe** [comment]
Hi - I renamed `attach(condition: Condition)` to `add(condition: Condition)` in #521.
