### ISSUE TITLE
Recommended workaround for GroupOperation willFinishOperation...

### ISSUE THREAD

**Issue by StephenDaedalus** [ProcedureKit/ProcedureKit#514]
I had been relying on GroupOperation's `willFinishOperation` being called even when there were errors in child operations. I liked how I could monitor every child operation and dynamically call `addOperation` as I progressed through my state machine - at least this was my particular use-case for the class.

I'm not sure when or if the behavior changed but I believe it may have in one of the more recent revisions. 

What is the best reason for *not* having willFinishOperation called even if errors is not empty in the code below and is the proper work-around to just override `willAttemptRecoveryFromErrors`?

```
public func operationQueue(queue: OperationQueue, willFinishOperation operation: NSOperation, withErrors errors: [ErrorType]) {
        guard queue === self.queue else { return }
        if !errors.isEmpty {
            if willAttemptRecoveryFromErrors(errors, inOperation: operation) {
                child(operation, didAttemptRecoveryFromErrors: errors)
            }
            else {
                child(operation, didEncounterFatalErrors: errors)
            }
        }
        else if operation !== finishingOperation {
            willFinishOperation(operation)
        }
    }
```

**Comment by danthorpe** [comment]
Hi @StephenDaedalus - I think this change happened ~ v3.1 or v3.2 and the goal is mostly to allow `GroupOperation` to be able to recover from errors. Previously, if there was a child which failed, the error would be collected, and even if the subclass, re-added a new operation which "fixed" the error, there was no way to essentially remove the error from the previous failure.

To remedy this, `GroupOperation` (and `GroupProcedure`) has some APIs which can be overridden to indicate to the group that the failing child will be re-tried. This can be done in `willAttemptRecoveryFromErrors(_, inOperation: Operation) -> Bool`.

If you don't want to handle any errors, no need to override it. If you do want to handle errors, then framework consumers must explicitly indicate how they are going to handle errors.

I think this actually makes subclasses much more readable and testable - as the happy path is all just in `willFinishOperation()` and the unhappy path is clear.

In terms of how to implement an override to handle errors.

1. Check what the failing operation is
2. Check what the error is.
3. If it is recoverable by doing something differently, use `addOperation` to add additional operations to the group - and then return true.
4. If the error is not recoverable - return false.

This is basically how `RetryOperation` works, and see `CloudKitOperation` for hints about how to write a `RetryOperation` subclass.

**Comment by StephenDaedalus** [comment]
Dan, apologies for the delayed response. After looking more closely at the code I can see that this is definitely the better approach. I suggest that adding a few of the sentences from your notes above to the documentation will help clarify things just a bit more.
