### ISSUE TITLE
How about making QueueDelegate methods optional?

### ISSUE THREAD

**Issue by martnst** [ProcedureKit/ProcedureKit#530]
Currently added a delegate to a `ProcedureOperationQueue` is of a hassle. I added this extensions to my implementing Swift file: 

```swift
extension OperationQueueDelegate {
    public func operationQueue(_ queue: OperationQueue, willAddOperation operation: Operation) { }
    public func operationQueue(_ queue: OperationQueue, willFinishOperation operation: Operation) { }
    public func operationQueue(_ queue: OperationQueue, didFinishOperation operation: Operation) { }
}

extension ProcedureQueueDelegate {
    public func procedureQueue(_ queue: ProcedureQueue, willAddOperation operation: Operation) { }
    public func procedureQueue(_ queue: ProcedureQueue, willFinishOperation operation: Operation, withErrors errors: [Error]) { }
    public func procedureQueue(_ queue: ProcedureQueue, didFinishOperation operation: Operation, withErrors errors: [Error]) { }
    public func procedureQueue(_ queue: ProcedureQueue, willProduceOperation operation: Operation) { }
}
```

*Also I wondering what `: class` means a a protocol definition like [here](https://github.com/ProcedureKit/ProcedureKit/blob/development/Sources/ProcedureQueue.swift#L7)?*

**Comment by danthorpe** [comment]
Hi @martnst - yeah, can do. 

Just wondering though, as I'd have thought creating `ProcedureQueue` subclasses would not be very common - can I ask why you are having to implement this?

The `: class` so that you cannot implement this protocol with a type which does not support weak referencing, such as a value type. This is how that is done in Swift.

**Comment by martnst** [comment]
Hey @danthorpe, 

sorry for being ambiguous here. By *implementing Swift file* I am referring to a controller / manager class. I am not subclassing `ProcedureOperationQueue`

Thanks for the explainer on `: class`. Nice move 🙂

**Comment by danthorpe** [comment]
I see, so you have controller/manager, which owns a `queue` and you want the controller to be the delegate. Okay, I see.

**Comment by martnst** [comment]
Okay looks like I am behind #516 from 6 days ago.

**Comment by danthorpe** [comment]
Yeah - #510 and #511.

**Comment by martnst** [comment]
sorry i mixed the threads. your answer belongs to #529  😀

**Comment by martnst** [comment]
Wow that was quick 👍

**Comment by martnst** [comment]
I am wondering though, why did you leave `didFinishOperation` as non-optional?
