### ISSUE TITLE
ExclusivityManager synchronization bug

### ISSUE THREAD

**Issue by myexec** [ProcedureKit/ProcedureKit#543]
I'm using the framework in my project and noticed a bug in the ExclusivityManager class (or may I be wrong). The queues returned from the DispatchQueue+ProcedureKit extension are all concurrent, in particular DispatchQueue.initiated returns concurrent queue. Therefore 'add' and 'remove' functions are not synchronized. I tested this adding 2 mutually exclusive operations at once. The result was they were not mutually exclusive. I fixed this like so:

```swift
func add(procedure: Procedure, category: String) -> Operation? {
        return lock.withCriticalScope{
            _add(procedure: procedure, category: category)
        }
    }

    func remove(procedure: Procedure, category: String) {
        lock.withCriticalScope{
            _remove(procedure: procedure, category: category)
        }
    }
```

Awesome framework btw 👍

**Comment by danthorpe** [comment]
Hi @myexec  - yep that is definitely a bug! Great catch! Will fix asap.
