### ISSUE TITLE
Compiling failed with Xcode 8.1 GM seed

### ISSUE THREAD

**Issue by pomozoff** [ProcedureKit/ProcedureKit#548]
I've downloaded Xcode Version 8.1 (8T61a) GM seed and try to build a ProcedureKit 4.0.0 Beta 3 with Carthage and it fails with error:

> duplicate symbol __TMRbBp in:
>     /Users/apomozov/Library/Developer/Xcode/DerivedData/ProcedureKit-erdkskxxwyhdaoanlnvglvwxlmle/Build/Intermediates/ProcedureKit.build/Release-iphoneos/ProcedureKit.build/Objects-normal/arm64/Condition.o
>     /Users/apomozov/Library/Developer/Xcode/DerivedData/ProcedureKit-erdkskxxwyhdaoanlnvglvwxlmle/Build/Intermediates/ProcedureKit.build/Release-iphoneos/ProcedureKit.build/Objects-normal/arm64/ProcedureQueue.o
> ld: 1 duplicate symbol for architecture arm64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by danthorpe** [comment]
Thanks @pomozoff - will try to look into this asap, as I need to tag Beta 4.

**Comment by wfilleman** [comment]
pomozoff,

I'm using ProcedureKit 4.0.0 Beta 3, but I'm seeing the duplicate symbol __TMRbBp error in another part of my code base. Specifically a TodayView extension on three custom swift files I've written. None of which use or import ProcedureKit.

XCode 8.0 builds without issues, but the 8.1 GM and final 8.1 both have this issue. I'm stumped and opened up a discussion on the Apple Developer forum for hopefully some insight: https://forums.developer.apple.com/message/191894#191894

If you've been able to work through this, please let me know.

Wes

**Comment by danthorpe** [comment]
@wfilleman thanks for the info.

**Comment by danthorpe** [comment]
Has anyone tried building `development` from source with Xcode 8.1 final yet?

**Comment by jshier** [comment]
I build with the GM through CocoaPods every day.

**Comment by danthorpe** [comment]
@jshier on `development`?

**Comment by jshier** [comment]
Yes, 
```ruby
pod 'ProcedureKit', git: "https://github.com/ProcedureKit/ProcedureKit", branch: "development"
  pod 'ProcedureKit/Location', git: "https://github.com/ProcedureKit/ProcedureKit", branch: "development"
```

**Comment by danthorpe** [comment]
@wfilleman @pomozoff - not sure how you're integrating _ProcedureKit_ but perhaps it might be worth trying to move from beta 3 to `development`?

Although, there is a breaking change around ResultInjection APIs.

**Comment by wfilleman** [comment]
Thanks @danthorpe,

I was already building the 4.0.0-beta-3 tag. Just now switched over to the 'development' branch and same issue. But, to be clear, I don't think it's an issue with ProcedureKit since I saw this on the Xcode 8.1 GM earlier this week before I added ProcedureKit.

Seems like there's something in common with @pomozoff and my builds that I'm stumped on that's causing the same dup symbol error.

Wes

**Comment by danthorpe** [comment]
Very weird. I guess, worth just seeing if you've got any matching dependencies, other than _ProcedureKit_ including system frameworks. I have no idea what `__TMRbBp` is from.

**Comment by wfilleman** [comment]
Thanks @danthorpe, it's quite odd.

**Comment by danthorpe** [comment]
Okay... so, just finally managed to install Xcode 8.1 GM (I know the final is out, but I don't like using the AppStore builds - I currently have 4 Xcode apps installed).

But I'm getting this when doing a release build:

> duplicate symbol __TMRbBp in:
>     /Users/daniel/Library/Developer/Xcode/DerivedData/ProcedureKit-dnykyvtglbgxhrgjsrqujqiprltx/Build/Intermediates/ProcedureKit.build/Release/ProcedureKit.build/Objects-normal/x86_64/Condition.o
>     /Users/daniel/Library/Developer/Xcode/DerivedData/ProcedureKit-dnykyvtglbgxhrgjsrqujqiprltx/Build/Intermediates/ProcedureKit.build/Release/ProcedureKit.build/Objects-normal/x86_64/ProcedureQueue.o
> ld: 1 duplicate symbol for architecture x86_64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)

Will, investigate more tomorrow. Need to go to sleep now - next thing to do will be to search http://bugs.swift.org.

**Comment by wfilleman** [comment]
@danthorpe,

Ah, interesting. Looks like we're all hit with the __TMRbBp symbol bug. Thanks for the follow-up and let me know what you find out or anything you'd like me to try. For now, keeping XCode 8.0 around to get work done.

**Comment by jshier** [comment]
Ah, I just realized our optimized builds are still using Xcode 8.0. Testing an optimized build under 8.1 results in the same failure you're seeing. Building debug works fine.

**Comment by jshier** [comment]
Building `ProcedureKit` without optimization succeeds, I'm just not 100% sure about the stability of an app where not all of the frameworks have the same optimization levels (we've seen issues with that reported for Alamfire).

**Comment by pomozoff** [comment]
Hi guys.
I'm investigating this issue and my results are - looks like it's a swift 3 compiler bug that creates similar section in two different binaries **Condition.o** and **ProcedureQueue.o**:

> (__TEXT,__swift3_builtin) private external [no dead strip] __TMRbBp

As I realised this section has been created by compiler if you're using function overrides.
I've made a pull request with a simple workaround for this project, but this bug needs to be promoted to Swift developers as a critical one.

**Comment by danthorpe** [comment]
Hi @pomozoff - thanks for this. Great find, I hadn't figured out that it was related to function overrides. I'm in the process of opening up a bug on Swift JIRA - so will get this sorted, and fixed for Beta 4 this weekend.

**Comment by pomozoff** [comment]
Thanks

**Comment by JamieWhite** [comment]
That was a great find. How did you figure that out? just look for function similarities in the two classes?

**Comment by pomozoff** [comment]
Just commenting code in these classes and trying to create rerelease build :)
Then a couple of minutes was spent to realise what wrong with this line **ops.forEach()**.
In the second file I finished with commenting 80th line **evaluate(procedure: procedure, completion: finish)** where an overridden function leads to the same section in a result binary.
But I've no time to dive deeper.

**Comment by keith** [comment]
For reference here's the issue about this https://bugs.swift.org/browse/SR-3081
