### ISSUE TITLE
MutuallyExclusive with arbitrary category

### ISSUE THREAD

**Issue by pronebird** [ProcedureKit/ProcedureKit#580]
Is it possible to use MutuallyExclusive condition to group operations based on arbitrary category?

I see that MutuallyExclusive simply uses class name, but would that be possible to have a condition for sub-type of operation, i.e MyClass.Action1, MyClass.Action2?

I can imagine that I can achieve the same with observers and simply chain procedures, but thought that MutuallyExclusive should have similar function implemented already.

**Comment by danthorpe** [comment]
Hi @pronebird. At the moment, this is not possible, as the `category` property is only defined in an internal extension on `ConditionProtocol`.

However, I think, this could be changed to support arbitrary category groupings. In such a scenario, you could then just attach a `TrueCondition` or `BlockCondition` with a custom category.

**Comment by pronebird** [comment]
Hi @danthorpe,

Thanks for suggestion. Looking at TrueCondition's code, if I get it right, I can simply provide arbitrary name and set mutuallyExclusive = true, then it should work the same way as mutual exclusivity right?

**Comment by pronebird** [comment]
Am I right to think that this should work?

```swift
let exclusiveCondition = TrueCondition(name: "MutuallyExclusive<\(self)>.washingMachine1.doLaundry", mutuallyExclusive: true)

let operation = FetchExchangeRateProcedure()
operation.add(condition: exclusiveCondition)
        
operationQueue.addOperation(operation)
```

I am not sure whether it makes the condition mutually exclusive or entire operation..

**Comment by pronebird** [comment]
Ugh, I just skimmed through the code and what you said makes sense. ConditionProtocol defines category but it's internal.

**Comment by danthorpe** [comment]
Yeah, so the name argument of `TrueCondition` is just the name of the underlying `Operation`, not the category - but this is what I'm suggesting will be changed.
