### ISSUE TITLE
HTTPRequirement construction error

### ISSUE THREAD

**Issue by yageek** [ProcedureKit/ProcedureKit#585]
I'm on the `development` on the road to `beta-4`
As discussed in stack, initializing an `HTTPRequirement` struct leads to a compilation error.

By compiling the following file: https://gist.github.com/yageek/dd491dec6428fd95f495ddc5fa242926

I have the following compilation error:

 `[…]/SONSerializationProcedure.swift:46:54: Cannot convert value of type 'Data' to expected argument type '_?'`

**Comment by danthorpe** [comment]
Fixed by #585
