### ISSUE TITLE
Missing equality comparisons in Errors.swift for ProcedureKitError.Context?

### ISSUE THREAD

**Issue by swiftlyfalling** [ProcedureKit/ProcedureKit#589]
Some of the Context enum cases are not currently handled explicitly in
`public static func == (lhs: Context, rhs: Context) -> Bool`

**Comment by danthorpe** [comment]
I haven't yet figured out exactly what to change - but before v4 is final, there needs to be a bit of an overhaul/refactor of `ProcedureKitError`.
