### ISSUE TITLE
Simplify the unwrapping of `PendingValue` in `ResultInjection`

### ISSUE THREAD

**Issue by yageek** [ProcedureKit/ProcedureKit#590]
The new refactor of the injection behaviour introduced 
a new protocol based on `PendingValue` for `requirement` and 
`result`.  

It is convenient to hide a complexity of a task behind a `GroupOperation`.

Let's imagine the following task:

```swift
public class DownloadProcedure<T: JSONObject>: GroupProcedure, ResultInjection {

    public var requirement: PendingValue<APICall>
    public var result: PendingValue<ResourceValue<T>> = .pending

    public init(call: APICall, tokenProvider: TokenProvider) {
        requirement = .ready(call)

        let serializedURLProcedure = SerializeAPICallProcedure(call: call, provider: tokenProvider)
        let downloadProcedure = NetworkDownloadProcedure(session: URLSession.shared)
        let unserializeProcedure = JSONDeserializationProcedure<T>()

        downloadProcedure.injectResult(from: serializedURLProcedure)
        unserializeProcedure.injectResult(from: downloadProcedure)

            super.init(operations: [serializedURLProcedure, downloadProcedure, unserializeProcedure])
        }
}
```

If I want to expose this behaviour for external developers, I would like to hide all the elements related
to `ProcedureKit` and only provide some simple asynchronous functions.

```swift
  public func downloadStuff(page: UInt, completion: @escaping (SomeCompletionType) -> Void) {
 }
```

At the end, I would like to know if the call has succeeded or failed.
If it has failed, I would like to have access to the error information.
If not, I would like to have the result of the operation.

So for each function I will write, I will need to unwrap the element contained in 
the `PendingValue` enum.

Writing something like:

```swift
  public func getNews(page: UInt, completion: @escaping (SomeCompletionType>) -> Void) {

        let downloadProcedure = DownloadProcedure<ParsedNews>(call: MediaServerAPI.News.getNews(page: page), tokenProvider: self.tokenProvider)

        downloadProcedure.addDidFinishBlockObserver { (procedure, errors) in
            if errors.first != nil {
                /* Deal with error */
            } else if case let .ready(object) = procedure.result {
                /* Deal with success */
            }
        }
        /* ... */
    }

```
May be it would make sense to provide a way to automatically perform this unwrapping.

But this may imply to have a conventional type for `SomeCompletionType`.

One proposition could be to use, as in Rust, the [Result](https://github.com/antitypical/Result) enum type and imagine to have something like:

```swift
  public func getNews(page: UInt, completion: @escaping (Result<[ParsedNews], MediaServerAPIError>) -> Void) {
        let downloadProcedure = DownloadProcedure<ParsedNews>(call: MediaServerAPI.News.getNews(page: page), tokenProvider: self.tokenProvider).unwrap(completion: completion)
            /* ... */
    }
```

**Comment by danthorpe** [comment]
Hi @yageek. Totally get where you're coming from here. Some interesting ideas certainly.

My preference would certainly be that `PendingValue<T>` shares much of the behaviour that `Result<T>` has. i.e.

```swift
enum PendingValue<T> {
    case void
    case pending
    case success(T)
    case failure(Error)
}
```

But I also absolutely want to keep _ProcedureKit_ free of any dependencies. Now potentially we could make a new repo _ProcecureKit+Result_ which provides some convenience adaptors for using _ProcedureKit_ with _Result_ and get this sort of behaviour.

For example, it could provide a completion block API to `ResultInjection` which exposes a `Result<T,Error>` to the block, and internally deals with the boiler plate stuff. Something like this:

```swift
import ProcedureKit
import Result

public extension ProcedureProtocol where Self: ResultInjection {
    func addCompletionResult(_ block: (Result<Self.Result, Error>) -> Void) -> Self {
          addDidFinishBlockObserver { procedure, errors in 
               // etc
          }
    }
}
```

**Comment by yageek** [comment]
I completely agree for the dependencies, I just add a link for explaining the idea. 

I like the `addDidFinishCompletionResult` idea.

**Comment by danthorpe** [comment]
Okay, will flesh out the ideas a bit.

Also, something I've hinted at here, is exposing `cancel(withError:)` as a separate protocol. Because while it makes sense to hide _ProcedureKit_ details inside an API, you will still want the ability to cancel asynchronous tasks.

**Comment by danthorpe** [comment]
Having said all of that - it might make sense to make `PendingValue` something like `PendingResult` and include the ability have errors.

**Comment by danthorpe** [comment]
@yageek I've done a bit of work to get the core code proposition closer to what we've been discussing here. Not a full blown `Result<T,E>` type - but an improvement I think. Would appreciate your thoughts on PR #601.

**Comment by yageek** [comment]
I tested a little bit the work and the branch and I have a question related to the failure case. 
In case of a `Procedure` conforming to the `OutputProcedure` protocol, setting `output` to `.failure(_)` is enough ? Do I still need to call `finish(withError: _)` afterwards?

**Comment by danthorpe** [comment]
@yageek there is a `defer` statement:

```swift
defer { strongSelf.finish(withError: strongSelf.output.error) }
```

**Comment by danthorpe** [comment]
There is now a `finish(withResult:)` API to enable automatic setting of the output, and correct finishing behaviour at the same time.

Gonna close this issue - although I agree that potentially there is more to be done here to make `ProcedureResult` a bit easier to use.
