### ISSUE TITLE
Data race in BackgroundObserver

### ISSUE THREAD

**Issue by leotumwattana** [ProcedureKit/ProcedureKit#610]
FYI, I just came across a *data race* on **BackgroundObserver** for `private var identifier: UIBackgroundTaskIdentifier?`

Don't know which kind of locks you guys use. I've been using `pthread_mutex_t`. Let me know and I can help with some of these race conditions.

**Comment by danthorpe** [comment]
@leotumwattana well, @swiftlyfalling has been fixing them all with regular `NSLock` or `NSRecursiveLock` - I'll let him take point on this one.

**Comment by leotumwattana** [comment]
@danthorpe sure thing. @swiftlyfalling, let me know if I can help in any way. Cheers!

**Comment by swiftlyfalling** [comment]
@leotumwattana: Just keep reporting any issues that Thread Sanitizer finds! 😁

**Comment by swiftlyfalling** [comment]
@leotumwattana: This should be fixed by #614, which has now been merged into `development`.

**Comment by leotumwattana** [comment]
Great and thanks @swiftlyfalling.
