### ISSUE TITLE
Inheritance chain of AsyncBlockProcedure

### ISSUE THREAD

**Issue by leotumwattana** [ProcedureKit/ProcedureKit#617]
@danthorpe: Was just looking through some of the code in more detail and thought the *inheritance chain* of `AsyncBlockProcedure` a little strange.

Why have `AsyncBlockProcedure` inherit from `AsyncResultProcedure` and not the other way around? Shouldn't the inheritance chain build up and not down?

Ignore me if there is something I'm missing. ;)

**Comment by danthorpe** [comment]
Well, `AsyncBlockProcedure` is just a specialism of `AsyncResultProcedure` where the `Output` is `Void`. Hence, it's a subclass class which defines the `Output`.

You could also where `AsyncResultProcedure` is a subclass of `AsyncBlockProcedure` - but this was round will end up with more duplicated code.

**Comment by leotumwattana** [comment]
Okay. Fair enough. Was curious. Learn something new every day. 😉

**Comment by leotumwattana** [comment]
Question answered. Let's close this. ;)
