### ISSUE TITLE
Setup task with ProcedureKit

### ISSUE THREAD

**Issue by marwey** [ProcedureKit/ProcedureKit#628]
I was wondering if it is possible to write a setup task which coordinates multiple async calls with ProcedureKit?

The scenario is like this: imagine an app running multiple (cloud / web-) service calls. Like e.g. for a set-up task which is getting various bits of configuration information from a server during launch time. This could involve hitting several endpoints. You want to call a single method to kick this process off, and have a completion block run when it has finished. The services don’t depend on each other. 

Plain iOS / macOS options to solve this:

- start each service from the completion block of the previous one, and when the last one is done, call your overall completion block. BAD approach ;-) 

- use a GCD dispatch group and wrap the service calls with 'dispatch_group_enter()' and 'dispatch_group_leave()'. This works very well, but is kind of 'low level'. 

I was wondering if this problem could also be solved using ProcedureKit?

**Comment by leotumwattana** [comment]
Let me see if I can help with this one. 

1. Create individual Procedures for each of your setup tasks.
2. Wrap those Procedures up into a GroupProcedure.

Since a GroupProcedure finishes when all it's child procedures are finished, then all you have to do is add a *DidFinishObserver* to the GroupProcedure to run some code upon completion of all your setup.

**Comment by marwey** [comment]
Yeah, that approach is reflecting what was my first thought as well. Unfortunately it doesn't quite solve the issue ;-) 

Let me explain a bit more about the nature of an individual setup task. If you e.g. call an iCloud operation it is an async call by itself. You start the operation and it immediately returns. Sometime later the completion block is executed with the result set or an error. 

So, if you just wrap such an operation in a procedure the call will return immediately and your GroupProcedure will finish when all setup tasks are kicked off. 

What you really want is that your GroupProcedure finishes when all of the setup tasks return their result sets. Or more precisely when all of the completion blocks are being called. 

GCD solves that problem by having you make a call to 'dispatch_group_leave()' within the completion block. Something I haven't figured out yet how to do with ProcedureKit?

**Comment by leotumwattana** [comment]
It really depends on when and where you call `finish()` on your individual setup procedures. 

In your case, since your setup procedure is async, then call finish on that procedure in the completion block of your setup. This means that procedure will not be considered completed until you receive the response back from the server. Which also means your *GroupProcedure* will not finish until all of such setup procedures are done.

```
class SetupAProcedure: Procedure {

  override init() {
    super.init()
    name = String(describing: type(of: self))
  }

  override execute() {
    guard !isCancelled else { return }

    someAsyncCode { [weak self] (success, errors) in 
      // ... handle stuff here
      self?.finish()
    }
  }

}
```

**Comment by marwey** [comment]
Ah, the trick is to subclass and override execute(). In my previous approach I was adding the CloudKit procedure directly to a GroupProcedure giving me no choice executing code within the completion block. But your solution looks like it can actually work. I will give it a try ;-) 

Thanks a lot for your suggestion!

**Comment by leotumwattana** [comment]
@marwey: If you are using the included CloudKitProcedures that ProcedureKit provides, then you shouldn't need to subclass anything. Actually, I believe those CloudKitProcedures are not meant to be subclassed at all. They'll call `finish()` for you at the appropriate spot. Just set your various completion handlers for those to get the results you need.

However, if you are writing your own procedures to wrap up some async code, then that's how you'd do it.

**Comment by marwey** [comment]
@leotumwattana Thanks for the additional advice! ;-)

When I first played around with GroupProcedure the CloudKitProcedureKit was not ready for Swift 3 - so I just used plain vanilla CloudKit API (without subclasses). However I got now rid of CloudKit and the way to go seems to be to create a subclass of a procedure, call the async function in `execute()` and handle `finish()` in the completion block.

Will try to implement this the next few days ;-)

**Comment by danthorpe** [comment]
@marwey - just to re-iterate that the advice from @leotumwattana is pretty much spot on. For CloudKit, you can wrap Apple's `CKOperation` subclasses in a `CloudKitProcedure` which will finish correctly for you. e.g. 

```swift
let setupSubscriptions = CloudKitProcedure { CKModifySubscriptionsOperation() }
setupSubscriptions.container = myContainer // etc - you should setup the modify subscription operation "through" the CloudKitProcedure instance
```

If you add procedures like this into your group, the group will wait until they correctly finish.

Also, if you are writing a _setup CloudKit_ procedure, I'd be quite interested in what sort of things you consider "setup" for CloudKit - as this is possibly something which _ProcedureKitCloud_ can help provide.

**Comment by marwey** [comment]
@danthorpe i meant 'setup task' in the following way. Let's say you have an app that displays thousands of cooking recipes in a collection view. The recipe data structure has the following attributes:

```
	title: String
	thumbnail_picture: Image
	number_of_likes: Int
	category: Reference
	cooking_video: Reference
	author: Reference
```
The reference types are described in similar structures. 

Now, when preparing the cell to display this data in the collection view I fetch the data for a specific recipe from the cloud service. It could be iCloud but can actually be any other (cloud) service. In addition I need to fetch the referenced data like e.g. category `title` and `category_thumbnail` to display that information in the collection view. 

In order to avoid costly remote (cloud service) calls I fetch all category data during app start. So when preparing the cell I can do a local dictionary lookup. Beside the category structure I have a couple of other structures that I would like to cache during app startup. Bundling those fetches in a group procedure as described above by @leotumwattana pretty much solves the problem for me. 

The approach certainly has its limits. E.g. it might not work for author structure since the there are too many authors to fetch in advance and that list can also change during runtime. Memory consumption of the app would also increase heavily. But for small, static structures that need to be joined this works pretty well. 

The other issue is that displaying the thumbnail images requires fetching those assets from cloud storage. Depending on the kind of cloud service you use this might require an asynchronous call returning the image data in a completion block. My envisioned approach was to bundle all image fetch operations in a group procedure and returning the cell in 

```
collectionView(_ collectionView: UICollectionView,
                                 cellForItemAt indexPath: IndexPath) -> UICollectionViewCell
```

in the completion block of that group procedure. Unfortunately this doesn't work and makes the compiler reporting a missing return statement. 

Not sure if my approach is best practice or if you guys solve those things differently?

**Comment by marwey** [comment]
Just to close this issue: the structure of the setup procedure I am using is quite simple and can be written on a per-project basis. 

Also, some time ago I already had found a solution for fetching the data and display it in the collection view by separating both in different functions.
