### ISSUE TITLE
ProcedureKit/Cloud (beta5) does not compile

### ISSUE THREAD

**Issue by automactic** [ProcedureKit/ProcedureKit#637]
When adding `ProcedureKit/Cloud` to podfile, the project does not compile. But when `ProcedureKit/Cloud` is removed, the project compiles successfully.

This issue can be recreated by starting an empty project, then add the following to the pod file
```
pod 'ProcedureKit', :git => 'https://github.com/ProcedureKit/ProcedureKit.git', :branch => 'release/4.0.0.beta.5'
pod 'ProcedureKit/Cloud', :git => 'https://github.com/ProcedureKit/ProcedureKit.git', :branch => 'release/4.0.0.beta.5'
pod 'ProcedureKit/Network', :git => 'https://github.com/ProcedureKit/ProcedureKit.git', :branch => 'release/4.0.0.beta.5'
pod 'ProcedureKit/Mobile', :git => 'https://github.com/ProcedureKit/ProcedureKit.git', :branch => 'release/4.0.0.beta.5'
```

Am I doing anything wrong? Please help, thanks!

**Comment by codedifferent** [comment]
I assume your're developing with Xcode 8.2 beta 2 (8C30a) ... yes, ProcedureKit/Cloud does not compile there because of some protocol conformation issues.

But if you're using the stable Xcode Version 8.1 (8B62) - everything works fine :-)

**Comment by codedifferent** [comment]
To be more precise: here are the three compiler errors of the Xcode 8.2 beta 2 (8C30a) with ProcedureKit/Cloud (beta5) & the actual development branch:

```
!! Type 'CKAcceptSharesOperation' does not conform to protocol 'CKAcceptSharesOperationProtocol'
CKAcceptSharesOperation.swift
! Protocol requires property 'sharesMetadatas' with type '[CKAcceptSharesOperation.ShareMetadata]'; do you want to add a stub?
! Candidate has non-matching type '[CKShareMetadata]?'
```
```
!! Type 'CKFetchRecordChangesOperation' does not conform to protocol 'CKFetchRecordChangesOperationProtocol'
CKFetchRecordChangesOperation.swift
! Protocol requires property 'recordZoneID' with type '[CKFetchRecordChangesOperation.RecordZoneID]'; do you want to add a stub?
! Candidate has non-matching type '[CKRecordZoneID]?'
```
```
!! Type 'CKOperation' does not conform to protocol 'CKOperationProtocol'
CKOperation.swift
! Protocol requires property 'longLivedOperationWasPersistedBlock' with type '() -> Void'; do you want to add a stub?
! Candidate has non-matching type '(() -> Void)?' (CloudKit.CKOperation)
```

**Comment by automactic** [comment]
Oh, yes, indeed. Thanks for the reply.

**Comment by danthorpe** [comment]
Thanks @automactic and @codedifferent - not been playing with Xcode 8.2 betas yet. Thanks for the advance notice! 👍

**Comment by swiftlyfalling** [comment]
@automactic: In case you weren't aware, the `development` branch of ProcedureKit has a fix for this.

**Comment by automactic** [comment]
@swiftlyfalling Thanks! I will try it out. 😀
