### ISSUE TITLE
DidCancelObserver and DidFinishObserver gets Called

### ISSUE THREAD

**Issue by vander2675** [ProcedureKit/ProcedureKit#638]
Hey,
probably I'm missing something but I cannot get my head around this. I have some nested GroupProcedures witch themselves have basic Procedures. The GroupProcedures are all setup in the init Method, as suggested in the Documentation. If one of the basic Procedures fails, it calls cancelwithError on itself and then returns from the execute Method. All GroupProcedures have an DidCancelObserver on all of their nested Procedures and cancel themselves with cancelWithError(), if one of their child Procedures get cancelled.

But the most outer GroupProcedure, has an DidCancelObserver and an DidFinishObserver. I want the DidFinishObserver only to get called when there is no cancelation on one of the inner Procedures. But at the moment both Observers get called. When I inspect the DidFinishObserver at runtime, I can even see that it has an Error. Am I missing something? 

I would appreciate any help!
Thanks
Pascal

**Comment by danthorpe** [comment]
Hi @vander2675 - can you include a _simplified_ code snippet?

**Comment by swiftlyfalling** [comment]
@vander2675: A bit of background:

Every Procedure (and Operation) must eventually finish. Even a cancelled Procedure, after it's done halting/cancelling its task and performing any required clean-up, must finish.

If you have some logic in your `DidFinishObserver` that you only want to execute when the Procedure finishes *without* cancellation, you can simply do this:

```swift
op.addDidFinishBlockObserver { procedure, errors in
    guard !procedure.isCancelled else {
        // TODO: anything else you want to do here if cancelled
        return
    }
    // TODO: handle normal finish
}
```

**Comment by vander2675** [comment]
![observer](https://cloud.githubusercontent.com/assets/11850132/21005379/e3e2f26c-bd34-11e6-8594-d7dc3393cf40.png)
Then I got tricked by this Graph. I thought an canceled Operation never reaches finished State.

**Comment by danthorpe** [comment]
@vander2675 - yeah, that is actually technically not correct any more. Sorry!

On the plus side - we are going to change this behavior in #571.

**Comment by vander2675** [comment]
No Problem!
So when I call cancel(withError: ...)  do I need to call finish() now also or is it enough to return from execute()?

**Comment by danthorpe** [comment]
At the moment, you must _either_ call `finish()` **or** `cancel()` from within your subclass.

**Comment by swiftlyfalling** [comment]
To clarify:

**Current Behavior**:
- You must call `finish()` **or** `cancel()` from within your subclass.

**Future Behavior**:
- "Every path must lead to `finish()`." You **must always call `finish()`** from within your subclass.
(Including if you handle cancellation in some special way - you must ensure that `finish()` is eventually called.)

**Comment by vander2675** [comment]
Allright, thank you for the fast clarification.
It's a really great framework and works like magic, if you get the hang on it. :)
