### ISSUE TITLE
Updating some old code to new ProcedureKit

### ISSUE THREAD

**Issue by sixten** [ProcedureKit/ProcedureKit#651]
This is more of a how-to question than an issue.

I've been working on updating an older codebase to Swift 3, and concurrently from a pretty old version of Operations to beta 5 of ProcedureKit. For the most part, this hasn't been too hard, but I admit that I'm a bit stumped when it comes to non-trivial `Condition`s, which work _very_ differently now. In particular, I have one that looks essentially like this:

```swift
struct IsSyncedCondition: OperationCondition {
  let name = "IsSynced"
  let isMutuallyExclusive = false
  
  func dependencyForOperation(_ operation: Operation) -> NSOperation? {
    var dependency: NSOperation?
    if /* … the operation's state isn't synced up … */ {
      dependency = GetSyncedOperation(/* … */)
    }
    return dependency
  }

  func evaluateForOperation(operation: Operation, completion: OperationConditionResult -> Void) {
    if /* … the operation's state isn't synced up … */ {
      completion(.Satisfied)
    }
    else {
      completion(.Failed)
    }
  }
}
```

How does the framework currently handle what `dependencyForOperation(_:)` used to do?

**Comment by danthorpe** [comment]
Hi @sixten - this is a really good question.

Essentially, conditions can still have dependencies, because they are just `Procedure` subclasses. It's just that you would add your dependency to the condition like any normal operation. You could for example do this as part of its initialiser? For example:

```swift
class IsSyncedCondition: Condition {

    override init() {
        super.init()
        if /* … the operation's state isn't synced up … */ {
            add(dependency: GetSyncedOperation(/* … */))
        }
    }

    func evaluate(procedure: Procedure, completion: @escaping (ConditionResult) -> Void) {
        // etc - as before
    }
}
```

**Comment by danthorpe** [comment]
Also, so that you're aware - we are thinking about further changes to `Condition` to support a richer programmer model for conditional procedures, see the discussions in #584

**Comment by sixten** [comment]
Yeah, for some reason, the notion of having the condition configure its dependencies in its initializer hadn't really occurred to me. I'd been sort of stuck on the fact that `evaluate(_:_)` was too late, because the condition was running by then…

There is one important difference here from before: `dependencyForOperation(_:)` was given the target operation—the one to which the condition would be attached—as a parameter. What our existing code does is to examine _that_ operation to determine whether things are synced up before it runs. I suppose I could define an initializer for my condition that took the target operation as a parameter, but that seems kind of smelly. On the other hand, I should also be able to pull out the state that the target operation has that the condition needs to know, and pass _that_ to the initializer. That's also somewhat cleaner than the old approach, since the dependency only flows in one direction.

**Comment by danthorpe** [comment]
@sixten - yes, exactly. I think ultimately, the goal should be to reduce the key elements of the business logic into the smallest possible unit/type - which you then inject into procedures/conditions as needed. I think the old/original API made this less obvious.

**Comment by sixten** [comment]
Yeah, the new approach makes sense. It's just a little disorienting jumping straight from the old idiom to the new. (And at the same time as fixing hundreds of other migration issues…)

Thanks!
