### ISSUE TITLE
Latest 4.0

### ISSUE THREAD

**Issue by appsird** [ProcedureKit/ProcedureKit#667]
What do I insert in my Podfile to download the latest (currently default is 3.4.1 which appears to be Swift 2 based).

pod 'Operations'

Also Tried 

pod 'Operations', :git => 'https://github.com/ProcedureKit/ProcedureKit', :commit => '95f41e9'
pod 'Operations', :git => 'https://github.com/ProcedureKit/ProcedureKit', :tag => '4.0.0.beta.6'

And, no luck as yet. Thanks for assisting.

**Comment by appsird** [comment]
It appears the following will download the later release, though renames to ProcedureKit:

pod 'ProcedureKit', :git => 'https://github.com/ProcedureKit/ProcedureKit.git', :commit => '95f41e9'

it seems the 'Operations' tag is not associated with the beta release. Any suggestions on how to obtain the latest is appreciated.

**Comment by harryworld** [comment]
`ProcedureKit` is targeting Swift 3.0, where `Operations` is for Swift 2.x

If you are looking for Swift 3.0 branch, this is what I use to get latest release `4.0.0.beta.6`

```
pod 'ProcedureKit',
    :git => 'https://github.com/procedurekit/procedurekit',
    :branch => 'release/4.0.0.beta.6'
```

**Comment by danthorpe** [comment]
Thanks @harryworld, sorry @appsird - this dropped off my radar!

To target Swift 2.3, use _Operations_:

```ruby
pod 'Operations'
``` 

to target Swift 3.0, you can use _ProcedureKit_:

```swift
pod 'ProcedureKit'
```

The [podspec](https://github.com/CocoaPods/Specs/blob/master/Specs/b/0/e/ProcedureKit/4.0.0/ProcedureKit.podspec.json) is v4 Beta 6.
