### ISSUE TITLE
Serial queues

### ISSUE THREAD

**Issue by marwey** [ProcedureKit/ProcedureKit#671]
As far as I understand operation queues (like ProcedureQueue) are concurrent by default and the order in which the procedures are picked for execution is not maintained. 
In order to maintain the insertion order of procedures added to a procedure queue, we have to add dependencies between the procedures to guarantee a certain execution order?

**Comment by swiftlyfalling** [comment]
> In order to maintain the insertion order of procedures added to a procedure queue, we have to add dependencies between the procedures to guarantee a certain execution order?

@marwey: Correct.

To provide a bit more detail:

An OperationQueue makes decisions on what operations to execute (and in what order) based on a number of factors. While you can adjust the `maxConcurrentOperationCount` to, for example, set it to `1`, **this does not guarantee execution order will be the same as insertion order**. (Many things can affect execution order, including `qualityOfService`.)

The way to guarantee execution order is to set dependencies.

**Comment by marwey** [comment]
@swiftlyfalling Thanks for clarification and the additional details regarding `maxConcurrentOperationCount` and `qualityOfService`! 

Have not looked at those in great detail but will put it on my to-do list! ;-)
