### ISSUE TITLE
Or Condition

### ISSUE THREAD

**Issue by hactar** [ProcedureKit/ProcedureKit#678]
I'm in a situation where I'd like a procedure to run when at least one of two conditions is fulfilled, a typical "or" - as there appears to be no "OrCondition" in procedurekit (only a negatedcondition) I'm worried that I'm approaching this incorrectly.

Is an OrCondition simply a missing feature or is my approach wrong?

**Comment by danthorpe** [comment]
Hi @hactar - hmm, interesting idea. Off the top of my head, sounds like a reasonable addition! How would you go about implementing it?

**Comment by sviatoslav** [comment]
How about implementing `CompoundCondition` that will work in the same way as `CompoundPredicate`? 
Internal implementation of `CompoundCodition` can be based on `GroupProcedure`.

**Comment by danthorpe** [comment]
@sviatoslav - yep, that's what I would do! Well... pull requests are welcome, if you want to give it a shot. 😊

**Comment by swiftlyfalling** [comment]
@hactar, @sviatoslav: This is now implemented as part of a new Conditions PR (with many other Condition improvements). See #681, and branch `feature/OPR-681_condition_improvements`.

**Comment by hactar** [comment]
Works for me. Nice one, thanks @swiftlyfalling !
