### ISSUE TITLE
Add GitHub Topics

### ISSUE THREAD

**Issue by swiftlyfalling** [ProcedureKit/ProcedureKit#686]
Add appropriate [GitHub Topics](https://github.com/blog/2309-introducing-topics) to the ProcedureKit project, for discoverability.

**Comment by danthorpe** [comment]
Done - feel free to comment on the topics. Do you have edit capabilities on them?

**Comment by swiftlyfalling** [comment]
@danthorpe: Looks good. (And nope, apparently do not have edit capabilities on the GitHub Topics.)
