### ISSUE TITLE
DelayProcedure with NoFailedDependencies is blocking GroupProcedure

### ISSUE THREAD

**Issue by yageek** [ProcedureKit/ProcedureKit#688]
I'm using `ProcedureKit` `4.0.0.beta.6`.

I have s `GroupProcedure` that stops its execution every time in the middle. The subclass looks like:
```
final class Group: GroupProcedure {
    init() {
        let procedureOne = ProcedureOne()

        let procedureTwo = procedureTwo()
        procedureTwo.add(condition: NoFailedDependenciesCondition())
        procedureTwo.add(dependency: procedureOne)

        let procedureThree = procedureThree()
        procedureThree.add(condition: NoFailedDependenciesCondition())
        procedureThree.add(dependency: procedureTwo)

        let delayOp = DelayProcedure(by: 2.0)       
 
       //This lines seems to lock the group
        delayOp.add(condition: NoFailedDependenciesCondition()) 
        delayOp.add(dependency: procedureThree)
       
        let procedureFour = procedureFour()
        procedureFour.add(condition: NoFailedDependenciesCondition())
        procedureFour.add(dependency: delayOp)

      super.init(operations: [procedureOne, procedureTwo, procedureThree, delayOp, procedureFour])
}
```
The execution stops always before the `DelayProcedure`.
Removing the `NoFailedDependenciesCondition` prevent the group to block.

**Comment by swiftlyfalling** [comment]
@yageek: I can't seem to reproduce your issue with beta 6. (I used essentially the example you provided above, but replaced `ProcedureOne()` (etc) with `BlockProcedure`s.)

Have you tried the latest `development` branch? It has numerous improvements and fixes related to conditions (including `NoFailedDependenciesCondition`). If your issue still reproduces with the latest `development`, could you provide some more details as to what your `ProcedureOne`, `ProcedureTwo`, etc do? Or a self-contained repro case?

**Comment by yageek** [comment]
After investigation, it is an error of mine. I putted:
```
 delayOp.add(dependency: NoFailedDependenciesCondition()) 
```
instead of:
```
 delayOp.add(condition: NoFailedDependenciesCondition()) 
```

**Comment by swiftlyfalling** [comment]
@yageek: Ah - good catch!

FYI, that should automatically be caught at compile-time in the latest `development` branch, because of underlying Conditions improvements.
