### ISSUE TITLE
[Question]: BlockProcedure on main queue

### ISSUE THREAD

**Issue by ryanjm** [ProcedureKit/ProcedureKit#693]
With `BlockOperation` there was a way to run the block on the main thread. This seems to be missing from [BlockProcedure](https://github.com/ProcedureKit/ProcedureKit/blob/08a0d37ba66f084073fd687bbd99a34fa9fe1fff/Sources/ProcedureKit/Block.swift#L27). Is that correct? What is the recommended way for having a block which runs on the main thread?

My main uses case is as a completion block for a `GroupProcedure`.

```swift
class MyProcedure: GroupProcedure {

    init(completionHandler: (()->())? = nil) {
        ...
        let completionBlock = BlockOperation {
            if let completion = completionHandler {
                completion()
            }
        }
        ...
    }
...
}
```

**Comment by ryanjm** [comment]
I forgot to look on Slack before posting. For others (or for myself in the future):

> Note, that `BlockProcedure` is “synchronous” which means, that the block is executed and then the procedure finishes. If you need to do something asynchronous in your block, then use `AsyncBlockProcedure`. In which cases you might do something like this....

```
let block = AsyncBlockProcedure { finishWithResult in 
    DispatchQueue.main.async {
        // do something on the main queue, which needed a callback
        finishWithResult(success) // or pass in an error
    }
}
```

**Comment by ryanjm** [comment]
This is what I ended up doing:

```swift
class CompletionBlockProcedure: Procedure {
    typealias CompletionBlock = () -> ()

    let block: CompletionBlock

    /// Will run block on main thread
    init(block: @escaping CompletionBlock) {
        self.block = block
        super.init()
        self.name = "Completion block procedure"
    }

    override func execute() {
        DispatchQueue.main.async {
            self.block()
            self.finish()
        }
    }
}
```

**Comment by danthorpe** [comment]
Yeah, interesting, I might actually do a bit of refactoring of the block procedures, possibly adding `MainBlockProcedure` similar to this.

**Comment by danthorpe** [comment]
Although, I think probably a better solution is to use `ProcedureQueue.mainQueue` like this:

```swift
let block = AsyncBlockProcedure { finishWithResult in
 
    // do something asynchronous which needs a callback

    // Finish the procedure when done, success is defined
    // in ProcedureKit, alternatively pass in an error
    finishWithResult(success)
}

// Remember that Operation dependencies work across queues
other.add(dependency: block)

// Enqueue it on the main queue
ProcedureQueue.mainQueue.add(operation: block)

myQueue.add(operation: other)
```

**Comment by ryanjm** [comment]
`MainBlockProcedure` is a much better name. 😄 I'll change mine to that.

I'm not sure what I'm doing wrong, but with the above code, it doesn't seem to run the block on the main thread. My other concern is the amount of additional code for something that I'm doing pretty frequently.

```swift
    let block = AsyncBlockProcedure { finishWithResult in
        completionBlock()
        finishWithResult(success)
    }
    block.add(dependencies: operations)
    ProcedureQueue.main.add(operations: [block])

    // vs

    let completion = MainBlockProcedure(block: completionBlock)
    completion.add(dependencies: operations)
    operations.append(completion)

    // ...
    self.add(children: operations) // group procedure after super.init
```

My completion block has a print statement with `[NSThread isMainThread]` (Yep, I still have Objective-C code) and it says that it isn't the main thread when I'm using the `AsyncBlockProcedure`.

**Comment by danthorpe** [comment]
But, main thread and main queue are not the same thing. See: http://blog.benjamin-encz.de/post/main-queue-vs-main-thread/

**Comment by ryanjm** [comment]
I'm late to responding, but thank you for the article. That helped clarify things for me.

**Comment by danthorpe** [comment]
Also, this is a slight diversion, but there are [some extension APIs](https://github.com/ProcedureKit/ProcedureKit/blob/development/Sources/ProcedureKit/DispatchQueue%2BProcedureKit.swift#L14) which have been added to `DispatchSource` which might be interesting to you...

```swift
public extension DispatchQueue {

    /// Indicates whether the current queue is the main queue
    public static var isMainDispatchQueue: Bool { get }

    /// Will synchronously execute the work on the main queue, regardless 
    /// of the current queue, even if called from the main queue.
    public static func onMain<T>(execute work: () throws -> T) rethrows -> T
}
```

These are marked public, but not sure if they are available outside of _ProcedureKit_ to be honest. Either way, how they are implemented might be interesting to you.

The `onMain` function is especially interesting - because if you use `DispatchSource.main.sync { }` arbitrarily, then you can cause a deadlock if your current queue happens to the be main queue.
