### ISSUE TITLE
[Question]: using NetworkObserver

### ISSUE THREAD

**Issue by briancordanyoung** [ProcedureKit/ProcedureKit#694]
I've recently transition from swift 2.3 & Operations, to swift 3.0 & ProdcedureKit RC 7.

I must fundamentally misunderstand the new NetworkObserver. How is intended to be used? I've tried the following on my operations and see no indicator:

```
let indicator  = NetworkActivityIndicator.shared
let controller = NetworkActivityController(indicator: indicator)
let networkStatusObserver = NetworkObserver(controller: controller)
procedure.add(observer: networkStatusObserver)

```

**Comment by danthorpe** [comment]
Hi @briancordanyoung - well, you don't need to do *all* of that. On iOS, should just be able to do...

```swift
import ProcedureKit
import ProcedureKitMobile // if not using CocoaPods

procedure.add(observer: NetworkObserver())
```

If that is not working - will need to investigate a bit more - unit testing around here is a bit tricky due to the use of `UIApplication.shared` so there may be a bug 🤔

**Comment by briancordanyoung** [comment]
hmmmm.  I get a compilation error `Missing argument for parameter "controller" in call` when trying to use a NetworkObserver().  Which is why I ended up with the 4 lines of code above. Right now get this error while it is in an extension.

```
extension Procedure
{
    internal func addNeworkObserver() {
        self.add(observer: NetworkObserver())
    }
}
```

**Comment by danthorpe** [comment]
Hmm, will investigate. It should be using these `init` methods, in this extension for iOS, [NetworkObserver+Mobile.swift](https://github.com/ProcedureKit/ProcedureKit/blob/development/Sources/ProcedureKitMobile/NetworkObserver%2BMobile.swift).

**Comment by briancordanyoung** [comment]
FYI.  I  am using CocoaPods and my only import line is:
```
import ProcedureKit
```

**Comment by stevemcintosh** [comment]
I have used this approach
myDownloadProcedure.add(observer: NetworkObserver(controller: NetworkActivityController.shared))

It does the job very nicely.  I hope this is helpful.

**Comment by swiftlyfalling** [comment]
As noted by @danthorpe, as long as all the ProcedureKitMobile files are being included by CocoaPods (specifically: [NetworkObserver+Mobile.swift](https://github.com/ProcedureKit/ProcedureKit/blob/development/Sources/ProcedureKitMobile/NetworkObserver%2BMobile.swift)), then you should be able to avoid having to type:

```swift
NetworkObserver(controller: NetworkActivityController.shared)
```

and should instead be able to type:

```swift
NetworkObserver()
```

on iOS.

**Comment by danthorpe** [comment]
Yeah - will investigate. Might be an error in the CocoaPod spec. Thanks for clarifying @swiftlyfalling 👍

**Comment by briancordanyoung** [comment]
Embarrassing.  I understand now.
The reason I was having trouble was that I did not include `ProcedureKit/Mobile` as a  CocoaPods dependency. (My confusion was related to my pod spec for the development cocoa pod my code is in)

Once ProcedureKit Mobile is properly included (either through the cocoa pods or import statements) then the network observer works as expected.
