### ISSUE TITLE
relevancy in context of latest Swift 3.1 Xcode 8.3

### ISSUE THREAD

**Issue by appsird** [ProcedureKit/ProcedureKit#697]
This framework appears full featured, I only wish it existed 2+ years back when I undertook my current CK project. It seems this (or other similar) framework should be a part of CloudKit proper to protect the overwork taxed developer(s) here. 

the framework uses the abstract class Operation which is already used in Swift 3.x
does this cause issues? The framework never graduated from beta - will this occur?

It appears there was much activity in this repo a year or two back, though less more recently. Are people still using this for their projects?

Thanks for any inputs.

**Comment by danthorpe** [comment]
Hi @appsird, thanks for your question & interest.

_ProcedureKit_ is very much a project in active development. It is relatively widely used, as far as I can tell. Having said that, it's still technically in beta as I've not completed all the documentation yet, and as v4 was a complete re-write from _Operations_ we've been very patient letting people upgrade from Swift 2 to 3 and report any issues.

Additionally, I'm the principle maintainer, and have been taking time out of working in tech recently, so haven't had as much time as I'd have liked to spend on writing docs.

**Comment by appsird** [comment]
Ok, understood.

Is there a branch/tag which compiles cleanly under Swift 3.1 Xcode 8.3?

I tried:

pod repo remove master
pod setup --verbose
pod 'Operations', :git => 'https://github.com/ProcedureKit/ProcedureKit', :branch => 'development', :tag => '4.0.0.beta.6'

Though, this generates error:

[!] Unable to find a specification for 'Operations'.


Thanks for any advice.

**Comment by danthorpe** [comment]
Hi @appsird did you try,

```ruby
pod repo remove master
pod setup --verbose
pod 'ProcedureKit/Mobile', :git => 'https://github.com/ProcedureKit/ProcedureKit', :branch => 'development'
```

Note that, specifying a branch and tag is redundant. And the _Operations_ podspec is only on the 3.4.0 tag, as it was removed from `development` a while ago. Instead use the _ProcedureKit_ podspec.

**Comment by appsird** [comment]
Tried as stated, received the following:

$ pod 'ProcedureKit/Mobile', :git => '
https://github.com/ProcedureKit/ProcedureKit', :branch => 'development'

-bash: https://github.com/ProcedureKit/ProcedureKit,: No such file or
directory

**Comment by appsird** [comment]
I next tried to insert the following into the Podfile

  pod 'ProcedureKit/Mobile', :git => '
https://github.com/ProcedureKit/ProcedureKit', :branch => 'development'

then, performed:

pod install

It appears files are in:

Pods/ProcedureKit/Sources/ProcedureKitMobile


Though the pod was not added to my project proper. Suggestions?

**Comment by codedifferent** [comment]
@appsird be sure to open your project in Xcode by opening the `xcworkspace` file. Otherwise you'll be in trouble with all your cocoapods. Hope this helps.

**Comment by appsird** [comment]
Yes, thanks, I did this though pod not present.

Anyone else using the latest Xcode integrated with success?

**Comment by codedifferent** [comment]
Just created a small test Project & installed the pod, and the started the xcode workspace-file. 
Everything all right ... besides a few compiler warnings. 

![procedurekit-test-project](https://cloud.githubusercontent.com/assets/484507/24462150/8e5dd23c-14a3-11e7-87fe-5f99a756631c.png)

**Comment by appsird** [comment]
Thanks Christian.

Can you please paste your Podfile here with commands used for pod update and install.

**Comment by danthorpe** [comment]
Thanks @codedifferent! Will get those compiler warnings sorted out asap.

@appsird - yep, sorry, wasn't clear in my previous message, you need to put the `pod 'ProcedureKit'` bit inside your [`Podfile`](https://guides.cocoapods.org/using/the-podfile.html) and then run `$ pod install` at the command line. Then open the Xcode workspace. Swift 3.1 is a minor version change, there should not be any issues beyond some warnings perhaps, but I will update `development` asap with any changes.

**Comment by appsird** [comment]
I already have an existing xcworkspace from prior integrated pods.

As per the guide:

https://guides.cocoapods.org/using/using-cocoapods.html

should i use the below workspace directive in the Podfile to add to the
existing xcworkspace?

workspace 'MyWorkspace'

**Comment by danthorpe** [comment]
I think that is only relevant if you have multiple Xcode project files in the same directory as the Podfile.

**Comment by codedifferent** [comment]
@danthorpe  just by the way ... thx for all the work, brain & heart you put in that project ... it's amazing :-)

@appsird here is my litte step by step guide to a smooth running ProcedureKitTest project (assuming you already installed cocoapods as a gem):

1. Create a new project in Xcode ... use the "Single View Application" in the iOS template section.
2. Navigate to the project folder in Terminal app ... the directory, the ProcedureKitTest.xcodeproj is situated.
3. Create a minimum Podfile with the command `pod init`
4. Open the standard Podfile called `Podfile` and add the ProcedureKit pod ... then you Podfile look like this:

```ruby
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ProcedureKitTest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ProcedureKitTest
  pod 'ProcedureKit/Mobile', :git => 'https://github.com/ProcedureKit/ProcedureKit', :branch => 'development'
  
end
```
5. When you saved the edited Podfile, install the pod with the command `pod install` in the terminal
6. If your project is still open in Xcode ... close it. 
7. From now on **ONLY** open your project in Xcode by opening the `.xcworkspace` file ... NOT the `.xcodeproj` file.
8. if you want to update your pods to the latest version of the development branch of ProcedureKit ... just use `pod update` instead of `pod install` in the commandline. 
9. Now you need to Clear and Build your project in Xcode ... otherwise the autocomplete will show an Error `No such module "ProcedureKit"`

10. Now you're ready to create your first ProcedureKit based class by including it ...

```Swift
//  MyFirstProcedure.swift

import ProcedureKit

class MyFirstProcedure: Procedure {
    override init() {
        super.init()
        name = "MyFirstProcedure"
    }
    
    override func execute() {
        // ensure that we check the isCancelled status before we do any kind of work
        guard !isCancelled else { return }
        
        // here is, wehere the work is done :-)
        print("Hello World!")

        // ensure that we call finish() at the end ... to ensure, that the next Procedures in the queue can be processed.
        finish()
    }
}
```


```Swift
//  ViewController.swift

import UIKit
import ProcedureKit

class ViewController: UIViewController {

    override func viewDidLoad() {
        super.viewDidLoad()
        
        // this is how you create a ProcedureKit queue
        let queue = ProcedureQueue()
        let myProcedure = MyFirstProcedure()
        // ... and fire your first "Hello World" as a procedure :-)
        queue.add(operation: myProcedure)
    }
}
```

**Comment by appsird** [comment]
@codedifferent  Walked through your example and it worked perfectly. Uncertain why I cannot get the pod into my existing project - may need to rebuild it from the ground up.

But thanks so much for your kind assistance.

@danthorpe  This is one grand vision you implemented. Thanks again.

Brian.

**Comment by appsird** [comment]
I do receive the warnings below:

![untitled](https://cloud.githubusercontent.com/assets/8471833/24484649/2f845da6-14b4-11e7-987e-1abfa5521642.png)

**Comment by appsird** [comment]
Please make me aware when the warnings are removed. I just performed a 'pod update' and it appears the latest (4.0.0 Beta 7) still has them.

**Comment by danthorpe** [comment]
It's in progress at the moment. You can watch this PR to get notifications: https://github.com/ProcedureKit/ProcedureKit/pull/699

**Comment by danthorpe** [comment]
Gonna close this now, latest release, 4.1.0, is for Swift 3.1 & Xcode 8.3.

**Comment by appsird** [comment]
Thank you Dan.
