### ISSUE TITLE
GroupOperation understanding using swift 2.3

### ISSUE THREAD

**Issue by mateo666** [ProcedureKit/ProcedureKit#698]
Im using version 3.4.0 for swift 2.3 and trying to understand how to properly use GroupOperation

So i have a group operation like this

`
class UpdateModuleFirmwareOperation : GroupOperation, NSProgressReporting{
    
    private(set) var serialCrc:String
    private(set) var firmwareMd5:String
    private(set) var firmwareVersionHex:String
    var progress:NSProgress=NSProgress()
    
    init(serialCrc:String, firmwareMd5:String, firmwareVersionHex:String){
        self.serialCrc = serialCrc
        self.firmwareMd5 = firmwareMd5
        self.firmwareVersionHex = firmwareVersionHex
        self.progress.totalUnitCount = 1300

        let opDownloadFirmware = DownloadFirmwareOperation(serialCrc: serialCrc, firmwareMd5: firmwareMd5)
        self.progress.addChild(opDownloadFirmware.progress, withPendingUnitCount: 100)
        
        let opReadFirmware:ReadHexFileOperation = ReadHexFileOperation()
        self.progress.addChild(opReadFirmware.progress, withPendingUnitCount: 50)

        let opPreFlash = PostFirmwareOperation(serial: serialCrc, md5: nil)
        self.progress.addChild(opPreFlash.progress, withPendingUnitCount: 100)

        let opFlash:DeviceFlashOperation = DeviceFlashOperation()
        self.progress.addChild(opFlash.progress, withPendingUnitCount: 550)
        
        let opPostFlash = PostFirmwareOperation(serial: serialCrc, md5: firmwareMd5)
        self.progress.addChild(opPostFlash.progress, withPendingUnitCount: 100)

        let opPowerOff = DevicePowerOffOperation()
        self.progress.addChild(opPowerOff.progress, withPendingUnitCount: 50)

        let opPowerOn = DevicePowerOnOperation()
        self.progress.addChild(opPowerOn.progress, withPendingUnitCount: 50)

        let opDelay = DelayOperation(interval: 2)
        let opDelay2 = DelayOperation(interval: 3)
        
        let opDeviceConnected = DetectModuleOperation()

        opReadFirmware.addDependency(opDownloadFirmware)
        opPreFlash.addDependency(opReadFirmware)
        opFlash.addDependency(opPreFlash)
        opPostFlash.addDependency(opFlash)
        opPowerOff.addDependency(opPostFlash)
        opDelay.addDependency(opPowerOff)
        opPowerOn.addDependency(opDelay)
        opDelay2.addDependency(opPowerOn)
        opDeviceConnected.addDependency(opDelay2)

        super.init(operations: [opDownloadFirmware, opReadFirmware, opPreFlash, opFlash, opPostFlash, opPowerOff, opDelay, opPowerOn, opDelay2, opDeviceConnected])
        name = "UpdateModuleFirmwareOperation"
}
`

at some point if a child operation encounters an error i call finish(error) on that child operation and the whole group should stop executing and return the proper error.
But all operations gets executed anyway.

So my question is how should i deal with an error occurring in a child operation and canceling all other operations so i can handle the one error that occurred ?

**Comment by danthorpe** [comment]
Hi @mateo666 - sorry for the delayed response.

To handle errors from children there is a `GroupOperation` method which you can override to suppress it.

See the [source code documentation](https://github.com/ProcedureKit/ProcedureKit/blob/3.4.1/Sources/Core/Shared/GroupOperation.swift#L286) in `GroupOperation`. Hope that helps. Let me know if you still have any issues!

**Comment by danthorpe** [comment]
Hi @mateo666 - will close this, please re-open if you have any more issues or questions.

**Comment by mateo666** [comment]
Is the swift 3 version ready and stable ? would like to migrate my project.
Also is there a way to plug in a logger inside to see whats happening under the hood. Im using SwiftyBeaver with JustLog over elasticSearch

**Comment by danthorpe** [comment]
Yep! v4.1.0 is final & ready for Swift 3.1 & Xcode 8 😁

ProcedureKit has its own log functionality, accessed through the log property of Procedure. But it can have a custom logger plugged in quite easily. See [here](https://github.com/danthorpe/Examples/blob/development/Operations/Permissions/Permissions/AppDelegate.swift#L22) for an example plugging in SwiftyBeaver.

**Comment by mateo666** [comment]
Great would love to migrate my project to swift 3. 
Do you have any plan on releasing the documentation ?
or does it exist somewhere ? 
i only see the old one.
