### ISSUE TITLE
Thoughts on UIProcedure

### ISSUE THREAD

**Issue by pronebird** [ProcedureKit/ProcedureKit#704]
I've been looking to migrate some of UI code from Operative to ProcedureKit which has been used across my app in all other parts except UI so far. 

One of the most common operations we have is controller presentation which ensures that there are no simultaneous modal presentations including `UIAlertControllers` which IIRC are exceptional because you can't show anything on top of them.

So here are my thoughts on existing implementation of `ProcedureKitMobile`:

1. `UIProcedures` with modal presentation should be mutually exclusive between each other and should wait until presentation animation completed.
2. Missing dismissal procedure which needs mutual exclusivity too.
3. Mutually exclusive with `UIAlertControllers`. Better wait until they are gone.
4. Given all of above it's not always possible to pin the presenting view controller if they pile up from different sources. Dynamically detecting top modal controller within operation is safer in my opinion than explicitly providing one and that totally breaks `DismissingViewController`. You say it's a mess, but we had certain auxiliary controllers modally displayed within current context to request user action. Not very clean but sometimes there is not much choice.

**Comment by danthorpe** [comment]
Hi @pronebird - really appreciate your thoughts on this. We're always looking for improvements so, suggestions and contributions are more than welcome.

Not really sure what you're advocating for here - a change in how presentation is performed?

**Comment by pronebird** [comment]
@danthorpe yeah I am advocating for a change where we have more explicit dependencies between UI operations to make sure that UIKit does not throw errors or break when modifying view hierarchy simultaneously using more than one UIProcedure.

**Comment by danthorpe** [comment]
And at the moment, `AlertProcedure` is mutually exclusive with all over `AlertProcedure` instances, which is restrictive?

**Comment by pronebird** [comment]
Well `AlertProcedure` is good, it has mutual exclusivity set. However I think if you run AlertOperation and UIProcedure at the same time then things will break.

**Comment by danthorpe** [comment]
I see what you're saying, because `UIProcedure` is un-restricted, then out-of-the-box mixing them together could be un-predicatable.

In general, I'm not really in favour of adding too much mutual exclusivity by default, as I think it can be very easy to introduce dead-locks. Whereas, it is relatively trivial for framework consumers to add their own exclusivity conditions.

Having said that, I can appreciate that typically, your UI code should not have a complete view of all that is going on - so, adding the appropriate conditions is at best - tricky.

hmm.

**Comment by pronebird** [comment]
I agree, mutual exclusivity hell is something I stumbled upon already. However if most of UI operations only restrict presentation for short time such as present/dismiss animations which are in general short then it should be mostly safe to use without deadlocks. I am trying to avoid repetition, I am fine with throwing couple of custom classes to achieve the same, but then I would never use `UIProcedure` since it wouldn't satisfy my basic needs. :-) Adding conditions manually for frequent ops like this is too much boilerplate..

**Comment by danthorpe** [comment]
Hmm, so are you proposing just adding:

```swift
add(condition: MutualExclusivity<UIProcedure>())
```

into the initialiser?

**Comment by pronebird** [comment]
Technically, but we should be careful. It's important that operation is exclusive during animation (i.e `present()` has completion handler). There is also an issue with "show" operation which for some reason does not have completion handler. I worked around that with`CATransaction` in my case.

Roughy, I see `UIProcedure` to be split into smaller operations to modify view hierarchy. `UIProcedure` in its current state supports a lot of cool stuff, like waiting until dismissed and such. 

I really need to play around with that to gather more feedback.

**Comment by pronebird** [comment]
Closing this since `UIProcedure` is now deprecated.
