### ISSUE TITLE
[Question]: How to properly inject results? 

### ISSUE THREAD

**Issue by geraldeersteling** [ProcedureKit/ProcedureKit#716]
Hello,

I've been using Apple's operations from the 'Advanced NSOperations' project for while, but was always struggling with passing the results from operation to operation.

Then I stumbled upon ProcedureKit, but now my question is how I can properly pass results along procedures.

I _think_ I've got it down, but since the docs for result injection aren't there yet, I'd like to know if what I have is OK.

For example:

**The OutputProcedure:**

```swift
class Login: Procedure, OutputProcedure {
    typealias Output = ProfileInfo // for the sake of this example; assume that ProfileInfo is a simple struct
    
    private let username: String
    private let password: String
    
    // Question 1: The protocol states that this property needs to be declared, but there is no 'value' neither here or in the initializer; I can only assume that it is 'pending' like this?
    var output: Pending<ProcedureResult<ProfileIndo>> = Pending.pending
    
    init(username: String, password: String) {
        self.username = username
        self.password = password
    }

    override func execute() {
        
        {...}
        
        // Logging in was OK; and some basic info could be returned
        let info = ProfileInfo()
        finish(withResult: ProcedureResult.success(info))

        // Logging in was NOT OK;
        finish(withResult: ProcedureResult.failure(<someError>))        

        // Question 2: do you 'always' need to use finish(withResult:) or can you also finish with an error? If so, what happens then?
    }

}
```

**The InputProcedure, dependant on the `Login` procedure above:**

```swift
class GetMoreProfileInfo: APIProcedure<UserTarget>, InputProcedure, OutputProcedure {
    typealias Input = ProfileInfo
    typealias Output = MoreProfileInfo // again assume this is a simple struct
    
    // Question 3: The same question as Question 2 really; should you just always declare these properties like this? Seems rather wasteful if so?
    var input: Pending<ProfileInfo> = Pending.pending
    var output: Pending<ProcedureResult<[String : Any]>> = Pending.pending
    
    override func execute() {
        
       // Question 4: Can I just use the input here like this? And what is the purpose of `isPending`? 
       if let someInfo = input.value {
            let fullInfo = MoreProfileInfo(info: someInfo)
            finish(withResult: ProcedureResult.success(fullInfo))
       } else {
            finish(withResult: ProcedureResult.failure(<someError>))
       }
    }
}
```

---

If there are general pointers as to how result injection works: I'm all ears!

**Comment by danthorpe** [comment]
Hi @geraldeersteling - you pretty much have it. I can answer your questions from the comments though to hopefully make it crystal.

## Question 1 & 3

You don't actually need to specify the `Output` and `Input` type aliases - they are inferred from the properties. So, this is enough:

```swift
class Login: Procedure, OutputProcedure {
    var output: Pending<ProcedureResult<ProfileInfo>> = .pending
    // etc
    }

class GetMoreProfileInfo: APIProcedure<UserTarget>, InputProcedure, OutputProcedure {
    var input: Pending<ProfileInfo> = .pending
    var output: Pending<ProcedureResult<[String: Any]>> = .pending
    // etc
}
```

To explain these types a bit more... the `Pending<T>` type is sort of similar to an `Optional`, there is a value, or the value is "pending". Therefore, when declaring the properties, set this as the default, as when the class is initialised, everything is pending.

The `Input` property is a pending value. During the `Procedure`'s lifecycle the `input` property goes from being `.pending` to getting set to the required value __before__ `execute()` is called. Therefore, inside your `execute()` method, you can unwrap as in your example. On the otherhand, the `Output` property is a pending result. A result is either the value or an error, but during the procedure's lifecycle, it is also pending. Hence why we have `Pending<Input>` and `Pending<ProcedureResult<Output>>` as the property types.

## Question 2

The `finish(withResult:)` API is just a shorthand for doing two things at once. For every `Procedure` subclass, you need to call "finish" at some point. If there is an (unrecoverable) error, you must call `finish(withError:)`. For an `OutputProcedure` *before* calling finish, you need to make sure that the output property is set. This is what `finish(withResult:)` does for you. It just sets the `output` property from being `.pending` to `.ready(result)`, and then calls "finish" correctly. So, you should use it if your `Procedure` subclass conforms to `OutputProcedure`. 

Note also, that you don't need to prefix with `ProcedureResult`, just do:

```swift
    finish(withResult: .success(info))
```

## Question 4 - and what the hell is going on?

In your example, there is a critical bit of code not shown - and that is how you connect the two procedures together.

```swift
// Create your procedures
let loginProcedure = LoginProcedure()
let getMoreProfileInfoProcedure = GetMoreProfileInfo()

// Define their dependence & result injection
getMoreProfileInfoProcedure.injectResult(from: loginProcedure) // This API does quite a lot...
```

That [last line of code](https://github.com/ProcedureKit/ProcedureKit/blob/development/Sources/ProcedureKit/ProcedureResult.swift#L198) does a few things...

1. It sets up some observers on the login procedure (referred to as the dependency) for
  ii. when it will finish - to perform the result injection
  iii. when it cancels, to automatically cancel the receiver (the get more profile info procedure)
2. When the dependency will finish, this will check the `output` property, and ultimately unwrap the value, checking that it's not still `.pending` or that there were any errors.
3. Assuming that everything is ok, the `input` property of the receiver get set to the output value. So, the `input` goes from `.pending` to `.ready`, all before the procedure is executed. This transition happens as part of the dependency finishing.

Note also, that the `injectResult(from:)` API has a couple of forms, once which accepts a block, while allows you to receive the `Output` and return the `Input` - which means that simple synchronous data mappings don't require full blown procedures.

---

Hope that answers your questions, get back to me if you have any issues!

**Comment by geraldeersteling** [comment]
Crystal clear @danthorpe! 💎 
And that while I messed up some question numbers too (at question 3 I referred to question 2 instead of 1 😅).

Anyway, thanks for getting back so quickly and with a nice explanation to boot. Much appreciated.

**Comment by danthorpe** [comment]
No probs! Reopen if you have any other questions!

**Comment by geraldeersteling** [comment]
Hey @danthorpe,

Got a question again; this time I'm wondering how to use injection in group procedures.
Let me cook up a context for my question.

---

Say you have a 2 group procedures, Group A and Group B which I'll explain below. 

> _Assume that every bullet-point in the explanation is a single procedure._

#### Group A: an `OutputProcedure` 
- fetches some trivial JSON data from a server
- converts the JSON and attaches an `id` to each object in the JSON
- stores the converted JSON on disk

📤  _outputs the `id`'s that were attached (as `[id]`)_

#### Group B: an `InputProcedure`
📥 _expects an input of `[id]`_

- able to sync a JSON on disk
    - syncing in this context is a trivial matter which just deletes all JSON objects with an `id` not present  in `[id]`
- stores the synced JSON back to disk

---

With the groups above, how could I correctly input the output of 'Group A' into 'Group B'? Where the definition of 'correctly' means that the procedures in Group B can use the `input` from Group A.

> Tried to explain my use case as good as I could without a code snippet, but if one is needed I'll try to make one.

**Comment by danthorpe** [comment]
Hi @geraldeersteling - glad you came back to me on this. With `GroupProcedure` - there isn't really a way that the framework can easily _just make this work_ for you, as the group doesn't really know or impose anything on the types of its children.

But, it's fairly trivial to do what you want just my implementing the `output` and `input` properties dynamically. Something like this:

```swift
class GroupA: GroupProcedure, OutputProcedure {

    var output: Pending<ProcedureResult<[Id]>> {
        get { return jsonConverter.output } // assuming that the last procedure is a property in the group
        set { assertionFailure("\(#function) should not be publically settable.") }
    }
// etc etc
}

class GroupB: GroupProcedure, InputProcedure {

    var input: Pending<[Id]> {
        get { return jsonSync.input }
        set { jsonSync.input = newValue }
    }
  // etc etc
}
```

So, all this is doing really is just exposing the `input` and `output` properties of the appropriate child(s) procedures (which are conceptually internal and possibly private to the group). For simple cases which are just mirroring the first or last child - this feels like boilerplate. But, it is flexible enough that you could conflate multiple outputs from children into the group's output. 

See [ReverseGeocodeUserLocation](https://github.com/ProcedureKit/ProcedureKit/blob/development/Sources/ProcedureKitLocation/ReverseGeocodeUserLocation.swift#L66) for an example of this technique in the framework.

Hope that answers your question, and gives you a direction as how we would recommend doing this. Eager to hear if you have other ideas though!

**Comment by danthorpe** [comment]
Also, @geraldeersteling, the above is the simple conceptual way of doing it. In practice, to ensure that those properties are thread safe - (as they may be accessed/modified between different threads) you would want to wrap access to them inside some sort of lock. See [NetworkData](https://github.com/ProcedureKit/ProcedureKit/blob/development/Sources/ProcedureKitNetwork/NetworkData.swift#L21) for how we do this inside the framework.

**Comment by geraldeersteling** [comment]
Ah nice, thanks for your thoughts @danthorpe!
I'll try to work something out and get back as soon as I get it to work or if I have some other ideas, looks promising though!

**Comment by geraldeersteling** [comment]
Alright, I managed to get it to work in my situation; mostly based off your suggestions.

## What my problem was
As before I needed a `Group` to receive the input from another Procedure/Group. Using your suggestion to dynamically define the `input` really helped. But I couldn't really apply it to my context because the input-receiving group, a group that can delete 'things', spawned its procedures in its `init`. Let's give that group a trivial name; `DeleteThings`.
I made it so `DeleteThings` either expects to be _initialized_ with an array of `Thing`, which it can delete, or to wait on an other procedure which _injects_ an array of `Thing`.

Here is a snippet of the input-receiving group:

```swift
class DeleteThings: GroupProcedure, InputProcedure {

    var input: Pending<[CDICMenu]> = .pending

    init(things: [Things]) {
        
        var operations = [Procedure]()
        
        // Problem #1; At this point, the `input` is not ready yet. So I can't decide whether to use a _provided_ or _injected_ array of Thing 

        // Assume `DeleteThingContent` and `DeleteThing` are two valid Procedures; dependent on a 'thing'
        for thing in things {
            let deleteContent = DeleteThingContent(thing) // I first need the content to be deleted before the 'thing' itself gets deleted
            let deleteThing = DeleteThing(thing)
            deleteThing.addSuccessRequired(dependency: deleteContent) // addSuccessRequired is a simple extension I added which adds the dependency _and_ a NoFailedDependenciesCondition in a single call
            
            operations.append(contentsOf: [deleteContent, deleteThing])
        }

        super.init(operations: operations)
    }
}
```

In the above `DeleteThings` (at _problem # 1_) I couldn't really use your solution. Because the `input` is (from what I understand) ready when the operation executes.

## So what did I do?

So what I did was similar to the `Finishing` in [ReverseGeocodeUserLocation](https://github.com/ProcedureKit/ProcedureKit/blob/development/Sources/ProcedureKitLocation/ReverseGeocodeUserLocation.swift#L66). I added a procedure `Receiving` as an inner class in `DeleteThings`:

```swift
class Receiving: Procedure, InputProcedure, OutputProcedure {
        
        var providedThings: [Thing]
        var output: Pending<ProcedureResult<[Thing]>> = .pending
        var input: Pending<[Thing]> = .pending
        
        init(_ things: [Thing]) {
            self.providedThings = things
            super.init()
        }
        
        override func execute() {
            let things = input.value ?? providedThings
            self.finish(withResult: .success(things))
        }        
    }
```

I also updated the `input` property of `DeleteThings` to:

```swift
    var input: Pending<[Thing]> {
        get { return receiving.input }
        set(receivedInput) { receiving.input = receivedInput }
    }
```

Added `receiving` as a property of `DeleteThings` and updated its `init`:

```swift
var receiving: Receiving

init(things: [Thing]) {
    receiving = Receiving(things)
    super.init(operations: [receiving])
}
```

And finally moved spawning new procedures based on the input to `DeleteThing`'s overridden `childWillFinishWithoutErrors:`:

```swift 
override func childWillFinishWithoutErrors(_ child: Operation) {
        guard let receive = child as? Receiving,
            let things = receive.output.success
            else { return }
        
        var operations = [Procedure]()
        
        for thing in things {
            let deleteContent = DeleteThingContent(thing)
            let deleteThing = DeleteThing(thing)
            deleteThing.addSuccessRequired(dependency: deleteContent)
            
            operations.append(contentsOf: [deleteContent, deleteThing])
        }
        
        add(children: operations)
}
```

---

Adding `Receiving` and handling the group in this way works for my context. I've no idea if this is the best solution for what I need, though. But sharing is caring!

**Comment by danthorpe** [comment]
Yeah - looks sensible! Thanks for sharing this! 🙌

Nice addition with the `addSuccessRequired(dependency:)` might see if we can add that into the framework. 🤔

**Comment by geraldeersteling** [comment]
Ah, that would be great!

I might improve the solution as well later on; I think it should be possible without the `Receiving` procedure or something...anyway I'll re-open the issue if it comes to that.

**Comment by pronebird** [comment]
I wonder if there is any way to funnel the result from procedure into block-based procedure, something like:

```
let mainProcedure = MainProcedure(...)
let otherProcedure = InputBlockProcedure<ProcedureResult<T>>(block: { result in 
  // do something with result
})
otherProcedure.addDependency(mainProcedure)
otherProcedure.injectResult(mainProcedure)
```
