### ISSUE TITLE
Child procedure cancels its GroupProcedure?

### ISSUE THREAD

**Issue by Buju77** [ProcedureKit/ProcedureKit#736]
Is there a built-in method where I can cancel its entire GroupProcedure from a child? Or do I have to pass in the group manually during init of the child procedure?

**Comment by danthorpe** [comment]
There isn't any kind of group property accessible from within a child for its parent group.

The best thing to do would be to cancel with an error, which you can then process in the group and cancel from there.

**Comment by Buju77** [comment]
how does the group catch the cancelation of the child? do you mean like this?

```swift
class UploadOperations: GroupProcedure {
    
    func procedureQueue(_ queue: ProcedureQueue, didFinishProcedure procedure: Procedure, withErrors errors: [Error]) {
        for error in errors {
            // a child encounted an fatal error --> cancel the entire group
            if let error as? CriticalChildError {
                let groupError = GroupCanceledError(...)
                cancel(withError: groupError)
                return
            }
        }
    }
}
```

**Comment by swiftlyfalling** [comment]
@Buju77: I would not recommend overriding the Group's ProcedureQueueDelegate methods. Instead, try one of the following approaches.

### 1. Dependencies + NoFailedDependenciesCondition

If your Group's children are already (or ought to be) a chain of dependencies, you can simply add a `NoFailedDependenciesCondition` to each child, and the errors will propagate, cancelling all child Operations later in the chain.

Example:

```swift
let procedure1 = TestProcedure()
let procedure2 = TestProcedure()
let procedure3 = TestProcedure()
procedure2.add(dependency: procedure1)
procedure2.add(condition: NoFailedDependenciesCondition())
procedure3.add(dependency: procedure2)
procedure3.add(condition: NoFailedDependenciesCondition())
let group = GroupProcedure(operations: [procedure1, procedure2])
```

That's all you have to do. If `procedure1` fails with any error, `procedure2` will be cancelled with an error, and then `procedure3` will be cancelled with an error, and so on.

### 2. GroupProcedure subclass

If, on the other hand, you want to do more complex parsing of errors **or** one or more of your GroupProcedure's children are to run concurrently, you can handle this from inside a GroupProcedure subclass by overriding `child(_:willAttemptRecoveryFromErrors:)`.

Example:

```swift
class UploadOperations: GroupProcedure {
    // ...
    // This function is called for every child Operation that will finish with errors.
    open override func child(_ child: Operation, willAttemptRecoveryFromErrors errors: [Error]) -> Bool {
        for error in errors {
            // a child encounted an fatal error --> cancel the entire group
            if let error as? CriticalChildError {
                let groupError = GroupCanceledError(...)
                cancel(withError: groupError)
                break
            }
        }
        // always call super to get the default GroupProcedure error-aggregation behavior
        return super.child(child, willAttemptRecoveryFromErrors: errors)
    }
}
```

(We may rename that method in the future to make it clearer that it's the one to use to handle errors.)

**Comment by Buju77** [comment]
ah cool thx. I wasn't sure if I should use `didFinishProcedure` or `willAttemptRecoveryFromErrors`.  I chose the first one because it sounded more correct to me for what I wanted to do.

yes all my childs should be run concurrently

**Comment by danthorpe** [comment]
Yeah, I referring to option 2 from @swiftlyfalling's comment above.

As mentioned, we will very likely rename this API - as it's not obvious at all that it's an opportunity for error handling. However, another option, which might be preferable will be to introduce a `delegate` property to `GroupProcedure` which will support this API. This would have the benefit of not having to subclass the class to get custom error handling.

**Comment by Buju77** [comment]
Yeah, a `delegate` would be really nice. But it doesn't matter in my case. I'm subclassing anyway because I'm generating my child operations (lots of them) inside the `execute()` of my custom `GroupProcedure` subclass.

(updating lots of small resources on the server can be easily done in parallel ^^)
