### ISSUE TITLE
The Group recovery method is not called when conditions are not fulfilled.

### ISSUE THREAD

**Issue by yageek** [ProcedureKit/ProcedureKit#742]
I am using ProcedureKit 4.1.0.

Starting from the documentation of the `func child(_ child: Operation, willAttemptRecoveryFromErrors errors: [Error]) -> Bool` of `GroupProcedure`:

 _This method is called when a child will finish with errors.
     (It is called on the Group's EventQueue.)
Often an operation will finish with errors become some of its pre-requisites were notmet. Errors of this nature should be recoverable. This can be done by re-trying the original operation, but with another operation which fulfil the pre-requisites as a dependency.
If the errors were recovered from, return true from this method, else return false.
Errors which are not handled will result in the GroupProcedure finishing with errors._

So in a case of a `GroupProcedure`, I would have imagine that it would be possible to recover from any error produced by its childs, including any failed conditions.

This simple scenario shows the trick:
``` 
ReadBluetoothProcedureGroup = [ReadProcedure]
ReadProcedure <- BluetoothEnabledCondition
```

If `BluetoothEnabledCondition` fails, `func child(_ child: Operation, willAttemptRecoveryFromErrors errors: [Error]) -> Bool` will not be called.

Using the debugger seems to point out that the condition makes the `GroupProcedure` be considered as cancelled:

```swift
/** GroupProcedure extracts  */
    public func procedureQueue(_ queue: ProcedureQueue, willFinishProcedure procedure: Procedure, withErrors errors: [Error]) -> ProcedureFuture? {
        guard queue === self.queue else { return nil }

       // -> Guard returns because the group is cancelled
        guard !isCancelled else { return nil }

        let promise = ProcedurePromise()
        dispatchEvent {
            if !errors.isEmpty {
                if self.child(procedure, willAttemptRecoveryFromErrors: errors) {
                    self.child(procedure, didAttemptRecoveryFromErrors: errors)
                }
                else {
                    self.child(procedure, didEncounterFatalErrors: errors)
                }
            }
            else {
                self.childWillFinishWithoutErrors(procedure)
            }
            promise.complete()
        }
        return promise.future
    }
}
```

I dont' know it if is really an issue but it is not what I would have expected by reading the documentation.

**Comment by danthorpe** [comment]
Thanks @yageek - I think this is possibly a bug, or at least an overlooked use case. Will investigate.

**Comment by swiftlyfalling** [comment]
@yageek:

Using release 4.1.0, if I execute the following code:

```swift
class TestGroup: GroupProcedure {
    override func child(_ child: Operation, willAttemptRecoveryFromErrors errors: [Error]) -> Bool {
        print("child \(child.operationName) willAttemptRecoveryFromErrors: \(errors)")
        return super.child(child, willAttemptRecoveryFromErrors: errors)
    }
}
let child = BlockProcedure { }
let group = TestGroup(operations: [child])
child.add(condition: FalseCondition())
queue.add(operation: group)
```

The `child(_: willAttemptRecoveryFromErrors:)` override is called as expected.

I think there may be something else at play here - can you reduce things down to a minimal repro code sample?

**Comment by danthorpe** [comment]
Yeah, just confirmed. And the `.notice` log spits out the following:

> TestGroup: Will Execute
> TestGroup: Did Execute
> BlockProcedure: Will cancel with errors: [ProcedureKit.ProcedureKitError.FalseCondition()].
> BlockProcedure: Will finish with errors: [ProcedureKit.ProcedureKitError.FalseCondition()].
> child BlockProcedure willAttemptRecoveryFromErrors: [ProcedureKit.ProcedureKitError.FalseCondition()]
> TestGroup: BlockProcedure did encounter 1 fatal errors.
> BlockProcedure: Did finish with errors: [ProcedureKit.ProcedureKitError.FalseCondition()].
> TestGroup: Will finish with errors: [ProcedureKit.ProcedureKitError.FalseCondition()].
> TestGroup: Did finish with errors: [ProcedureKit.ProcedureKitError.FalseCondition()].

**Comment by yageek** [comment]
My bad 😒  This seems to be related to a coding issue on my side. I'm trying to rewrite my previous code and I am not able to reproduce. I would suspect that I simply did not add the correct element to the queue.
