### ISSUE TITLE
[Poll]: When will you drop support for iOS 8?

### ISSUE THREAD

**Issue by danthorpe** [ProcedureKit/ProcedureKit#748]
**For this to work, please give a +1 to one of my comments below that is a best reflection of your intentions in terms of dropping iOS 8**

At _ProcedureKit_, when Xcode 9 is released, we would quite like to advance the minimum deployment target to iOS 9, for the myriad of reasons that software developers can appreciate.

However, as framework developers, we obviously don't want to pull the rugs out from under application developers that depend on _ProcedureKit_. So, we're trying to get a sense of how ready framework consumers are to drop iOS 8 come October. Give that around 2.5% of the iOS userbase is running an OS older than iOS 9 [1] - we're hoping that they'll only be a few holdouts.

1: Mixpanel Trends on iOS 10 adoption: https://mixpanel.com/trends/#report/ios_10

**Comment by danthorpe** [comment]
Already dropped support for iOS!

**Comment by danthorpe** [comment]
Will drop support around October time, when Xcode 9 / iOS 11 / iPhone 8 is released

**Comment by danthorpe** [comment]
Will wait 3 months after Xcode 9 / iOS 11 / iPhone 8 release - say, end of 2017.

**Comment by danthorpe** [comment]
Will wait 6 months after Xcode 9 / iOS 11 / iPhone 8 release - say, end of March 2017.

**Comment by danthorpe** [comment]
I love iOS 8 - I'm never upgrading!

**Comment by stevejmcintosh** [comment]
Drop iOS 8 and go for 9. To many projects that I've been on have been based on the false assumption that their user base is running on a version that no one users. Look at the stats on what people are using. Usually it's 90% running the current iOS update.

**Comment by danthorpe** [comment]
Appreciate that @stevejmcintosh, and I largely agree with you, but it really depends on your own app's users. Generally speaking, it's not a decision that the engineering teams can make entirely by themselves, as there are likely business elements to consider too.

**Comment by asos-petergoldsmith** [comment]
> Already dropped support for iOS!
Is that supposed to read "Already dropped support for iOS 8!"

**Comment by danthorpe** [comment]
@asos-petergoldsmith - oh, yep, thanks! Can you and a +1 to that comment, we're gonna count +1s together a sense of where everyone is. Thanks!

**Comment by leotumwattana** [comment]
Already dropped support for iOS 8.

**Comment by lukeredpath** [comment]
My client is currently unable to drop support for iOS 8 and I doubt they will be able to by October. Their codebase depends heavily on ProcedureKit so I hope it can remain backwards compatible. No problem not supporting iOS 8 for new features but please keep old ones working.

**Comment by danthorpe** [comment]
@lukeredpath yeah, at the moment, we are planning that _ProcedureKit_ v5 will be Xcode 9 & Swift 4 with a minimum iOS 9, and we'll maintain support (i.e. bug fixes) for _ProcedureKit_ v4.x until March 2018 at a minimum (I think).

At the moment, we're really just trying to get a sense of how many developers are still stuck on iOS 8 (really, Xcode 8) - as it's clearly a greater maintenance effort to maintain runtime switches.

**Comment by jshier** [comment]
If you look at the [MixPanel for iOS 8](https://mixpanel.com/trends/#report/ios_8/from_date:-365,report_unit:day,to_date:0), you can see that it's at 1.16% most recently. 

For Alamofire 5 we'll be dropping iOS 8 support (most likely) due to some rather nasty hacks around bugs. We tried to drop it for AF4 but with the huge breaking changes in Swift, it wasn't easy for people to update. That, added to to Xcode 8.3 dropping support for Swift 2.3, and we added support back. Now with 3.2 and 4 being the same compiler, we can ship a hybrid version of AF4 that builds on Swift 3.1, 3.2, and 4, while we work to make AF5 Swift 4 only.

For my company, we recently had our biggest client drop iOS 8 altogether and for new build projects we recommend current - 1 at most, with some being iOS 10 only.

**Comment by danthorpe** [comment]
Hey @jshier, thanks for the feedback. The plan you describe for AFN is pretty much the same as what myself and @swiftlyfalling have been discussing & envision for PK.

This poll is really just to give us an (albeit limited) indication of developers' situations.

**Comment by danthorpe** [comment]
Thanks all.
