### ISSUE TITLE
ProcedureObserver fails to compile in Xcode 9 beta 3

### ISSUE THREAD

**Issue by appsird** [ProcedureKit/ProcedureKit#752]
I receive a new error when compiling with said release:

![image](https://user-images.githubusercontent.com/8471833/28039078-dce7c3b8-6575-11e7-8372-d5838d92d9b1.png)

**Comment by danthorpe** [comment]
Oh, thanks @appsird not checked with Beta 3 yet.

**Comment by danthorpe** [comment]
Looks like this has already been [reported](https://bugs.swift.org/browse/SR-5265?jql=text%20~%20%22ProcedureKit%22) as a "won't fix" bug - annoyingly I didn't see it until now.

Will investigate.

**Comment by danthorpe** [comment]
This is a bit of a serious situation, as the "construct" which allows complete typing of a procedure inside an observer is actually considered a weakness of the generics system, which has now been fixed. Hmm. We're investigating and considering the approach.

However, for anyone who is on the bleeding edge (_ProcedureKit_ `development` with Xcode 9 betas) - then for now, stay on Beta 2.

Any fixes for this will likely bump us to version 5 (a bit earlier than I planned, but probably unavoidable).

**Comment by dimat** [comment]
It seems that beta 3 now supports only swift 3.2 as the lowest version, but if I open my project in xcode 8, then it shows that procedurekit is on swift 3.0

**Comment by danthorpe** [comment]
Hi - @dimat, yep, that is as expected.

**Comment by swiftlyfalling** [comment]
As an update, #754 should fix this issue - and be sufficiently backwards-compatible to make it into a future 4.x point release. Will be merged into `development` soon.

**Comment by appsird** [comment]
Thanks Daniel.

**Comment by dimat** [comment]
Thanks a lot!
Any chance to bump the version as well?

**Comment by swiftlyfalling** [comment]
@dimat: This should make it into the next 4.x release. Not sure exactly what the timeframe looks like for that just yet.

**Comment by danthorpe** [comment]
Was hoping to get the documentation guides done before doing v4.3. Will bump a new version this week though, and maybe doc site will be v4.4.
