### ISSUE TITLE
v5 API cleanup

### ISSUE THREAD

**Issue by swiftlyfalling** [ProcedureKit/ProcedureKit#758]
> **Work-In-Progress**

### Visibility:

Procedure
- [ ] `willEnqueue(on:)` (should probably be `internal` - should only be called from ProcedureQueue and the tests)
- [ ] `pendingQueueStart()` (should probably be `internal` - should only be called from ProcedureQueue and the tests)

Profiler.swift
- [ ] `ProcedureEvent` (should probably be `internal` or even `fileprivate`)

ExclusivityManager
> The whole of `ExclusivityManager` is only `public` because a single function `__tearDownForUnitTesting()` is `public`. With how mutual exclusivity has changed since v4, there should be no need for anyone (especially not tests outside of the framework) to call `__tearDownForUnitTesting()` ever.

- [ ] Consider removing `__tearDownForUnitTesting()` altogether.
- [ ] Make `ExclusivityManager` `internal`, if not `fileprivate`.

### Unavailable (renamed):

RepeatProcedure
- [ ] ❓ `replaceConfigureBlock(block:)` (replacement named `replace(configureBlock:)` already exists)
- [ ] ❓ `appendConfigureBlock(block:)` (replacement named `append(configureBlock:)` already exists)

### Other cleanup:

- [ ] Transition the few remaining uses of `NSLock` to `PThreadMutex`.
- [ ] Replace the one remaining use of `NSRecursiveLock` (in one of the testing framework components).
- [ ] Remove the `NSLock` / `NSRecursiveLock` extensions.
- [ ] Refactor and replace all remaining uses of `DispatchQueue.onMain`.
- [ ] Remove (or at least mark `internal`) `DispatchQeueue.onMain`. (It can't be made 100% safe.)

**Comment by danthorpe** [comment]
For the `[replace|append]ConfigureBlock(block:)` API - I would say to keep them. Consider their usage:

This is from the `NetworkProcedure.init`:

```swift
if let timeout = resilience.requestTimeout {
    appendConfigureBlock { $0.add(observer: TimeoutObserver(by: timeout)) }
}
```

if it is changed, this becomes:

```swift
if let timeout = resilience.requestTimeout {
    append { $0.add(observer: TimeoutObserver(by: timeout)) }
}
```

The other API variant exists so that it is nicer to use when passing closures around, such as (sort-of) [here](https://github.com/ProcedureKit/ProcedureKit/blob/4f8761a0ce8bc9dd4e16f9b9e042fe9ef70386d8/Sources/ProcedureKit/Repeat.swift#L225)

```swift
if let newConfigureBlock = payload.configure {
    _replace(configureBlock: newConfigureBlock)
}
```

But this isn't really used much. So, all things considered - would probably leave it as is, or else stick with `[append|replace]ConfigureBlock(block:)`

Thoughts?

**Comment by swiftlyfalling** [comment]
@danthorpe: I suppose it could also result in changing:

```swift
if let timeout = resilience.requestTimeout {
    appendConfigureBlock { $0.add(observer: TimeoutObserver(by: timeout)) }
}
```

to:

```swift
if let timeout = resilience.requestTimeout {
    append(configureBlock: { $0.add(observer: TimeoutObserver(by: timeout)) })
}
```

I'm not wedded to one way or the other. Just noticed the duplicates in a partial audit.

**Comment by blg-andreasbraun** [comment]
We could finally add progress reporting to NetworkProcedure now that URLSessionTask has support for that :)
