### ISSUE TITLE
Conditions are not Validated on the Same queue as the Procedure

### ISSUE THREAD

**Issue by vander2675** [ProcedureKit/ProcedureKit#760]
The Conditions added to an Procedure, are Evaluated on another Queue, which gets created uniquely for each Procedure with Condtions. So there is no Thread-Safe access to resources inside of Conditions, when having multiple Procedures with the same Condition.

How about making the queue evaluating the Conditions the same Queue as the Procedures Queue?

**Comment by danthorpe** [comment]
Hi @vander2675, I think evaluating conditions serially on the same queue would be a significant performance impact to achieve thread-safety of `Condition`. 

Can you describe what you're trying to do, perhaps we can suggest an alternative direction?

/cc @swiftlyfalling

**Comment by vander2675** [comment]
Hi @danthorpe,
I have a Procedure wich is Downloading an Image. Before start downloading an Image, the Condition should evaluate, if there is already an Download running. What I'm using right now, is an Dict wich saves if an unique ImageID is already set. That means, there is already an Procedure downloading this image right now. This access to the Dict needs to be thread safe.

**Comment by swiftlyfalling** [comment]
Hi @vander2675:

Yes, Conditions are explicitly evaluated asynchronously. What you've described in your first post is an implementation detail that affects only Conditions with dependencies - so the best way to think about it is "Conditions are evaluated asynchronously".

So let's dig down into the root problem you described: you need what your Condition does (in its evaluation) to be thread-safe.

The solution is to make it thread-safe! 😁

There are many options here, but taking a look at your specific use-case:
> I have a Procedure wich is Downloading an Image. Before start downloading an Image, the Condition should evaluate, if there is already an Download running. What I'm using right now, is an Dict wich saves if an unique ImageID is already set. That means, there is already an Procedure downloading this image right now. This access to the Dict needs to be thread safe.

The solution is to ensure that access to the Dict is thread-safe. ProcedureKit provides `PThreadMutex`, which conveniently wraps a pthread mutex, and that would be one way to do it.

However, please also keep in mind that a Condition is only called when it is evaluated. It doesn't magically receive other events that might be helpful (like when an image download procedure has finished). But there *is* a feature of ProcedureKit that's called both before `execute` and after `finish` - an Observer!

So here's one way of that I believe will solve your use-case - with an Observer:

```swift
// let's abstract out your registry of currently-running image downloads into a class
// that provides thread-safe methods
class RunningImageDownloadsContext {
    private var imagesDownloading = Set<ImageID>()
    private let lock = PThreadMutex()

    // If no other image download for the specific ImageID is currently proceeding,
    // return true (and record that this ImageID is now proceeding to download).
    // Else, return false.
    func tryImageDownloadProceed(_ procedure: YourImageDownloadProcedure) -> Bool {
        return lock.withCriticalScope {
            let (inserted, _) = imagesDownloading.insert(procedure.imageID)
            return inserted
        }
    }

    // Removes the specific ImageID from the set of images currently downloading
    func imageDownloadComplete(_ procedure: YourImageDownloadProcedure) {
        lock.withCriticalScope {
            let removed = imagesDownloading.remove(procedure.imageID)
            assert(removed != nil, "imageDownloadComplete called for ImageID that does not exist in set")
        }
    }
}

// Now, let's create a custom Observer so we can handle the willExecute and didFinish events
class ImageDownloadObserver: ProcedureObserver {
    private let context: RunningImageDownloadsContext

    enum Errors: Error {
        case DuplicateImageDownloadInProgress
    }

    init(context: RunningImageDownloadsContext) {
        self.context = context
    }

    func will(execute procedure: Procedure, pendingExecute: PendingExecuteEvent) {
        guard let imageDownloadProcedure = procedure as? YourImageDownloadProcedure else { assertionFailure("ImageDownloadObserver was added to a \(procedure)"); return }
        guard context.tryImageDownloadProceed(imageDownloadProcedure) else {
            // tryImageDownloadProceed failed - another image download for this ImageID is currently in-process
            // so, cancel this procedure
            procedure.cancel(withError: Errors.DuplicateImageDownloadInProgress)
        }
    }

    func did(finish procedure: Procedure, withErrors: [Error]) {
        guard let imageDownloadProcedure = procedure as? YourImageDownloadProcedure else { assertionFailure("ImageDownloadObserver was added to a \(procedure)"); return }
        imageDownloadComplete(imageDownloadProcedure)
    }
}

// now, just create a single RunningImageDownloadsContext for a group of image downloads that may include duplicates
let context = RunningImageDownloadsContext() // store this somewhere

// then add a ImageDownloadObserver to every YourImageDownloadProcedure using that context
// for example:
let imageDownload = YourImageDownloadProcedure(...)
imageDownload.add(observer: ImageDownloadObserver(context: context))
```

You'll obviously need to tweak the specifics above - I assumed a custom Procedure called `YourImageDownloadProcedure`, that has a property called `imageID` which is type `ImageID`. Replace those as needed.

And to be clear, the above handles removing items from the list of *currently-downloading* images. To do so conveniently, we need the events that Observers provide. If you instead want to create a list of all image downloads that are or have downloaded, you could use a Condition and just use the same `RunningImageDownloadsContext` class (just don't call `imageDownloadComplete`).

**Comment by danthorpe** [comment]
Hi @vander2675 - gonna close this for now.
