### ISSUE TITLE
Must be called from main thread only

### ISSUE THREAD

**Issue by leotumwattana** [ProcedureKit/ProcedureKit#776]
I've been updating my project to Xcode 9 the past few days and noted some analyser warnings on `UI API called from background thread`. So just wanted to post up issues to various projects on **GitHub** as a start.

**First that I've found for ProcedureKit:**
`BackgroundObserver.swift:31`

![backgroundobserver swift](https://user-images.githubusercontent.com/544211/28601715-7be92b1e-71ec-11e7-8779-d1cdf5bb561b.png)

**Comment by danthorpe** [comment]
Oh - okay. That's an easy fix. 👍

**Comment by swiftlyfalling** [comment]
@leotumwattana: Could you try the `feature/OPR-781_improve_backgroundobserver` branch?

(It has numerous improvements to BackgroundObserver. See PR #781 for details.)

**Comment by leotumwattana** [comment]
@swiftlyfalling: Thanks. Just tried `feature/OPR-781_improve_backgroundobserver` and it seems to be working great so far. That warning has been fixed. I'll report back if I find any issue. 👍

**Comment by danthorpe** [comment]
Closing this, as it's now fixed by #781.
