### ISSUE TITLE
GroupProcedure DidFinish observer is not guaranteed to execute before child DidFinish observers

### ISSUE THREAD

**Issue by nickmshelley** [ProcedureKit/ProcedureKit#778]
Steps: Have a set of individual procedures, each with some post-processing in a `didFinish` observer on that individual procedure. Put those in a group procedure and set a `didFinish` observer on the whole group.

Expected: The group's `didFinish` is always run _after_ all of the individual procedures' `didFinish` observers fire.

Actual: When the last procedure in the group finishes, which `didFinish` that gets run first is undefined (race condition).

Now that we know what's happening, the behavior makes sense. We fixed it by changing the individual procedure observers to `willFinish`. But I think this behavior is a bit confusing and unexpected and the resulting bug was pretty hard to track down.

**Comment by swiftlyfalling** [comment]
@nickmshelley:

The only guarantee that DidFinish observers make is that they will be executed at some point after the Procedure's `isFinished` becomes `true`.

There is no guarantee as to the relative ordering with respect to _anything_ else (besides events for *that* Procedure instance that occurred previously).

Switching to WillFinish observers is exactly the right move. 👍 If you need to do something when a Procedure will finish (i.e. after `finish()` has been called, but _before anything depending on it finishing proceeds_), absolutely 100% use a WillFinish observer. 

This is important for many other cases, like what happens with **dependencies**. 

To start, let's look back at `Foundation.Operation`: 

Once all of an `Operation`'s dependencies become finished, it is ready to execute.
This means that there is no guarantee that a _dependency's_ [completion block](https://developer.apple.com/documentation/foundation/operation/1408085-completionblock) (which only guarantees it will be executed [*at some point after the Operation finishes*](https://developer.apple.com/documentation/foundation/operation/1408085-completionblock)) will be called or finish executing prior to dependent Operations executing.

For a `Foundation.Operation`, there isn't an easy way of solving this. This is part of why, for example, the various `CKOperation` subclasses (in CloudKit) have a separate handler block that is called when processing is finished, but before the `CKOperation` signals it is finished (example: [`fetchRecordsCompletionBlock`](https://developer.apple.com/documentation/cloudkit/ckfetchrecordsoperation/1476078-fetchrecordscompletionblock)).

In ProcedureKit, you have the WillFinish observer built-in to every `Procedure` subclass. If you need the explicit ordering behavior, use a WillFinish observer.

The documentation surrounding this can certainly improve (there is a massive effort currently underway to update and expand the documentation). I'll look into what we can do to clarify the distinction between Will and Did observers. (And it sounds like a good idea to add a reminder about this to the `GroupProcedure` documentation.)

As far as the behavior you saw using DidFinish observers: This is as expected.

**Comment by nickmshelley** [comment]
Thanks for the detailed explanation.
