### ISSUE TITLE
Method names and Swift 3 conventions

### ISSUE THREAD

**Issue by lukeredpath** [ProcedureKit/ProcedureKit#796]
I had a bit of discussion with @danthorpe on Twitter about this and thought I'd open an issue.

I believe there's some inconsistency with some of the methods in the public API and how they relate to the Swift naming guidelines. I'm aware these are just guidelines however if the aim is to try and adhere to those where possible I believe there is a case for renaming some.

In particular, I'm calling out the `add()` family of methods. There are multiple methods with this name, with different parameters, but they all have inherently different behaviour and I believe the method name should reflect that. For example, we have:

* `add(child: ...)`
* `add(dependency: ...)`
* `add(observer: ...)`
* `add(condition: ...)`

All of these methods, when combined with their first parameter label, form a grammatical phrase rather than a prepositional phrase. According to the Swift 3 guidelines (https://swift.org/documentation/api-design-guidelines/):

> When the first argument forms part of a prepositional phrase, give it an argument label. The argument label should normally begin at the preposition, e.g. x.removeBoxes(havingLength: 12)

It goes on to say:

> Otherwise, if the first argument forms part of a grammatical phrase, *omit its label, appending any preceding words to the base name, e.g. x.addSubview(y)*

Emphasis mine. Therefore, I believe these methods should be renamed to `addChild(_)`, `addObserver(_)`, etc.

In addition, the queue has `add(procedure: )`. This is also grammatical and IMO should be renamed to `addProcedure()` although I can also see an argument for simply `add(_:)` - this is slightly more succinct possibly at the expense of expressiveness although you only really add procedures to a procedure queue so its arguably clear enough. `addProcedure()` is probably more consistent with my other suggestions.

It's worth noting that `NSOperationQueue` uses `addOperation()` and `addDependency()`.

**Comment by danthorpe** [comment]
Totally agree with this. Kinda swamped at the moment, but we can get this done for v4.4, with deprecation warnings, and then v5 can remove the deprecations.

**Comment by danthorpe** [comment]
Thanks for reporting it @lukeredpath
