### ISSUE TITLE
[Question]: Sync execution of procedures with finish blocks

### ISSUE THREAD

**Issue by pomozoff** [ProcedureKit/ProcedureKit#798]
Sorry, I can't create a new tag on SO, therefore I'm asking here.

I'd like to synchronyze execution of procedures with finish blocks, as it was on first beta 4.0 releases.
For example - I have two procedures **A** and **B** and one serial operation queue **Q**. I add a finish block **F** to the procedure **A** and want that procedure **B** will be executed **AFTER** block **F** was finished.
I saw **synchronizedWith** argument, but I can't understand how to put the OperationQueue instance there.
Is it possible using the release of PK v4.3?

**Comment by swiftlyfalling** [comment]
Absolutely. Use a **`WillFinish` observer**.

DidFinish observers execute *after* a Procedure transitions to the finished state. A Procedure finishing is what determines when dependencies (or the next Procedure, in the event of a serial queue) runs. Hence, the only guarantee made about a DidFinish observer is that it will execute at some point after the Procedure finishes.

If you want something to execute **when the Procedure is in the process of finishing, but _before_ it sets its finished state to true** (triggering dependencies, the next Procedure on a serial queue, etc) use a WillFinish observer. This will do exactly what you want.

**Comment by pomozoff** [comment]
Thank you!
