### ISSUE TITLE
carthage build with Xcode 9 error

### ISSUE THREAD

**Issue by mateo666** [ProcedureKit/ProcedureKit#800]
trying to install with carthage 

carthage update ProcedureKit --no-use-binaries --platform iOS 

*** Checking out ProcedureKit at "4.3.2"
*** xcodebuild output can be found in /var/folders/0h/qh_n5bjs0jzch9h7g_10mpqc0000gn/T/carthage-xcodebuild.QigCZi.log
*** Building scheme "ProcedureKit" in ProcedureKit.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/mateo/Dev/Fortin/FlashLink/ios/Carthage/Checkouts/ProcedureKit/ProcedureKit.xcodeproj -scheme ProcedureKit -configuration Release -derivedDataPath /Users/mateo/Library/Caches/org.carthage.CarthageKit/DerivedData/9.0_9A235/ProcedureKit/4.3.2 -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES build (launched in /Users/mateo/Dev/Fortin/FlashLink/ios/Carthage/Checkouts/ProcedureKit)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/0h/qh_n5bjs0jzch9h7g_10mpqc0000gn/T/carthage-xcodebuild.QigCZi.log

**Comment by mateo666** [comment]
here is the end of the log

** BUILD FAILED **


The following build commands failed:
    PhaseScriptExecution Swift\ Lint /Users/mateo/Library/Caches/org.carthage.CarthageKit/DerivedData/9.0_9A235/ProcedureKit/4.2.0/Build/Intermediates.noindex/ProcedureKit.build/Release-iphoneos/ProcedureKit.build/Script-65A2D8001D69FBFD00FB067C.sh
(1 failure)

**Comment by jshier** [comment]
Linting issues related to #799.

**Comment by mateo666** [comment]
thanks for the reply.
Any workaround ?

**Comment by danthorpe** [comment]
@mateo666 - update your `Cartfile` to point at `development`:

```
github "ProcedureKit/ProcedureKit" "development"
```

and then re-build:
```
$ carthage update ProcedureKit --no-use-binaries --platform iOS
*** Fetching ProcedureKit
*** Checking out ProcedureKit at "ef61b0363ff9345d97edad7b97f466d4c1248b45"
*** xcodebuild output can be found in /var/folders/36/tvprlgf11qg3c4nh0675qgz00000gn/T/carthage-xcodebuild.LEv05l.log
*** Building scheme "ProcedureKitMobile" in ProcedureKit.xcodeproj
*** Building scheme "ProcedureKitNetwork" in ProcedureKit.xcodeproj
*** Building scheme "ProcedureKitCloud" in ProcedureKit.xcodeproj
*** Building scheme "TestingProcedureKit" in ProcedureKit.xcodeproj
*** Building scheme "ProcedureKit" in ProcedureKit.xcodeproj
*** Building scheme "ProcedureKitLocation" in ProcedureKit.xcodeproj
*** Building scheme "Stress Tests" in ProcedureKit.xcodeproj
```

Keep and eye on the _ProcedureKit_ releases, as a new version is imminent.

**Comment by mateo666** [comment]
working
thanks
