### ISSUE TITLE
Fail to install via Carthage when Swiftlint 0.22.0 is installed

### ISSUE THREAD

**Issue by dalu93** [ProcedureKit/ProcedureKit#803]
Hi,
I'm noticing that Carthage build for ProcedureKit fails for Swiftlint issues related to changes done in Swiftlint 0.22.0.
My fix for now was to downgrade the version to 0.21.0.
IS there any possibility you can fix the errors please?

**Comment by danthorpe** [comment]
You can build from `development` at the moment, put this in your `Cartfile`:

```
github "ProcedureKit/ProcedureKit" "development"
```

then update with: `carthage update --no-use-binaries`

**Comment by flopIrish** [comment]
Hi,
by building from development, I am seeing another issue: 
```
/Users/fjeu0001/Documents/Dev/networking-ios/Carthage/Checkouts/ProcedureKit/Sources/ProcedureKitLocation/LocationSupport.swift:94:13: error: 'startUpdatingLocation()' is only available on watchOS application extension 3.0 or newer
            startUpdatingLocation()
            ^
/Users/fjeu0001/Documents/Dev/networking-ios/Carthage/Checkouts/ProcedureKit/Sources/ProcedureKitLocation/LocationSupport.swift:94:13: note: add 'if #available' version check
            startUpdatingLocation()
            ^
/Users/fjeu0001/Documents/Dev/networking-ios/Carthage/Checkouts/ProcedureKit/Sources/ProcedureKitLocation/LocationSupport.swift:92:10: note: add @available attribute to enclosing instance method
    func pk_startUpdatingLocation() {
         ^
/Users/fjeu0001/Documents/Dev/networking-ios/Carthage/Checkouts/ProcedureKit/Sources/ProcedureKitLocation/LocationSupport.swift:86:1: note: add @available attribute to enclosing extension
extension CLLocationManager: LocationServicesProtocol {
^
** BUILD FAILED **
The following build commands failed:
	CompileSwift normal armv7k
	CompileSwiftSources normal armv7k com.apple.xcode.tools.swift.compiler
```

**Comment by flopIrish** [comment]
If I use Carthage with ProcedureKit 4.3.2, I am seeing an issue related to swiftLint:
The code below:
(_currentEvaluationContext == nil, "Evaluating the same Condition twice is not supported.")
Is replaced by:
assert(_currentEvaluationContext =, "Evaluating the same Condition twice is not supported."

**Comment by danthorpe** [comment]
Hi @flopIrish @dalu93 - this is now fixed.


>$ carthage update
*** Fetching ProcedureKit
*** Checking out ProcedureKit at "4.4.0"
*** xcodebuild output can be found in /var/folders/36/tvprlgf11qg3c4nh0675qgz00000gn/T/carthage-xcodebuild.gG4TdK.log
*** Building scheme "ProcedureKit" in ProcedureKit.xcodeproj
*** Building scheme "ProcedureKitMobile" in ProcedureKit.xcodeproj
*** Building scheme "ProcedureKitCloud" in ProcedureKit.xcodeproj
*** Building scheme "ProcedureKitTV" in ProcedureKit.xcodeproj
*** Building scheme "TestingProcedureKit" in ProcedureKit.xcodeproj
*** Building scheme "Stress Tests" in ProcedureKit.xcodeproj
*** Building scheme "ProcedureKitLocation" in ProcedureKit.xcodeproj
*** Building scheme "ProcedureKitNetwork" in ProcedureKit.xcodeproj
*** Building scheme "ProcedureKitMac" in ProcedureKit.xcodeproj
$ cat Cartfile
github "ProcedureKit/ProcedureKit"

**Comment by flopIrish** [comment]
thanks @danthorpe !
