### ISSUE TITLE
Potential memory leak in AsyncTransformProcedure, AsyncResultProcedure

### ISSUE THREAD

**Issue by Sander-Kornev** [ProcedureKit/ProcedureKit#807]
There is a case to get memory leak while using mentioned classes because of their internal structure.

```
open class AsyncTransformProcedure<Input, Output>: Procedure, InputProcedure, OutputProcedure {
     //...
    open override func execute() {
        //...
        transform(inputValue) { self.finish(withResult: $0) }
    }
}
```
As you can see  execution of transform block is built in such way, that captures **self**  with strong reference. And if that block that is sent as second parameter is saved in subclass of AsyncTransformProcedure that would lead to retain cycle, which I exactly run into.

It can be fixed by nullifying saved block in subclass after calling it with ProcedureResult, but I'd rather change that passed block to  something like following

```
transform(inputValue) {[weak self] in self.finish(withResult: $0) }
```

What do you think?

**Comment by danthorpe** [comment]
Hmm, yeah this is a good spot. Will look into it!
