### ISSUE TITLE
Assertion failure when GroupProcedure finishing

### ISSUE THREAD

**Issue by sixten** [ProcedureKit/ProcedureKit#810]
I recently updated our dev branch to use 4.4.0 (installed via Carthage, and building using Xcode 9.1 b2), and one of the `GroupProcedure` operations in the app started producing a ProcedureKit assertion failure.  It's certainly possible that there's _also_ a bug in my code, which I'm looking over. But since this is coming from fairly deep in the library (judging by the stack trace), and in [code that was just recently added](https://github.com/ProcedureKit/ProcedureKit/commit/09386e55335b024c8e9b87bbae95c1e4d7b46fbb#diff-da6de18788222317c6a57cb3a3c2d7cfR1162), I also wanted to bring it to your attention.

The message is
```
Fatal error: Procedure hasn't finished, but procedureQueue is nil: file /Users/sotto/[redacted]/Carthage/Checkouts/ProcedureKit/Sources/ProcedureKit/Procedure.swift, line 1162
```

I'm not sure what information would be most useful to you, but I'm happy to try to capture more detail.

**Comment by swiftlyfalling** [comment]
@sixten:

1. Are you adding the GroupProcedure to a ProcedureQueue?

2. Does the error trigger consistently? Or intermittently?

3. Does the error trigger in all builds? Or just (Release / Debug / etc)?

4. Can you try replacing that fatalError with the following more descriptive error-producing code:
    ```swift
    fatalError("Procedure \"\(operationName)\" hasn't finished, but procedureQueue is nil")
    ```
    and determine whether it's your GroupProcedure that is triggering it, or one of its children? (You may need to give them names if you haven't already.)

5. Can you post a stack trace for the error?

6. Would it be possible for you to try reducing this down to a self-contained example that triggers the error and post that code?

**Comment by sixten** [comment]
1. No. In this particular case—which is the logout process for the app—we're adding it to `OperationQueue.main`. (Which, IIRC, is because the `ProcedureQueue` on which we normally schedule things gets shut down while the logout is in process, and restarted once things have been reset.) That was never an issue before, but if _that's_ the `ProcedureQueue` that the assertion isn't finding, that could explain why the other groups in the app seem to be working OK. And we might be able to rejigger things to set up a separate queue for this purpose?

2. Consistently, within a fairly small sample size (maybe ~20 runs?).

3. Have only tested so far in Debug builds.

4. I've been running it under the debugger in the simulator the last couple of times: at the point of the `fatalError`, `self` is our logout operation, which is a subclass of `GroupProcedure`.

5. The whole thing is really, really long, so [please see this attachment](https://github.com/ProcedureKit/ProcedureKit/files/1409055/stack_trace.txt).

6. I can certainly try, though most of what this code is doing is talking to other parts of the app to clear out state, reset data stores, etc. So by the time I stub all of that out, who knows whether the issue will still occur.

**Comment by swiftlyfalling** [comment]
1. Ah. So, Procedures **must** be added to a `ProcedureQueue`. This has always been the case, but there weren't always assertions surrounding it, and we'll be adding additional assertions to catch these things sooner.

Try using `ProcedureQueue.main` instead, which is the ProcedureKit equivalent of `OperationQueue.main`. That should fix this error.

**Comment by sixten** [comment]
Sorry for not closing the loop (and the issue itself) sooner! But, to confirm, switching from `OperationQueue.main` to `ProcedureQueue.main` did indeed fix the crash. Thanks!
