### ISSUE TITLE
Inheritance of AsyncBlockProcedure lead to EXC_BAD_ACCESS crash

### ISSUE THREAD

**Issue by Sander-Kornev** [ProcedureKit/ProcedureKit#813]
I'm trying to make sure that AsyncBlockProcedure is executed in the main queue. Here is the implementation

```
class AsyncBlockUIProcedure: AsyncBlockProcedure {
    override func execute() {
        if Thread.isMainThread {
            super.execute()
        } else {
            DispatchQueue.main.async {
                super.execute()
            }
        }
    }
}
```

and I'm using it like following

```
let operation = AsyncBlockUIProcedure { completionBlock in
      completionBlock(ProcedureResult.success(())) // EXC_BAD_ACCESS 
}
ProcedureQueue.main.addOperation(operation)
```

Description of completionBlock contains following 
_0x00000001050d9b80 ProcedureKit`partial apply forwarder for reabstraction thunk helper from @callee_owned (@owned ProcedureKit.ProcedureResult<()>) -> () to @callee_owned (@in ProcedureKit.ProcedureResult<()>) -> () at Block.swift_

Stacktrace image

![yfxf8z8gtzgn0mj62gfzrg](https://user-images.githubusercontent.com/3295273/34383913-59d69b2a-eb21-11e7-9818-1514fea64919.png)

What can be wrong? Any ideas?
Thanks!

**Comment by danthorpe** [comment]
Sorry for the delayed response to this issue. The recommended approach is to add such `Procedure`s to the `ProcedureQueue.main` shared instance.

However, in some cases this isn't always possible, especially if they are added inside`ProcedureGroup`s. In those cases, something like what you're doing above is not too far wrong. The problem with this approach is that using `Thread.isMainThread` is not recommended.

There is some supporting code in this project already on this topic, e.g. see [here](https://github.com/ProcedureKit/ProcedureKit/blob/development/Sources/ProcedureKit/DispatchQueue%2BProcedureKit.swift#L46). I would say that these APIs (which are effectively doing what you want to do here) are safer than what you have - but we still have some concerns that they are not fully correct. It's on our list of issues to address, if you check the issue history.

If you have more thoughts or directions for this, would love to hear them.

**Comment by danthorpe** [comment]
Hi @Sander-Kornev had a quick look into this - not exactly sure why calling `success` here is causing a EXC_BAD_ACCESS (I was able to reproduce it).

In the mean time, I've created `UIBlockProcedure` which avoids this problem - see #840. No doubt you've moved on from this issue now. Just letting you know.

**Comment by Sander-Kornev** [comment]
@danthorpe , anyway, thanks!
