### ISSUE TITLE
[Question]: Alternative to PATs for URLSession Testability protocol

### ISSUE THREAD

**Issue by ericyanush** [ProcedureKit/ProcedureKit#814]
I've been investigating the use of ProcedureKit in a fairly large application that currently uses a customized copy of the Advanced NSOperations code containing enhancements, bug fixes and unit tests.

One of the things I noticed is the use of Protocol Associated Types in the URLSessionTaskFactory protocol to enable testing of procedures that utilize networking, which in-turn forces any class/struct that contains a networking procedure to be generic. I'm finding that the generic is leaking up into group procedures that contain network procedures (sometimes several levels deep) and into other procedures that produce network procedures, none of which have any reason to be generic. 

As an alternative, does it make sense to remove the PATs from the URLSessionTaskFactory protocol, and modify it's method requirements to return URLSession*TaskProtocol instances instead? I know that this will force the extensions on URLSession and TestableURLSessionTaskFactory to contain simple wrapper methods, but in trade it would prevent the details of the network procedure testing implementation from leaking into largely unrelated classes. (Example of changes: ericyanush/ProcedureKit@11a7873b5f4822e281048a7c56287264e4e139fc)

**Comment by danthorpe** [comment]
Hi @ericyanush! This is a good question, thanks for raising it.

I think the problem of generics leaking outside of abstractions/interfaces is pretty common to Swift code up to this point. And in terms of `GroupProcedure` and needing to compose network procedures - clearly it is a bit of a problem. Your changes are fairly straightforward, and quite pragmatic & reasonable.

One question though: is there any benefit to making `GroupProcedure` generic over the `URLSession` type? Why not just define your networking procedures as `NetworkDataProcedure<URLSession>`?

My thoughts are, that the generic was primarily to allow the `NetworkDataProcedure` to be fully testable, and so to a large degree, is there much need for framework consumers to worry about passing around stubbed or testable `URLSession` classes?

**Comment by ericyanush** [comment]
There are two reasons I see for not defining the network procedures as `NetworkDataProcedure<URLSession>` within the Group procedures.

1. Limited re-usability. The approach we have taken is to sub-class the network data operation (in this case NetworkDataProcedure), providing it any request parameters in the initializer, and implementing the serialization of that data into a request in the sub-class, this affords us greater flexibility to re-use network procedures in multiple group procedures (or by themselves).

2. Testability. If a framework consumer defines their network data procedures within a group operation as the generic specialization of URLSession it makes it impossible to test the group procedure without hitting the network. In our case, we are using group procedures to encapsulate logic via conditionally producing (adding procedures to the group) depending on the result of one or more network data procedures. Testing these group operation's behaviour currently would require them to be defined as generics.

**Comment by danthorpe** [comment]
@ericyanush had a closer look at this - can see now where you're going, and totally agree. Have cherry picked your commit into PR #823.
