### ISSUE TITLE
ProcedureKit not working in Xcode 9.1

### ISSUE THREAD

**Issue by sivamoorthykutty** [ProcedureKit/ProcedureKit#815]
Hi, I have faced error in ProcedureKit how could I resolve it.
Error:
Assertion failed: Calling start() manually on a Procedure is unsupported. Instead, add the Procedure to a ProcedureQueue.:
/Sources/ProcedureKit/Procedure.swift, line 592

**Comment by danthorpe** [comment]
Hi @sivamoorthykutty, yeah, this is expected behaviour. [On the homepage](https://github.com/ProcedureKit/ProcedureKit#usage)  it says how to execute `Procedure`s in the usage section. You need to add them to a `ProcedureQueue`.
