### ISSUE TITLE
Add procedure to collect and combine results from multiple procedures

### ISSUE THREAD

**Issue by pronebird** [ProcedureKit/ProcedureKit#824]
Sometimes there is a need to collect and combine results from multiple procedures.

For example I have a procedure to fetch the app subscriptions from my server, subsequently fetch `SKProducts` and then in the end combine the results from both procedures into one.

So injection chain looks as such:

1. `FetchSubscriotionsProcedure` -> `SKProductsRequestProcedure` -> `CollectAndCombineResultsProcedure`
2. `FetchSubscriptionsProcedure` -> `CollectAndCombineResultsProcedure`

Then `CollectAndCombineResultsProcedure` may produce a single `Result<T>`. Although I must admit I have no clue how to combine the values from multiple ops into a tuple dynamically without using fixed `init()` for each of the cases, i.e 2 ops, 3 ops...

**Comment by pronebird** [comment]
I actually realized that having a non-generic procedure is cleaner given that it's pain to implement that in Swift. Too bad, stuff like `::collect` in Rust is way more powerful in that sense.

**Comment by danthorpe** [comment]
Hey @pronebird - can you actually share a bit more about what you're doing here. Really useful for me to know how you're using the framework..

**Comment by pronebird** [comment]
Alright so I have `productIdentifiers` for app subscriptions stored on my server with some metadata such as subscription plans durations.

So I download those, then inject the received `productIdentifiers` into a fetch operation that pulls the actual `SKProducts` from iTunes. However since `SKProducts` miss some of the metadata that I store on my server, I need now to combine the results from both operations.

This is very similar to how `ReverseGeocodeUserLocation` which has a dedicated `Finishing` operation to combine the received data into `UserLocationPlacemark` structure.

I thought I could make a procedure that accepts multiple operations and produces a tuple of results, however in Swift that seems to be super hard, I ended up with a class that's fixed to two operations otherwise I have no idea how to write a generic without having a proper macro support in the language.

**Comment by danthorpe** [comment]
I see, yeah. It's a bit fiddly.

So, I guess I would probably encapsulate it in a `GroupProcedure` which contains your two operations, with some sort of merge at the end. Pretty much what you're doing.

I see what you're saying now about a `::collect` process. So what is needed here, in the general case, is a `Procedure` which receives two inputs `T` and `V` and produces `U`. And sequence versions which receive `[T]` and `[V]` and produce `[U]` where you then provide the closure to do the merging for each element.

We do have a `ReduceProcedure` which assumes a sequence of `Element` and another initial type `U` (which could be a sequence of another type). So, in theory you could use this as a possible `CollectProcedure` and just massage some input types.

Probably simpler and more maintainable to use a `GroupProcedure` though and do it similar to the `ReverseGeocodeUserLocation`.

---
Thanks for sharing - might put this on my list. The framework should make plugging inputs together a bit easier.

**Comment by pronebird** [comment]
Yeah I see, there are ways but it feels like I still write a lot of code to achieve very little. :)

Btw while we are here talking about `ReverseGeocodeUserLocationProcedure`. I wonder what's the reasoning behind having a `Completion` block that accepts a `UserLocationPlacemark`, and not a `ProcedureResult<UserLocationPlacemark>`? Not really understand how do you expect error handling to happen on the developer's end. Using observers?

**Comment by danthorpe** [comment]
Hmm - that's probably a bug.
