### ISSUE TITLE
ReverseGeocodeUserLocation doesn't finish() when input is not satisfied

### ISSUE THREAD

**Issue by pronebird** [ProcedureKit/ProcedureKit#825]
It seems that `ReverseGeocodeUserLocation` while sets the `output`, never calls `finish()`.

```swift
override func execute() {

    guard let location = location.value, let placemark = placemark.value else {
        output = .ready(.failure(ProcedureKitError.requirementNotSatisfied())) // ???
        return
    }

    let userLocationPlacemark = UserLocationPlacemark(location: location, placemark: placemark)

    if let block = completion {
        DispatchQueue.main.async {
            block(userLocationPlacemark)
        }
    }

    finish(withResult: .success(userLocationPlacemark))
}
```

See https://github.com/ProcedureKit/ProcedureKit/blob/development/Sources/ProcedureKitLocation/ReverseGeocodeUserLocation.swift#L46

**Comment by pducks32** [comment]
I actually ran into this problem yesterday, this should be finish with error.

**Comment by danthorpe** [comment]
Hi @pronebird @pducks32, had a quick look into this.

Created a PR: #835, which tweaks the precondition checks in the `Finishing` procedure.

The thing is - I don't actually think this is a problem. If the `UserLocation` procedure finishes with any errors or without a location, the finishing procedure is cancelled. Likewise for the reverse GeocodeLocation.

So, if this happens... the `Finishing` procedure which collects these outputs together does not even execute, as it's cancelled before it can start.

Is there any chance you can describe how you're getting into that `execute()` function in the face of errors, no location, or no placemark?

Regardless - happy to merge some defensive coding to ensure that every code-path has a `finish()` but, just wondering how's it's even getting that procedure to execute at all.

**Comment by pronebird** [comment]
I believe I reported this issue without testing if operation ever ends up in this state.

**Comment by danthorpe** [comment]
Cool, well I've merged the PR, gonna close this for now. Thanks!
