### ISSUE TITLE
Retry procedure example for procedures that conform to the InputProcedure protocol

### ISSUE THREAD

**Issue by ArkadiYoskovitz** [ProcedureKit/ProcedureKit#827]
The wiki contains an example on how to use a ProcedureGenerator, but it dosed cover the use case for a dynamically injected input.

Any tips?

**Comment by danthorpe** [comment]
Hey @ArkadiYoskovitz - yeah, this is a good question. I think what you're asking me is... if I have a procedure, say:

```swift
final class MyProcedure: Procedure, InputProcedure {
    var input: Pending<Data> = .pending
    // etc
}
```

which I want to use as the "Payload" associated type in a `RetryProcedure` - then how do I set the `input` each time a new payload instance is created.

Good question. 🤔

---

1. The framework does not offer any built in support for making this "just work" at the moment. But I'll have a think.

2. The `RetryProcedure` `init` method essentially accepts a "retry handler" which is a closure. The closure signature is `(FailureInfo, Payload) -> Payload?` where `payload.operation` is the previous iteration's `T` type. In other words, this block receives some failure info (errors etc), and a "payload" structure, which contains the failed procedure.

    Therefore, you could set the new procedure's `.input` value here.

3. In general, I would suggest that `RetryProcedure` should be subclassed. It's not actually an abstract class, but for real-world usage, probably best to subclass it. Then you can provide a bespoke "recovery" model. See [`NetworkProcedure`](https://github.com/ProcedureKit/ProcedureKit/blob/e23387b87718785243151d98e800b711452a4dcd/Sources/ProcedureKitNetwork/Network.swift#L159) for an example.

    If you are going to subclass - then this is in some ways easier to work with, as your subclass can require that `T` conforms to `InputProcedure` and the subclass can also conform to `InputProcedure` - with matching `Input` type. Then you can pretty much just hook up your retry procedure instance in a chain and should all work fine. But this is a lot of boilerplate if you just want simple retry mechanism that `RetryProcedure` supports for free.

4. ??? Not sure if there are other options?

---

### Possible future improvement in _ProcedureKit_

I'm a huge fan of _result injection_ and of `RepeatProcedure` & `RetryProcedure` - as I think they're really powerful. So, would actually be quite interested in providing some built in support for doing option 2. Essentially, I could see this as being a specialized initializer in `RepeatProcedure` to support cases where `T: InputProcedure`. Something like...

```swift
public init<OperationIterator>(dispatchQueue: DispatchQueue? = nil, max: Int? = nil, wait: WaitStrategy = .immediate, iterator: OperationIterator) where 
OperationIterator: IteratorProtocol, 
OperationIterator.Element == T, 
T: InputProcedure // <-- this is the key additional constraint on T
{
    (_current, _iterator) = /* Setup special iterator with support for setting .input from self */
    super.init(dispatchQueue: dispatchQueue, operations: [])
}
```

`RepeatProcedure` would then need to support the same conditional API as `InputProcedure`:

```swift
extension RepeatProcedure where T: InputProcedure {

    var input: Pending<T.Input>? = .pending {
        set {
           // this is going to be a bit tricky, as we need to provide storage for a generic 
           // type, without stating what the storage type is...
        }
    }

    @discardableResult func injectResult<Dependency: OutputProcedure>(from dependency: Dependency, via block: @escaping (Dependency.Output) throws -> T.Input) -> Self {
      // etc etc
    }
}
``` 

this is a sort of mix-in, where `RepeatProcedure` itself would not conform to `InputProcedure` but, when used with the correct `T` type, it would have the same API as `InputProcedure`. Unfortunately, Swift doesn't allow us to achieve this without repeating code... but, 🤷‍♂️

Anyway, I think, this would allow for consumer code like...

```swift
let procedure = RetryProcedure { MyProcedure() } // where MyProcedure conforms to InputProtocol
procedure.injectResult(from: outputProcedure) // where outputProcedure conforms to OutputProtocol and Output == Input
```

which I think is the goal. 🤔 Just need to figure out how to store the first `.input` value.

**Comment by danthorpe** [comment]
Oh, there is actually already some support for this: See [this extension](https://github.com/ProcedureKit/ProcedureKit/blob/development/Sources/ProcedureKit/Repeat.swift#L363).

I will add appropriate APIs to make it "inject-able"

**Comment by danthorpe** [comment]
@ArkadiYoskovitz try the branch from #828. This should support what _I think_ you want.

**Comment by danthorpe** [comment]
@ArkadiYoskovitz - closing this for now.
