### ISSUE TITLE
[Question] GroupProcedure Errors

### ISSUE THREAD

**Issue by pducks32** [ProcedureKit/ProcedureKit#832]
Hi,
 I love this library and use it in every single project and it's great. I have a question about cancelling vs. finishing.

It's based on real code but because it's my company's proprietary code I have copy pasted the code and errors and just changed the names of the procedures. So given an Input/Output Procedure of the form `Procedure<Input, Output>`, the layout is:
* `DownloadUserAvatarByTheirIDProcedure<UserID, Void>`
   *  `DoesntMatterProcedure<UserID, URL>`
   *  `DownloadAvatar<URL, URL>`
   *  `mapOutputOfDownloadToGroupsOutput<URL, Void>`

```swift
let mapOutputOfDownloadToGroupsOutput = TransformProcedure<URL, Void> { url in
  self.output = .ready(.success(url))
  self.finish()
}
```

I use this pattern a lot until today I realized that `DownloadAvatar ` was `finish(withError: anError)`-ing and yet my `GroupProcedure` didn't seem to care.

Output is:
```
DownloadUserAvatarByTheirIDProcedure: DownloadAvatar did encounter 1 errors.
DownloadUserAvatarByTheirIDProcedure: TransformProcedure did encounter 1 errors.
```

I thought that `GroupProcedure`s would _bubble_ child errors but I guess that doesn't make sense. So I want to ask, what do you believe is the best way to make sure that the Group errors out?

In your `ReverseGeocode` example you have a separate class which I like but I will be honest I write a lot of these and that level of boilerplate would probably kill me. I much rather just do everything in a custom `init` in my  `GroupProcedure`.

Thanks, also I'd like to add this info back to a doc somewhere in case others run into this so where is the best place for that? The docs I use the most are just sifting though the code which to be honest sucks. Thanks,

**Comment by danthorpe** [comment]
Hi @pducks32,

Well, `GroupProcedure` automatically handles _cancellation_ but not _errors_. In your subclass (`DownloadUserAvatarByTheirIDProcedure`) you would need to add some support to deal with errors from children. There are a couple of way to do this.

Firstly, I'd recommend reading these docs, from http://procedure.kit.run/development/index.html
- [Handling Cancellation](http://procedure.kit.run/development/handling-cancellation.html)
- [Groups](http://procedure.kit.run/development/groups.html)
- [GroupProcedure](http://procedure.kit.run/development/Classes/GroupProcedure.html) (this is the autogenerated class doc)

From your question, what is not entirely clear is how you might want to handle the errors, do you want to:

1. Not finish with any errors in the group?
2. Finish with errors in the group, but still set it's output as "success" (what you have at the moment)
3. Finish with errors in the group, and not set the output.

The most straightforward way to handle errors from child procedures is to override [child(_:willFinishWithErrors:)](http://procedure.kit.run/development/Classes/GroupProcedure.html#/s:12ProcedureKit05GroupA0C5childyAA0A0C_Says5Error_pG20willFinishWithErrorstF) and do something with the error. In this method you can check which child is going to error, and then essentially "recover" from it. How to do this?

1. One option is to append the error to the group's errors array and nothing else. This is the default behaviour - and it means that the group keeps executing, but ultimately will finish with errors.
2. You could _not_ add the error to the group's errors array, and continue - so the group will finish, but will not have this error (i.e. it would be considered to finished with success).
3. You could append the error to the group's errors array, and then cancel the group - which would mean that the child procedures cancel
4. You could append the error to the group's errors array, and then finish the group - which would mean that the child procedures do not start

The difference between options 3 & 4 is subtle - and it only really impacts the child procedures. For example you might observers on them for cancellation maybe.

--- 

We could also avoid the `TransformProcedure` entirely and use a block observer to set the group's output.

```swift
final class DownloadUserAvatarByTheirIDProcedure: GroupProcedure {
 
    let first: GetURLFromUserId

    var input: Pending<UserId> = .pending {
        didSet { first.input = input }
    }
    var output: Pending<Result<URL>> = .pending

    init() {

        // DoesntMatterProcedure<UserID, URL>
        first = GetURLFromUserId

        // DownloadAvatar<URL, URL>
        let download = DownloadAvatar()

       download.injectResult(from: first)
       super.init(operations: [first, download])

        download.addDidFinishBlockObserver { [weak self] procedure, errors in 
            // inspect errors here to set the group's output
             self?.output = .ready(.success(procedure.url))
        }
    }
}
```

Alternatively, depending on how you wanted to handle any errors from the Download (i.e. to suppress them) - you could do all of this in the `child(_:willFinishWithErrors:)` over ride too.

If you want to "suppress" the errors from the download procedure, you could also do this:

```swift
final class DownloadUserAvatarByTheirIDProcedure: GroupProcedure {
    // etc

    init() {

        // DoesntMatterProcedure<UserID, URL>
        first = GetURLFromUserId

        // DownloadAvatar<URL, URL>
        let download = DownloadAvatar()
       download.injectResult(from: first)

        let ignoredErrors = ComposedProcedure(download)
        ignoredErrors.transformChildErrorsBlock = { _, errors in 
             errors = []
        }

       super.init(operations: [first, ignoredErrors])
    }
}
```

I might actually create a convenience `IgnoredErrorsProcedure` for this.

**Comment by swiftlyfalling** [comment]
> 4. You could append the error to the group's errors array, and then finish the group - which would mean that the child procedures do not start

@danthorpe: GroupProcedure always handles finishing itself, once all of its children finish. There is no way to finish a group besides ensuring all of its children finish (there are a bunch of reasons for this, including proper management of its internal ProcedureQueue), so 4 really is just 3 (cancel the children if you want the Group to finish).

**Comment by pducks32** [comment]
Hey thanks so much Dan. I'm looking into how best to make it work. I think canceling the group seems to be the best approach and overriding that errors delegate method to append the errors to the Group's errors. 

You said 

> I might actually create a convenience IgnoredErrorsProcedure for this.

By this same logic I made a group procedure subclass that has a property in it's init that allow it to listen to it's children's errors and do what I want above. Maybe that would be a good subclass for this library.

**Comment by swiftlyfalling** [comment]
@pducks32: GroupProcedure _should_ be automatically aggregating the errors from children. (i.e. Errors from children should be appended to the Group's errors.) Is that not happening?

If you are looking for additional behavior _beyond_ that, such as "cancelling other child Procedures if one of them errors", you'll need to use additional code. (The framework has a few options built-in - if the child Procedures are in a dependency chain, you can use `NoFailedDependenciesCondition`.)

**Comment by danthorpe** [comment]
Gonna close this for now.

@pducks32 - see `IgnoreErrorsProcedure` in the `development` branch.
