### ISSUE TITLE
Overlooked simple ProcedureQueue issue?

### ISSUE THREAD

**Issue by StephenDaedalus** [ProcedureKit/ProcedureKit#852]
Using `queue.addOperations([auth], waitUntilFinished: true)` does not seem to work on a `ProcedureQueue`.

Here's a simple example:

```swift
let queue = ProcedureQueue()
queue.maxConcurrentOperationCount = 1
        
let auth = GetAuthorizationStatusProcedure(Capability.CloudKit())
queue.addOperations([auth], waitUntilFinished: true)

if auth.output.isPending {
    print("Pending")
} else {
    if let error = auth.output.error {
        print("Error received: \(error)")
    }
    if let tuple = auth.output.success {
        print("Boolean value: \(tuple.0) status: \(tuple.1)")
    }
}
```

It works if you change it to this:

```swift
queue.addOperation(auth)
queue.waitUntilAllOperationsAreFinished()
```

**Comment by danthorpe** [comment]
Hi @StephenDaedalus 

In Dave De Long's original source code, the override of this method triggered a `fatalError` which we (eventually) removed from _ProcedureKit_. However, as our documentation shows, we still feel that it's an anti-pattern to set `waitUntilFinished` is true, as it is never needed to block the queue.

See the method documentation: https://github.com/ProcedureKit/ProcedureKit/blob/0b2841404f51b10b9c5b6e7416b69a4f45e07d5e/Sources/ProcedureKit/ProcedureQueue.swift#L239

However, I can see that this is not as obvious or discoverable as it might be. We could make this a compile time switch, which has previously be discussed as an option. 🤔

---

Also, not sure if your code sample is just a throw-away sample, but the way that you're using `GetAuthorizationStatusProcedure` and then querying the `output` property on a blocked queue is not the way to do this.

Instead, use perhaps use an observer, for example:

```swift
let auth = GetAuthorizationStatusProcedure(Capability.CloudKit())
auth.addDidFinishBlockObserver { (auth, errors) in
    guard let status = auth.output.success else {
        print("Error received: \(error)"); return
    }

    print("CloudKit enabled: \(status.0), status: \(status.1)")
}

queue.addOperation(auth)
```

Or, if you want to do another task after getting back the authorization status, consider using dependencies, result injection, or the `AuthorizedFor<>` condition as option. 

You can wrap `AuthorizedFor` using combinations of `NegatedCondition` and `SilentCondition` to silently check for  the authorization state of capabilities to then show UI to prime the user for a system authentication alert.

For example, something like this:

```swift
// lets assume you have a procedure
let showCloudKitAuthenticationPrimer = PresentViewControllerWithStoryboard(.explainCloudKitPermissionRequest)

// Attach a condition which silently checks for not-authorized state
let condition =  NegatedCondition(SilentCondition(AuthorizedFor(Capability.CloudKit())
showCloudKitAuthenticationPrimer.add(condition: condition)

ProcedureQueue.main.addOperation(showCloudKitAuthenticationPrimer)
```

**Comment by StephenDaedalus** [comment]
Thanks very much for your comment. I appreciate the history via Dave De Long. I was not intending to use waitUntilFinished but stumbled upon the issue while doing some testing. A agree that the observer is the correct way to go.

More background: I am unable to use ProcedureKit in the latest production version of Xcode, i.e. 9.4.1 due to the fact that it uses Swift 4.1 and most of the CloudKit functionalities are #defined from being able to be used. If uncommented, those sections result in a segmentation violation in Xcode due to the following: `    public var output: Pending<ProcedureResult<CKRecord>> = .pending
`.  Is there a different version I should be using other than development? Even the Swift 4.1 tag contains the #define.

**Comment by danthorpe** [comment]
Hey @StephenDaedalus - there are breaking changes, but have you tried using the `development` branch?

The _ProcedureKitCloud_ module has linking issues in Xcode 10, and has had some issues in Xcode 9 / Swift 4.1.

Which CK procedures do you use?
