### ISSUE TITLE
Abort trap: 6 Issue with ComposedProcedure

### ISSUE THREAD

**Issue by StephenDaedalus** [ProcedureKit/ProcedureKit#856]
Running in Xcode 10 with Swift 4.2 against the OPR-853_cloud_kit_xcode_10 that was created over the weekend. Experienced this issue with Xcode 9.4.1 with Swift 4.1 as well. 

Instructions: 

Create a new workspace with the ProcedureKit frameworks
Create a new single-view project
Add the attached file and attempt to compile it. 

You'll see an Abort trap: 6 with a lengthy trace. The last lines are:

'
[CloudFetchUserRecordOperation.swift.zip](https://github.com/ProcedureKit/ProcedureKit/files/2109567/CloudFetchUserRecordOperation.swift.zip)

1.	While serializing 'CloudFetchUserRecordOperation' in module 'Simplified'
2.	While loading conformances for 'CloudFetchUserRecordOperation' in module 'Simplified'
3.	While reading inherited conformance for type 'CloudFetchUserRecordOperation'
4.	While reading specialized conformance for type 'ComposedProcedure<CloudKitProcedure<CKFetchRecordsOperation>>'
5.	While reading inherited conformance for type 'CloudKitProcedure<CKFetchRecordsOperation>'
6.	While reading specialized conformance for type 'RepeatProcedure<CKProcedure<CKFetchRecordsOperation>>'
7.	While reading inherited conformance for type 'CKProcedure<CKFetchRecordsOperation>'
8.	While reading specialized conformance for type 'ComposedProcedure<CKFetchRecordsOperation>'
'

**Comment by danthorpe** [comment]
Hi @StephenDaedalus,

This works fine for me:

```
import Foundation
import CloudKit

import ProcedureKit

final class FetchUserRecord: GroupProcedure, OutputProcedure {

    var output: Pending<ProcedureResult<CKRecord>> = .pending

    init(container: CKContainer = .default()) {

        let cloud = CloudKitProcedure { CKFetchRecordsOperation.fetchCurrentUserRecordOperation() }
        cloud.container = container
        cloud.database = container.publicCloudDatabase

        super.init(operations: [cloud])

        cloud.setFetchRecordsCompletionBlock { [weak self] (recordsByID) in
            guard let userRecord = recordsByID?.first else { return }
            self?.output = .ready(.success(userRecord.value))
        }

        add(condition: MutuallyExclusive<FetchUserRecord>())
        add(condition: AuthorizedFor(Capability.CloudKit()))
    }
}
``` 

Make sure you're using branch `xcode/10.0/development` and that you're compiling everything in Swift 4.2 mode.

**Comment by StephenDaedalus** [comment]
I’ll retry right away. Thanks again.

**Comment by StephenDaedalus** [comment]
I can confirm your FetchUserRecord procedure does work fine. I don't understand the complexities of the ComposedProcedure I had been using - since your example is simpler and accomplishes the same thing. Closing this for now.

**Comment by danthorpe** [comment]
@StephenDaedalus yeah, your `ComposedProcedure` sample, probably should have worked, but, overall it isn't really needed.

`ComposedProcedure` is sort of a niche `GroupProcedure` subclass, which is good for cases where you don't want to wrap an `NSOperation` class which you don't own. i.e. 

```swift
queue.add(operation: ComposedProcedure(operation: SomeOtherOperation()))
```

I should probably make `ComposedProcedure` `final`, as in general it should not be subclassed.

In this case, because we are using `CloudKitProcedure` it is already wrapping the `CKOperation` in a `Procedure` so there is really no need to wrap it again. Instead we just want to compose it.

**Comment by danthorpe** [comment]
Hey @StephenDaedalus, responding to your comments on Slack... you could augment this procedure like this:

```swift
final class FetchUserRecord: GroupProcedure, OutputProcedure {

    typealias FetchCloudRecordProcedure = CloudKitProcedure<CKFetchRecordsOperation>
    typealias ConfigureBlock = CloudKitRecovery<CKFetchRecordsOperation>.ConfigureBlock
    typealias Recovery = CloudKitRecovery<CKFetchRecordsOperation>.Recovery

    let cloud: FetchCloudRecordProcedure

    var output: Pending<ProcedureResult<CKRecord>> = .pending

    init(container: CKContainer = .default()) {

        cloud = CloudKitProcedure { CKFetchRecordsOperation.fetchCurrentUserRecordOperation() }
        cloud.container = container
        cloud.database = container.publicCloudDatabase

        super.init(operations: [cloud])

        cloud.setFetchRecordsCompletionBlock { [weak self] (recordsByID) in
            guard let userRecord = recordsByID?.first else { return }
            self?.output = .ready(.success(userRecord.value))
        }

        cloud.set(errorHandlerForCode: .badDatabase) { (fetchRecordsOperation, fetchRecordsError, logger, recovery) -> Recovery? in
            // Handle "bad database error here"..

            // The provided recovery is the suggested `Delay` parameter, and the current configure block.
            let (suggestedDelay, currentConfigureBlock) = recovery

            // Return a tuple of the same type, adding any specific additional configuration.
            let updatedConfigureBlock: ConfigureBlock = { wrappedCloudKitOperation in

                // First call the current configure block - this will reset existing configurations
                // such as the container etc.
                currentConfigureBlock(wrappedCloudKitOperation)

                // Do any new configuration here, depending on how you want to adjust the operation
                // in light of the error. Read CloudKit docs for tips on how to handle specific errors

                // For example, maybe change the database?
                wrappedCloudKitOperation.database = container.privateCloudDatabase
            }

            // Now return this tuple. CloudKitProcedure will take this, and apply
            // the updated configuration to a new CKFetchRecordsOperation instance, and
            // execute it.
            return (suggestedDelay, updatedConfigureBlock)
        }

        add(condition: MutuallyExclusive<FetchUserRecord>())
        add(condition: AuthorizedFor(Capability.CloudKit()))
    }

    // If the CloudKitProcedure encounters an error, and there is no error handler set for
    // it, then it will finish with an error. Override the GroupProcedure method here to 
    // catch this, and set it on the output.
    override func child(_ child: Procedure, willFinishWithErrors errors: [Error]) {
        defer { super.child(child, willFinishWithErrors: errors) }
        guard child == cloud, let error = errors.first else { return }
        output = .ready(.failure(error))
    }
}
```

Bu default, `CloudKitProcedure` will automatically retry another instance of the `CKOperation` as is for all of the network errors - you do not need to do anything.

**Comment by StephenDaedalus** [comment]
This is great! I'll have to study it a bit more closely but if there's anything that's missing from the ProcedureKit framework is more current sample code with reference implementation examples. I mentioned before that I'd be happy to throw in a few of my classes just to see how they stack up.

One thing I discovered is that if you add the AuthorizedFor(Capability.CloudKit()) condition on the lower-level 'cloud' operation instead of on the FetchUserRecord GroupProceudre, you'll be able to pick up the error in the child willFinishWIthErrors method. It helps to localize failures. Not sure if you'd agree with that approach.
