### ISSUE TITLE
`Condition.willAttach(to:)` needs to be `open`

### ISSUE THREAD

**Issue by kdubb** [ProcedureKit/ProcedureKit#866]
Otherwise a custom condition outside of ProcedureKit cannot add dependencies to the operation is attaches to; or at least I cannot figure how one would do that.

**Comment by danthorpe** [comment]
Hi @kdubb,

Well, `Contition` has APIs for adding dependencies which should be used, see: https://github.com/ProcedureKit/ProcedureKit/blob/development/Sources/ProcedureKit/Condition.swift#L320

It's best to call these as part of the initialiser in your `Condition` subclass. There is an example here: https://github.com/ProcedureKit/ProcedureKit/blob/eeba2978be99442a786a8c78b58c64b2b50c08ef/Sources/ProcedureKit/Capability.swift#L260

Does that help?

**Comment by danthorpe** [comment]
Gonna close this for now - @kdubb re-open if you need to.
