### ISSUE TITLE
Adding operations to the "middle" of a GroupProcedure

### ISSUE THREAD

**Issue by sixten** [ProcedureKit/ProcedureKit#871]
We have a case in our app where we're using a `GroupProcedure` for a bundle of processing that always starts and ends the same way, but has some variability in the middle. The way we've been handling this has _mostly_ been working:

1. In the group's initializer, create the **Start** and **End** operations. Make **End** dependent on **Start**. Call super with those two operations.
1. Add a **MoreWorkObserver** to **Start** that may, in `will(finish:withErrors:)`, create a new **Middle** procedure, and call `start.produce(operation: middle)`. (Each **Middle** thus created also gets a **MoreWorkObserver**, so this may continue to chain.)
1. The group overrides `groupWillAdd(child:)`, and makes **End** dependent upon each new **Middle** procedure.

Sometimes—not often—this crashes because the **End** operation has started to execute at the point where we're trying to add a new dependency. I assume that this is because there's some asynchrony between the point where produce is called, and the point where the group hears about the new operation. Enough that that the **Middle** can finish finishing, and **End** starts up.

**Is there a better way (read: safe, but still idiomatic) to implement this pattern?**

One alternative I've considered, but which seems pretty heavyweight, would be to make this two nested groups: the inner group would have Start, and any Middle procedures it produced, while the outer group would contain the inner group and End. (I'm presuming that the way that `GroupProcedure` handles adding dependencies on its internal `CanFinishGroup` doesn't suffer from the race I'm running into here.)

Another alternative might be to move the code from the MoreWorkObserver to the group's `child(_:willFinishWithError:)`, and add the dependency to End and enqueue the new procedure directly, rather than going roundabout through `produce(operation:)`. That seems safely synchronous, at the cost of more directly coupling the group to the operations it contains.

**Comment by danthorpe** [comment]
Hi @sixten this is a great question.

Okay, so.... your approach is an interesting one. If I was doing this, I would just override `child(_:willFinishWithError:)` and use this to add a new child and add additional dependencies.

But your method, is effectively doing the same thing, as `produce()` adds the new operation to the receiver's queue - which is the group's queue in this case. So the question is, why isn't it working reliably 100% of the time? 

*Would you be able to share your observer code?* You should have something which is a bit like this, I think:

```swift
class MoreWorkObserver: ProcedureObserver {

    var finalDependency: Procedure?

    func will(finish procedure: Procedure, with: Error?, pendingFinish: PendingFinishEvent) {
        // Business logic to determine whether to add a new procedure
        guard shouldAddNewProcedure() else { return }

        // Create a new procedure
        let newMiddle = MiddleProcedure()
        finalDependency?.addDependency(newMiddle)
       newMiddle.addObserver(MoreWorkObserver())

       // Produce new procedure using the pending finish event
       // This guarantees that the new operation is produced before the receiver finishes.
      procedure.produce(operation: newMiddle, before: pendingFinish)
    }
}
```

Take a look at the PR which added the internal event queue: https://github.com/ProcedureKit/ProcedureKit/pull/668 this usage case is an example.

---

Now all of this is a little tricky, we've got a custom observer, which sort of recursively does some business logic and then decided whether to add a new procedure (of the same type) and then it has to handle all of the "boilerplate" to keep all of the dependencies in order. Surely there is a better way?

What about using a `RepeatProcedure`? It would work something like this:

```swift
class StartMiddleEndGroup: GroupProcedure {
   init() {
        let start = StartProcedure()
        let middle = RepeatProcedure { 
             guard shouldAddNewProcedure() else { return nil }
             return Middle()
        }
        middle.addDependency(start)
        let end = EndProcedure()
        end.addDependency(middle)
        super.init(operations: [start, middle, end])
   }
}
```

Depending on the logic for figuring out whether you have a new `Middle()` or not just needs to be expressed as either:
1. a `() -> Middle?` closure (as in this example above)
2. or, an `Iterator` with `Middle` associated element type.

Then `RepeatProcedure` will essentially do all of the housekeeping for you. It will schedule a new instance of your procedure, execute it, and keep itself alive until the iterator runs out.

This makes your code so much easier to read and understand, as your `EndProcedure` just depends on the `RepeatProcedure`.

**Comment by sixten** [comment]
Tackling the first part first: the gist of the observer matches what you've sketched, with a couple of differences:

1. The code in the production app does its evaluation and production in a Core Data `performAndWait` block. But I've also tried moving the call to produce outside of the block (in case the calling queue was significant) and seen the same failure.
1. I'm _not_ currently passing the `PendingFinishEvent` to produce (I think the code was written before that parameter was introduced?). This may be my entire problem?
1. Your version adds the dependency to **End** _before_ calling produce, which seems certain to prevent the issue I'm seeing. Our code does that in the group's `groupWillAdd(child:)` method. (In principle, there's no reason why the **Middle** operations should know anything about **End**.)

I'll be back for the design questions, but first let's see whether my problem is actually a really silly bug in my code!

```swift
  // MoreWorkObserver, somewhat simplified
  func will(finish procedure: Procedure, withErrors errors: [Error], pendingFinish: PendingFinishEvent) {
    guard !procedure.isCancelled && !procedure.failed else { return }
    guard let op = procedure as? Middle else { return }

    var nextOperation: Procedure?
    op.managedObjectContext.performAndWait {
      // ... check some stuff, set nextOperation or not ...
    }
    
    if let nextOperation = nextOperation {
      try! procedure.produce(operation: nextOperation)
    }
  }

  // StartMiddleEndGroup
  override func groupWillAdd(child: Operation) {
    if child is Middle {
      end.addDependency(child)
    }
    super.groupWillAdd(child: child)
  }
```

**Comment by danthorpe** [comment]
Hi @sixten yeah, I would definitely update this to pass through the `pendingFinish` parameter to the `produce` call - that may fix the issue.

I _think_ adding the dependency via `groupWillAdd(child:)` is okay...

**Comment by danthorpe** [comment]
@swiftlyfalling - any thoughts on this?

**Comment by sixten** [comment]
Well, I'm cautiously optimistic that changing how we're calling `produce(operation:)` has fixed the proximate cause of our issue. (It's never been something we can 100% reliably reproduce, but we haven't seen it since making that change.)

As far as using a `RepeatProcedure` as a way to implement the logic of adding an uncertain number of **Middle** operations: that's definitely an interesting idea. The one potential issue I see is that our logic for figuring out whether there's another **Middle** depends on the response from the previous one (or, in the initial case, the **Start**). That's the primary reason we're using the will-finish event now. It doesn't seem like there's a ready way for the logic in the `RepeatProcedure` to see the outcome of the previous iteration.

**Comment by danthorpe** [comment]
Hi @sixten - well good to hear that using the `pendingEvent` property has likely fixed the race condition. 👍 

----

Deciding whether to continue repeating based on a result of the previous operation, is certainly possible. `RepeatProcedure` can be initialized using anything conforming to `IteratorProtocol`. So it would certainly be possible to create your own iterator:

```swift
protocol Repeatable {

    /// Determines whether or not a subsequent instance of the
    /// receiver should be executed.
    ///
    /// - Returns: a Bool, true to indicate that another instance should be executed.
    func shouldRepeat() -> Bool
}

struct RepeatableIterator<Element: Repeatable>: IteratorProtocol {

    private var iterator: AnyIterator<Element>
    private var latest: Element?

    init<I: IteratorProtocol>(_ base: I) where I.Element == Element {
        iterator = AnyIterator(base)
    }

    mutating func next() -> Element? {
        if let latest = latest {
            guard latest.shouldRepeat() else { return nil }
        }
        latest = iterator.next()
        return latest
    }
}
```

It's important to make sure that the implementation of `shouldRepeat()` is thread safe.

Indeed support for this protocol actually already exists in _ProcedureKit_ although I have marked it as deprecated in a bid to reduce the API surface area - see: https://github.com/ProcedureKit/ProcedureKit/blob/04e33cb83dc158ea926ded602a4f072d8cb24346/Sources/ProcedureKit/Repeat.swift#L329

**Comment by danthorpe** [comment]
Gonna close this as resolved now.
