### ISSUE TITLE
Command line application

### ISSUE THREAD

**Issue by altab-ch** [ProcedureKit/ProcedureKit#872]
Is there any way to add this framework to a command line application ?

I tried different ways but still get :

> dyld: Library not loaded: @rpath/libswiftCore.dylib
  Referenced from: /Users/****/Library/Developer/Xcode/DerivedData/TestProcedureKit-bvthfxsvvstphsaqrqphdvgtxzqu/Build/Products/Debug/ProcedureKit.framework/Versions/A/ProcedureKit
  Reason: image not found

**Comment by danthorpe** [comment]
Hi @altab-ch, how are you setting up the command line application?

**Comment by altab-ch** [comment]
Hi danthorpe,

As explained in your installation guide, I tried to drag and drop the project and tried to install through cocoapods. I did not try to setup anything else in the command line app.
I also tried to install the framework in a regular Cocoa app and it is working fine.

I guess I should configure additional stuff to make this framework work in a command line app.

Best regards,

**Comment by altab-ch** [comment]
Additional information:

When I add the framework through cocapods, I get a warning:

> Not running swift-stdlib-tool: ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES is enabled, but the product type 'Command-line Tool' is not a wrapper type

After googling, it seems a bit tricky to solve.

**Comment by danthorpe** [comment]
Hi @altab-ch - well, it certainly has worked before, because we added `TaskProcedure` in _ProcedureKitMac_ explicitly for command line applications. But, admittedly we don't have integration tests for a command line app.

I will try to look into it, and see what the situation is. Sorry I can't provide a definitive answer right now 😔

**Comment by danthorpe** [comment]
Hi @altab-ch - not sure if you're still working on command line applications, but this open source project might help you out: https://github.com/CIKit/Buildkite
