### ISSUE TITLE
NetworkProcedure input

### ISSUE THREAD

**Issue by pronebird** [ProcedureKit/ProcedureKit#876]
Hi,

I use `NetworkProcedure` to improve networking in my app, and basically I found that it's a little limiting when it comes to passing `input` into iterator block, since `NetworkProcedure` does not implement `InputProcedure`.

Simple scenario:

1. Generate `URLRequest`
2. Spin off `NetworkProcedure` with `NetworkDataProcedure` factory

Now in my case it's impossible to create `URLRequest` inside of iterator body passed to `NetworkProcedure` because my code may `throw` errors when creating `URLRequest`. It seems that it's possible to return `nil` from the `NetworkProcedure`'s body, but then the error is swallowed in that case.

So in order to propagate any `URLRequest` creation errors, I've used an intermediate `ResultProcedure` and `addWillAddOperationBlockObserver` to provide the input to newly created `NetworkDataProcedure`:

```swift
let createRequestProcedure = ResultProcedure { [weak self] () throws -> URLRequest in
    if let value = self?.input.value { // grab input from custom GroupProcedure subclass
        return try requestBuilder(value)
    } else {
        throw ProcedureKitError.requirementNotSatisfied()
    }
}

let networkProcedure = NetworkProcedure {
    NetworkDataProcedure(session: URLSession.shared) // pending input
}

networkProcedure.add(dependency: createRequestProcedure)

networkProcedure.addWillAddOperationBlockObserver { (networkProcedure, dataProcedure) in
    if let procedure = dataProcedure as? NetworkDataProcedure<URLSession>, 
       let value = createRequestProcedure.output.success {
        procedure.input = .ready(value) // fill in the input
    }
}
```

Is this safe to do? Thoughts on improving `NetworkProcedure`?

**Comment by pronebird** [comment]
@danthorpe 

Awesome! 👏 

I was a little concerned that I have to fiddle with `input` in such way. I am still on 4.5, so I guess once v5 is out, I'll migrate my code and streamline my operations even further.

**Comment by danthorpe** [comment]
@pronebird yeah, it's kinda sucked that the gap between v4.5 -> v5 has been so long. It's been a number of reasons (sorry!) - but we're almost there now. 🚀

If you are able to try your project with `development` and give me some feedback about what looks to be broken - that would be really helpful! 🙌 

One of the things which changed very soon after v4.5 was the removal of the associated type from the `Network*Procedure` classes - this was the first breaking change which necessitated v5 instead of v4.6.

**Comment by pronebird** [comment]
@danthorpe I'll give it a try 👍

**Comment by pronebird** [comment]
Just had a chance to migrate to v5.0.0-beta1. `NetworkProcedure` seems to proxy the injected result into `NetworkDataProcedure` returned from iterator. 👍 

```
let createRequestProcedure = ResultProcedure { [weak self] () throws -> URLRequest in
    if let value = self?.input.value {
        return try requestBuilder(value)
    } else {
        throw ProcedureKitError.requirementNotSatisfied()
    }
}

let networkProcedure = NetworkProcedure {
    NetworkDataProcedure(session: URLSession.shared)
}.injectResult(from: createRequestProcedure)

let parsePayloadProcedure = TransformProcedure { (payload) throws -> Output in
    let decoder = JSONDecoder()
    decoder.dateDecodingStrategy = .formatted(DateFormatter.iso8601Full)
    return try decoder.decode(Output.self, from: payload)
}.injectPayload(fromNetwork: networkProcedure)

parsePayloadProcedure.addWillFinishBlockObserver { [weak self] (parseProcedure, error, _) in
    if error != nil {
        return
    }
    
    if let value = parseProcedure.output.value {
        self?.output = .ready(value)
    }
}

addChildren([createRequestProcedure, networkProcedure, parsePayloadProcedure])
```
