### ISSUE TITLE
Cannot create a CloudKitProcedure with let operation CKQueryOperation, get Generic Parameter error

### ISSUE THREAD

**Issue by imrabti** [ProcedureKit/ProcedureKit#883]
I want to configure a CloudKitProcedure which calls a CKQueryOperation, but I can't succeed I have a Swift compilation error, below is the code I use :

`let operation = CloudKitProcedure { CKQueryOperation(query: CKQuery(recordType: "Products", predicate: NSPredicate(value: true))) }`

I get an error "Generic Parameter 'T' couldn't be inferred"

Did I write something wrong, I have used CloudKitProcedure with a CKModifyRecordZone it worked good, but with this one it doesn't.

**Comment by danthorpe** [comment]
Hi @imrabti, your code looks fine at first glance. 

Can you confirm what version/hash of ProcedureKit you are using & platform version too. Thanks.

**Comment by imrabti** [comment]
Hi @danthorpe, thank you for the fast answer, and for the outstanding framework you offer us.

Here is the hash of ProcedureKit I'm using : 57b3de53e06694fb44a3211c35b9df89dfe226b2
I'm on the development branch, and for the platform it is on iOS 11.4.

I hope the details I provided are enough.

**Comment by danthorpe** [comment]
Thanks @imrabti - but, that hash is not recognised/valid - see: https://github.com/ProcedureKit/ProcedureKit/commit/57b3de53e06694fb44a3211c35b9df89dfe226b2 ??

Can you try your project again using the `5.0.0-beta.1` tag? See: https://github.com/ProcedureKit/ProcedureKit/releases/tag/5.0.0-beta.1

Also, if you're using the Xcode 10 Beta - I still have some changes from https://github.com/ProcedureKit/ProcedureKit/pull/855 to resolve into `development` and v5 before it is _final_. There are changes here related to CloudKit stuff. Now that the Xcode 10 GM seed is here, this should hopefully all get resolved this coming weekend.

**Comment by danthorpe** [comment]
Just refreshing my memory on the `CKQueryOperation` support - I think in the changes in Swift 4.1 and development branches of Swift, that support for CKQuery in `CloudKitProcedure` was not immediately possible. This is why the file has `#if !swift(>=4.1)` at the top of it.

And that is why you're seeing the compile time error, because `CKQueryOperation` does not conform to the required protocols that `CloudKitProcedure` needs.

Now that the GM is here, I can re-visit this. I think (looking at the test suite) that `CKQueryOperation` was the only cloud kit operation which I could not get working when I last looked at this when Xcode 9.4 came out.

**Comment by imrabti** [comment]
I’m currently using XCode 9, I’ll switch to that Tag and give it a try. Hopefully everything will work smoothly. 

In my cocoaPod I have import ProcedureKit as described below : 
pod 'ProcedureKit/All', :git => 'https://github.com/ProcedureKit/ProcedureKit.git', :branch => 'development'

Is it the good way to integrate it ?

**Comment by imrabti** [comment]
If the issue fixed with XCode 10 and Swift 4.2, I can also move to that.

**Comment by danthorpe** [comment]
Yeah, that is mostly fine. Once 5.0 is _done_ (which should not be long now - just need to finish of Xcode 10 stuff) then you can switch to semantic versioning with:

```ruby
pod 'ProcedureKit/All', '~ 5.0'
```

**Comment by imrabti** [comment]
Ok great, I’ll try with Xcode 10, I need to migrate my application anyway to that.

**Comment by danthorpe** [comment]
Wise move - its out of Beta now. If you have any other migration issues with PK - it would be super great if you could create a new issue in this project 😊

**Comment by imrabti** [comment]
Thank you, I need your opinion on a use case I use PK in to handle CloudKit record zone operation.

**Comment by imrabti** [comment]
After updating to Swift to 4.2 and XCode 10 this works smoothly.
