### ISSUE TITLE
CKFetchRecordZoneChangesOperation zoneChangeToken block is not called to get the new value of ServerToken

### ISSUE THREAD

**Issue by imrabti** [ProcedureKit/ProcedureKit#886]
I'm using CKFetchRecordZoneChangesOperation with CloudKitProcedure, but I have an issue to get the new ServerToken value, I have used the block recordZoneChangeTokensUpdatedBlock to intercept the new ServerToken, but it is never called.

I have attached below the code I use : 

```swift
private func createRecordChangesOperation(fetchOption: CKFetchRecordZoneChangesOperation.ZoneOptions, finishOperation: BlockProcedure) -> Procedure {
    let optionsByZone = [recordZoneId: fetchOption]        
    let operation = CloudKitProcedure { CKFetchRecordZoneChangesOperation(recordZoneIDs: [self.recordZoneId], optionsByRecordZoneID: optionsByZone) }
    operation.database = database
    operation.qualityOfService = self.qualityOfService
        
    operation.recordChangedBlock = { record in
        self.mergeGroupOperation.addChild(MergeOperation(record))
    }
        
    operation.recordWithIDWasDeletedBlock = { recordId, recordType in
        self.deleteGroupOperation.addChild(DeleteOperation(recordId))
    }

    operation.recordZoneChangeTokensUpdatedBlock = { recordZoneId, newToken, clientToken in
        if let serverToken = newToken {
            self.serverToken = serverToken
            Defaults[.serverToken] = NSKeyedArchiver.archivedData(withRootObject: serverToken)
        }
    }
        
    operation.setFetchRecordZoneChangesCompletionBlock {
        self.queue.addOperations([self.mergeGroupOperation, self.deleteGroupOperation, finishOperation])
    }
        
    return operation
}
```

**Comment by danthorpe** [comment]
Is the operation definitely being called? I'm a little worried about this bit which is adding operations to a queue inside a completion block of another operation.

**Comment by imrabti** [comment]
Yes It is the operation is called, it is added to queue, the Block **setFetchRecordZoneChangesCompletionBlock**  is called and both GroupProcedure **mergeGroupOperation** and **deleteGroupOperation** are also executed.

**Comment by danthorpe** [comment]
Hmm, there might be an issue with the type mapping of `ZoneOptions` in this class - I didn't know this. But `ZoneOptions` has been renamed to `ZoneConfiguration` in iOS 12, might be causing an issue. 

But other than that, I'm not sure what the issue is.

**Comment by danthorpe** [comment]
Hi @imrabti I've got a PR #888 which updates some of the CloudKit support. Perhaps you could try your project with this branch?

There were no sessions at WWDC this year, yet a couple of operations got deprecated entirely in iOS 11, and I haven't seen any updates in docs/guides. 

Also, in particular, [`CKFetchRecordZoneChangesOperation`](https://developer.apple.com/documentation/cloudkit/ckfetchrecordzonechangesoperation), had a number of changes including the introduction of `ZoneConfiguration` which effectively replaces `ZoneOptions` in iOS 12. It includes a property for the `previousServerToken`. Now, I know that this doesn't necessarily mean that usage of zone options is broken on iOS 12 - but it's interesting that it's the think that you have an issue with.

If you haven't, might be a good idea to go over the docs to sanity check your expectations of how this should all work?

**Comment by imrabti** [comment]
Hi @danthorpe that's great I hope it will fix the issue, I'll try that and confirm to you how it is working.

**Comment by imrabti** [comment]
Hi, I have tested using the PR and I confirm it is working good now as expected, thank you.
