### ISSUE TITLE
Add possibility to expose DispatchQueue from EventQueue for RxSwift Scheduler

### ISSUE THREAD

**Issue by evilutioner** [ProcedureKit/ProcedureKit#892]
We are using in project RxSwift and ProcedureKit and I unable to access to DispatchQueue to create 
SerialDispatchQueueScheduler in RxSwift for observer.

```swift
// ProcedureKit
public class EventQueue {
   fileprivate let queue: DispatchQueue
   public init(label: String, qos: DispatchQoS = .default) {
        self.queue = DispatchQueue(label: label)
  }
  ...
}

// RXSwift
public class SerialDispatchQueueScheduler : SchedulerType {
  init(serialQueue: DispatchQueue, leeway: DispatchTimeInterval =  DispatchTimeInterval.nanoseconds(0)) {
        configuration = DispatchQueueConfiguration(queue: serialQueue, leeway: leeway)
    }
  ...
}
```

Solutions1 (more appropriate way) : 
  Create init with custom queue in EventQueue class

Solution2 (simple solution):
  Change fileprivate to public property for queue property

I can create PR if need

**Comment by danthorpe** [comment]
Hi @evilutioner - this is interesting. In theory, it's not an issue to change this property to public.

But, just stepping back a second, can you elaborate on how you want to combine usage of _ProcedureKit_ and _RXSwift_? My hunch is that you're going to do something like...

```swift
protocol SchedulerProvider {
    var scheduler: SchedulerType { get }
}

extension Procedure: SchedulerProvider {
    var scheduler: SchedulerType {
        return SerialDispatchQueueScheduler(serialQueue: eventQueue.dispatchQueue)
    }
}
```

But, just wondering how you're then going to use this?

**Comment by danthorpe** [comment]
@swiftlyfalling any thoughts on this?

**Comment by evilutioner** [comment]
I can show two ways of using scheduler or not using:

```Swift
class MyOperation: Procedure {
    override func execute1() {
        _ = observable.subscribe(onNext: {
            // some work
        }).observeOn(myScheduler)
    }
    
    override func execute2() {
        _ = observable.subscribe(onNext: {
             self.eventQueue.asyncDispatch { in
                // some work
            }
        })
    }
}
```

**Comment by danthorpe** [comment]
Okay, so you'd have some base `Procedure` subclass which can be initialised (or injected) with an observable, and its `execute` method is one of the two above. And then presumably in the `// some work` you call `finish()` to end the procedure.

I haven't worked on a project which mixes the two frameworks/paradigms. Certainly interesting from a _can we do it_ perspective. I'm not entirely sure that it's a good idea, but that's a different discussion.

Of the two approaches above - I much prefer option two, as it requires no changes to the access controls in ProcedureKit as it stands. I'm guessing you would prefer option 1 - but what is the motivation behind that? What makes option 1 "better"?

**Comment by evilutioner** [comment]
@danthorpe 
> What makes option 1 "better"?

Solution 1 can prevent user to escape use you abstract layer. It can be such way:

```Swift
override func execute() {
        // some work
             self.eventQueue.queue.async { 
                // some work
            }
    }
```

**Comment by danthorpe** [comment]
I think, however, that if the `DispatchQueue` is exposed, it is a potential problem as it will be possible to dispatch work items onto the queue by-passing the lock with guarantees serial behaviour. So, while `SerialDispatchQueueScheduler` is "serial" it would effectively mean that the underlying `DispatchQueue` has _two_ serial "queues".

Perhaps a better approach is to make `EventQueue` conform to `SchedulerType` - is it a base class, or a protocol?

**Comment by evilutioner** [comment]
Please, explain how to do this, you can have a look to protocol:

```Swift
public protocol SchedulerType: ImmediateSchedulerType {
    var now : RxTime {
        get
    }
    func scheduleRelative<StateType>(_ state: StateType, dueTime: RxTimeInterval, action: @escaping (StateType) -> Disposable) -> Disposable
    func schedulePeriodic<StateType>(_ state: StateType, startAfter: RxTimeInterval, period: RxTimeInterval, action: @escaping (StateType) -> StateType) -> Disposable
}

public protocol ImmediateSchedulerType {
    func schedule<StateType>(_ state: StateType, action: @escaping (StateType) -> Disposable) -> Disposable
}

```

**Comment by danthorpe** [comment]
Looks like it's a protocol (https://github.com/ReactiveX/RxSwift/blob/master/RxSwift/SchedulerType.swift), why not add:

```swift
extension ProcedureKit.EventQueue: RxSwift.SchedulerType {
  
    func schedule<StateType>(_ state: StateType, action: @escaping (StateType) -> Disposable) -> Disposable {
        // TODO: ??
    }

    func scheduleRelative<StateType>(_ state: StateType, dueTime: RxTimeInterval, action: @escaping (StateType) -> Disposable) -> Disposable {
        // TODO: ??
    }

    func schedulePeriodic<StateType>(_ state: StateType, startAfter: RxTimeInterval, period: RxTimeInterval, action: @escaping (StateType) -> StateType) -> Disposable {
        // TODO: ??
    }
}
```

And use the public API of `EventQueue` to fulfil these RxSwift APIs.

**Comment by danthorpe** [comment]
Potentially, we could support all of this in a ProcedureKit+RxSwift mini-framework.

**Comment by evilutioner** [comment]
IMHO It's overkill

**Comment by evilutioner** [comment]
Can I make simple PR and resolve this issue?

**Comment by danthorpe** [comment]
Yeah, you can submit a PR, and it'll get discussed. But I'm pretty sure that we will not want to expose the underlying `DispatchQueue` - the whole purpose of `EventQueue` is to protect that dispatch queue.

You may not see it as an issue for your project, but I need to consider all framework consumers.

**Comment by evilutioner** [comment]
> Implementation of that extension, would effectively be similar to https://github.com/ReactiveX/RxSwift/blob/53cd723d40d05177e790c8c34c36cec7092a6106/RxSwift/Schedulers/Internal/DispatchQueueConfiguration.swift

How to created  DispatchSource from EventQueue?

```Swift
let timer = DispatchSource.makeTimerSource(queue: queue)
```

**Comment by danthorpe** [comment]
Yeah, that might be tricky without PK modifications.

**Comment by evilutioner** [comment]
> Implementation of that extension, would effectively be similar to https://github.com/ReactiveX/RxSwift/blob/53cd723d40d05177e790c8c34c36cec7092a6106/RxSwift/Schedulers/Internal/DispatchQueueConfiguration.swift

Thanks, I will try

**Comment by evilutioner** [comment]
@danthorpe 
Could you make function `makeTimerSource` as `public` ?
```Swift
func makeTimerSource(flags: DispatchSource.TimerFlags = []) -> DispatchSourceTimer { }
````

**Comment by danthorpe** [comment]
Yeah, we can do this.

**Comment by evilutioner** [comment]
> Yeah, we can do this.

Thanks!

**Comment by swiftlyfalling** [comment]
> [...] I'm pretty sure that we will not want to expose the underlying `DispatchQueue` - the whole purpose of `EventQueue` is to protect that dispatch queue.
> 
> You may not see it as an issue for your project, but I need to consider all framework consumers.

Just to highlight, I concur with the above.

A lot of the internal / private parts of ProcedureKit (especially related to the nature of how Procedures / events are executed, synchronized and dispatched) are not exposed for very considered reasons.

(An important goal is making it much harder for framework consumers to end up creating deadlocks / thread-safety issues through use of the public API.)

Haven't had a chance yet to dig into alternative possibilities to what's been suggested.

**Comment by danthorpe** [comment]
Closing this for now.
