### ISSUE TITLE
BackgroundObserver Documentation

### ISSUE THREAD

**Issue by christoff-1992** [ProcedureKit/ProcedureKit#896]
Just wondered if there is any documentation around the behaviour of the BackgroundObserver.

Or is this yet to be implemented in the updated framework.

Thanks

**Comment by danthorpe** [comment]
Hi @christoff-1992,

We don't (yet) have a dedicated guide to `BackgroundObserver` 😞. So the best documentation is the header docs associated with the class:

https://github.com/ProcedureKit/ProcedureKit/blob/2bf45aac793c6cb035743d953fe1fbef392a5fc7/Sources/ProcedureKitMobile/BackgroundObserver.swift#L33-L66

Also, it got some major TLC in https://github.com/ProcedureKit/ProcedureKit/pull/781 which has an overview of how it works.

---
What is a bit odd, is that I can't find the headers docs in the jazzy-generated docs here: http://procedure.kit.run/development/index.html so there might be a bug generating the docs outside of the core _ProcedureKit_ module. Hmm....

**Comment by danthorpe** [comment]
Does that help @christoff-1992?

If you're seriously, stuck - using `BackgroundObserver` is more or less the same as any other observer - see general docs here: http://procedure.kit.run/development/observers.html

And the overall syntax is:

```swift
let procedure - MyProcedure() // a Procedure subclass
procedure.addObserver(BackgroundObserver())
```

**Comment by christoff-1992** [comment]
@danthorpe - Thank you for such a quick response, it does help I have just been taking a look at the header documentations myself. #781 - Interesting! 👍 will have a read!
