### ISSUE TITLE
Invalid SelfBlock signature in ResultProcedure

### ISSUE THREAD

**Issue by pronebird** [ProcedureKit/ProcedureKit#900]
Hi,

It seems that `ResultProcedure` has invalid type information provided on one of initialisers:

```swift
public override init(block: @escaping SelfBlock)
```

`SelfBlock` seems to come from `BlockProcedure`. I may be wrong but it seems to me that the type alias is missing, i.e:

```swift
public typealias SelfBlock = (ResultProcedure<Output>) -> Void
```

Otherwise I don't see how it's possible to finish the `ResultProcedure` with result. 

As alternative `AsyncResultProcedure` can be used or perhaps force-cast inside of block provided into `ResultProcedure`:

```swift
let resultProcedure = procedure as! ResultProcedure<T>
```

ps: ProcedureKit v5.0.0-beta.2

**Comment by danthorpe** [comment]
Hi @pronebird - thanks for this. You are quite right - `SelfBlock` comes from the parent class. Fixing it now...

**Comment by danthorpe** [comment]
Hi @pronebird - sorry, forgot to comment back here - was wondering if you were able to check against the branch in #901? I've adjusted the init override.

When initialising a `ResultProcedure`, code-completion should show you these options (for a `ResultProcedure<String>` type):

<img width="736" alt="screenshot 2018-10-17 at 07 12 32" src="https://user-images.githubusercontent.com/309420/47065788-1af3dd80-d1dc-11e8-88b5-fbe0ab46a18a.png">

**Comment by danthorpe** [comment]
@pronebird closing this for now, fixes are in `development` branch.
