### ISSUE TITLE
Consider using ObjectIdentifier instead of UUID for Identifiable protocol

### ISSUE THREAD

**Issue by ArkadiYoskovitz** [ProcedureKit/ProcedureKit#913]
Consider using ObjectIdentifier instead of UUID for Identifiable protocol, the ObjectIdentifier is a lightweight structs that's chipper to generate then UUID, and it allows for instance uniqueness

**Comment by danthorpe** [comment]
Ohh - did not know about this: https://developer.apple.com/documentation/swift/objectidentifier Interesting....

**Comment by danthorpe** [comment]
This is done in `development`
