### ISSUE TITLE
[Question]: How to used dataTask(with request: URLRequest, completionHandler) in version 5

### ISSUE THREAD

**Issue by dvirvmoblin** [ProcedureKit/ProcedureKit#915]
In the 4.5.0 version I had this code :

let session = URLSession(configuration: sessionConfig)
        let task = session.dataTask(with: request, completionHandler: { [unowned self] (data: Data?, response: URLResponse?, error: Error?) -> Void in

and I handle the result in the completion block.

But in the last version 5.0.0 on Xcode 10 I get a compilation error the dataTask function has Ambiguous because there is 2 function with the same signature (one in the ProcedureKit and one in Foundation) 

So how to use this function ?

Thanks in ahead,
Dvir valdfogel

**Comment by ericyanush** [comment]
If you are trying to get a bare URLSessionDataTask, you can disambiguate the call by telling the compiler that your session is of type NetworkSession by changing its declaration to:

`let session: NetworkSession = URLSession(configuration: sessionConfig)` 

If you still need access to any of the other properties or functions that URLSession provides, this may not be the best solution, as the NetworkSession protocol only exposes the three factory functions for creating data, download and upload tasks.

If you don't need anything from ProcedureKitNetwork in the file that this is contained in, you can simply remove the import from the top of the file.

Ideally, if you are using ProcedureKit, you wouldn't be instantiating a URLSessionDataTask directly, and instead you would only create a URLRequest instance, and pass that into a NetworkDataProcedure instead, which will handle the setup of the data task internally.

**Comment by dvirvmoblin** [comment]
It's working - Thanks

**Comment by danthorpe** [comment]
Gonna close this for now.
