### ISSUE TITLE
'SubSequence' is not a member type of 'S'

### ISSUE THREAD

**Issue by mperovic** [ProcedureKit/ProcedureKit#929]
After updating to Xcode 10.2, I'm no longer able to compile my project. I have multiple `'SubSequence' is not a member type of 'S'` errors.

<img width="1588" alt="Screen Shot 2019-03-26 at 9 02 33 AM" src="https://user-images.githubusercontent.com/182573/54980491-28d93600-4fa6-11e9-8e08-71b22ff0264c.png">

**Comment by mperovic** [comment]
Found reason: https://developer.apple.com/documentation/xcode_release_notes/xcode_10_2_release_notes/swift_5_release_notes_for_xcode_10_2

> The Sequence protocol no longer has a SubSequence associated type. Methods on Sequence that previously returned SubSequence now return concrete types.

**Comment by ericyanush** [comment]
@mperovic It looks like you are using an older version of ProcedureKit; the initializer for MapProcedure was changed in 2fbbe3fd52e890de04c253d3a8d6d3a9e6b39ccc to utilize SubSequence. This change was shipped in ProcedureKit 5.0.

**Comment by mperovic** [comment]
You're absolutely right. Someone forced 4.5.0 in podfile.

Thanks
