### ISSUE TITLE
[Question]: Replacing ProcedureResult with Swift 5.0 Result

### ISSUE THREAD

**Issue by golanb** [ProcedureKit/ProcedureKit#933]
Hi Daniel,
Would you please consider replacing ProcedureResult<T> with Swift 5.0 Result<Success, Failure>?
Thanks

**Comment by danthorpe** [comment]
Hi @golanb I have considered this.

What are your thoughts on it? Why would it be beneficial for _ProcedureKit_ to use `Swift.Result` instead of `ProcedureResult`?

**Comment by ericyanush** [comment]
Throwing my $0.02 in here;

Initially, I assumed that it would be beneficial to replace ProcedureResult with the stdlib Result type, however, after looking at it more closely, the only benefit I could come up with was the code for ProcedureResult would be groomed and maintained as part of the Swift stdlib. That being said, I can't see the maintenance overhead of keeping ProecedureKitResult to be too high.

I even went as far as actually converting ProcedureKit to use the new Result type, and seen no real benefit in making the switch. All ProcedureKit client code that uses the ProcedureKitResult type would likely have to be updated, but the switch would provide no additional features, usability or performance. Maybe if other libraries or APIs within the standard library start using Result, there maybe additional benefits to be had, but as of now, I don't think it's worth it.

**Comment by jshier** [comment]
The biggest benefit is the ability to interop with everything else that's using the standard `Result`. It's why I suggested ProcedureKit's type be named `ProcedureResult` and one of the main reasons I drove the proposal to add `Result` to the standard library. Functionally, there's little difference of course, it just means you can pass it around and use it freely without worrying about running into another Result type.

**Comment by golanb** [comment]
I'm using ProcedureKit to simplify complex app logic in an API networking framework. That framework should eventually end up being a public SDK I would release. I thought it would be appropriate to adopt the new result type since it is almost identical. After reading @ericyanush's and @jshier's comments, I stand corrected. I agree with all the points you guys pointed out. Thank you all :)

**Comment by jshier** [comment]
I was suggesting it should be adopted, for exactly the reason you mention: so you don't have to translate between types in order to offer a clean consumable API.

In my mind, there's not reason not to adopt the type.

**Comment by golanb** [comment]
Oops... I got confused. @jshier would't I force anyone using my framework to upgrade to Swift 5.0?

**Comment by jshier** [comment]
It would require them to be using the Swift 5 compiler (Xcode 10.2), but not necessarily Swift language version 5. So yes, only when ProcedureKit is ready to make that transition can it be replaced.

**Comment by danthorpe** [comment]
Yeah, I think in summary, the _primary_ (maybe even only) benefit is that framework consumers would be able to interop with `Swift.Result` throughout their Swift codebase.

However, I don't think this is a big enough win to force through a change in _ProcedureKit_ and bump the major version at this time.

When we get closer to a release of v6 of _ProcedureKit_, then it would make sense to deprecate `ProcedureResult` and adopt `Swift.Result`.

**Comment by danthorpe** [comment]
Thanks for the comments and feedback everyone 💚.

Gonna close this for now - will pin it for visibility.
